### ISSUE TITLE
Identifiers: Remove worked example?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1008]
This was proposed for removal in #948, but this change would need to be merged against 1.1.5-dev first:

    <div class="example hint" markdown=1>

    <p class="first admonition-title">Worked Example</p>

    The **organization register prefix** for UK Companies House is GB-COH. The organization **Development Initiatives** has been assigned the company number ‘06368740’ by Companies House. The globally unique organization identifier for Development Initiatives can then expressed as follows:

    ```eval_rst
    .. code-block:: json

        {
            "scheme":"GB-COH",
            "id":"06368740",
            "uri":"http://opencorporates.com/companies/gb/06368740",
            "legalName":"Development Initiatives Poverty Research Limited"
        }

    ```

    </div>

**Comment by jpmckinney** [comment]
@romifz @pindec Why was this change proposed in #948? I can't find the discussion in the PR. https://github.com/open-contracting/standard/pull/948/commits/ce92c4fcae818134bd1e2f4a002d614aef7912a1#diff-a3cbd55f5f3a5aa29b0144cdccec3b12

**Comment by jpmckinney** [comment]
I found this comment: https://github.com/open-contracting/standard/pull/948#pullrequestreview-339915414

However, the existing worked example is in the Reference section, not the Getting Started section. We can still remove it, but I wanted to clarify that first.

**Comment by pindec** [comment]
I suggested the change because I was concerned that we would end up with two slightly different sources of information about dealing with organization identifiers - the new worked example and (as you point out) [the example in the Reference section](https://standard.open-contracting.org/latest/en/schema/identifiers/#organization-ids).

However, the Reference example does make the explanatory text around `scheme` and `id` fields clearer.

So perhaps the action should be instead of removing the Reference example, add a link to the new worked example at the end of the final paragraph of the [choosing an identifier section](https://standard.open-contracting.org/latest/en/schema/identifiers/#choosing-an-identifier), replacing the existing "See docs.org-id.guide for more information." with "See the full worked example for more information on implementing identifiers from these different kinds of organization list"?

**Comment by jpmckinney** [comment]
That sounds good to me. Can you create a branch from the 1.1.5-dev branch, and then select the 1.1.5-dev branch as the 'base' branch when creating the PR?

**Comment by pindec** [comment]
Thanks, will do.
