### ISSUE TITLE
Include government branch field for government bodies

### ISSUE THREAD

**Issue by romifz** [open-contracting/standard#1027]
Action item from the latest OCDS retreat. Description is

> Think of including a field about the branch of the government.  Investigate extension, who uses it, Colombia?

The related extension is https://github.com/sdd1982/branch, which adds a `branch` field for the branch of the government the buyer/procuring entity belongs to. As far as I can tell, the only publisher using this is Colombia.

Related: #711

**Comment by duncandewhurst** [comment]
I think that adding a field named `branch` could lead to confusion between [branches of government](https://en.wikipedia.org/wiki/Separation_of_powers) and [branch offices](https://en.wikipedia.org/wiki/Branch_office). Alternatively, the field could be named `branchOfGovernment`.

In Colombia's extension, the field is free-text. Alternatively, the field could use an open codelist with the 3 most common branches: legislature, executive, and judiciary. However, in that case the field might also need to be an array due to the [fusion of powers](https://en.wikipedia.org/wiki/Fusion_of_powers) in some parliamentary forms of government.

In any case, there hasn't been any engagement since this issue was originally opened and it seems to be relevant to only one publisher, so we should perhaps seek further input before adding it to the standard.

**Comment by jpmckinney** [comment]
This is also more a national/state-level concern than one that affects all governments/parties. I think it’s fine to leave unstandardized, but we can re-open if there is new engagement.

**Comment by yolile** [comment]
Something similar is also used in Paraguay, with new fields in `parties.details ` declared in a [local extension](https://gitlab.com/dncp-opendata/ocds_partyDetails_publicEntitiesDetails_extension), eg:

````json
"details": {
  "level": "Poder Ejecutivo",
  "entityType": "Organismos de la Administración Central",
  "type": "Entidad"
}
````

But I agree that this differs from country to country and having local extensions seems to be enough.
