### ISSUE TITLE
Search errors on standard site (since 1.1.5 release?). Some 404s and missing results.

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#1062]
Looks like search currently isn't working properly (since the 1.1.5 restructure?). 

404 example: [searching for 'prefix'](https://standard.open-contracting.org/latest/en/search/?q=prefix&check_keywords=yes&area=default) gives results with 404s for (at least) the top two.

Missing results example: searching for ['system architecture](https://standard.open-contracting.org/latest/en/search/?q=system+architecture&check_keywords=yes&area=default)' gives no results despite the new ["system architecture" sections](https://standard.open-contracting.org/latest/en/guidance/build/system_architectures/#system-architectures).

**Comment by jpmckinney** [comment]
It seems the new version of Sphinx broke the search system. I've made a change to the deploy script, so that tests will fail if the search system can't index the website. The error returned by the search system is unhelpful, so I'm deploying a new version with a longer error message. I might remove the bare try-catch, as it also contributed to hiding this error.

**Comment by jpmckinney** [comment]
Fixed https://github.com/open-contracting/standard-search/commit/41f98ff6ef758d52fb6eea43c8f89d7f16cc755a
