### ISSUE TITLE
Include taxes in values.

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#112]
From JoseLMarin on v0.3.2 

I'd suggest to consider key(s) to inform users if taxes are included or not in the amount. If taxes are included, the tax rate applied to the amount is also important to work with aggregated data.

**Comment by timgdavies** [comment]
@myroslav What have you done for handling tax in the open procurement API in the end?

**Comment by myroslav** [comment]
We'd need only VAT, thus added valueAddedTaxIncluded boolean property. See
http://api-docs.openprocurement.org/en/latest/standard/util.html#value

Unfortunately this does not cover all cases, and we are unclear of
potential changes here. Options discussed are:
- Collecting two different values, one brutto and the other - netto. And only one in cases, when tax does not apply.
- Calculation of only one of the values brutto/netto, and dropping the tax indicator altogether.

This is all because we need to compare apples to apples and oranges to
oranges, but this is not always simple, since we have multiple taxation
schemes and tender participants should have equal rights, as well as
procuringEntity should not be paying more because of these differences.

**Comment by timgdavies** [comment]
Moving in comment from @myroslav in #219:

> "There is possibility to have Tender to be conducted without VAT and to have contract value with VAT. Any analytics regarding these values (matching them) becomes quite complex.
> 
> A possible solution is to have multiple Values in contract (i.e. without VAT and with VAT). Is there more elegant solution?"

**Comment by timgdavies** [comment]
The next task here is to carry out more in-depth research into how taxes are modelled in any existing data.

**Comment by timgdavies** [comment]
Continued in #383
