### ISSUE TITLE
Review procuringEntity description

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1156]
@JachymHercher wrote in #825 

> ProcuringEntity covers three codes from eForms' organisation role: CPB wholesaler, CPB intermediary and a procurement service provider. They could either be split as they are in eForms, or they could be dealt with by extending the "fullly accurate" approach mentioned above (e.g. by adding codes such as "party receiving the items", "party distributing the items", "party signing the contract for its own use", "party signing the contract for the use by another party", "party using the items").

Re: "fully accurate", this was described as:

> We can group the "needs" / "use cases" into three levels:
> 
> - Basic: distinguishing the "buyer side", supplier, subcontractor, unsuccessful tenderers, review bodies, etc. 
> - Medium: within the "buyer side", distinguishing "buyers", "procuring entities", "central purchasing bodies", "contract implementors" (see https://github.com/open-contracting/standard/issues/548#issuecomment-727912060), etc. 
> - Fully accurate: knowing who exactly does what, i.e. organisation receiving tenders, org. processing tenders, org. signing the contract, org. whose budget is used to pay for the contract, org. sending the payment, etc.
>
> The first two are based primarily on "who they are" (often based on legal definitions), the third is rather "what they do" (often based on real world actions).  Judging from the EU, I think most systems work on the first two levels, because that's the way the legislation is written, people are used to it, and requirements it puts on manual data input. However, I think systems sometimes "dip" into the third level, but less for "analytical" purposes and more for "practical" purposes such as "who do I actually send my tender to", "who do I actually send my questions to", etc. 
> 
> In eForms, we try to cover the first two levels by [organisation role](https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/organisation-role/?target=Browse&uri=http://publications.europa.eu/resource/authority/organisation-role), while giving the possibility to go into the third level with [organisation subrole](https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/organisation-subrole/?target=Browse&uri=http://publications.europa.eu/resource/authority/organisation-subrole). 

I guess as a starting point: Is "procuring entity" a useful concept on its own? If so, then this issue is about adding subroles (see below quote). If not, then this issue is about replacing it with new options. Viz. subroles:

> OCDS does not have an equivalent of eForms' organisation subrole. Since legal definitions differ but real world actions are univeral, I think this approach might be valuable for standardization.

**Comment by JachymHercher** [comment]
> I guess as a starting point: Is "procuring entity" a useful concept on its own? If so, then this issue is about adding subroles (see below quote). If not, then this issue is about replacing it with new options. Viz. subroles:

I think both roles and subroles are useful - the former because they appear in legal discussions, the latter because they sometimes meet concrete communication (or analytical) needs. 

Concerning 'procuringEntity', a good starting point is to review the definitions (OCDS and Art. 2 of Directive 2014/24/EU): 
- 'procuringEntity': "The entity managing the contracting process." 
- (17) ‘procurement service provider’ (PSP) means a public or private body which offers ancillary purchasing activities on the market;
- (16) ‘central purchasing body’ (CPB) means a contracting authority providing centralised purchasing activities and, possibly, ancillary purchasing activities; 
-  (15) ‘ancillary purchasing activities’ means activities consisting in the provision of support to purchasing activities, in particular in the following forms: 
      - (a) technical infrastructure enabling contracting authorities to award public contracts or to conclude framework agreements for works, supplies or services;
    -   (b) advice on the conduct or design of public procurement procedures;
    -   (c) preparation and management of procurement procedures on behalf and for the account of the contracting authority concerned;
- (14) ‘centralised purchasing activities’ means activities conducted on a permanent basis, in one of the following forms:
    -  (a) the acquisition of supplies and/or services intended for contracting authorities,
    -  (b) the award of public contracts or the conclusion of framework agreements for works, supplies or services intended for contracting authorities;

There might be some legal distinction between "on behalf and for the account of" (in 15) ) and "intended for" (in 14) ), but my non-legal reading would be that (14)(b) is a type (15)(c), and thus all (14)(b) CPBs are also PSPs (but not vice versa). (14)(a) CPBs stand on their own, they are simply a 'buyer' (that passes on its purchases later on). "Managing the contracting process" (in the definition of 'procuringEntity') is part of (15)(c), which implies that a (14)(b) CPB is always a 'procuringEntity', while a PSP is a 'procuringEntity' under (15)(c) but not under (15)(a) and (15)(b). 

An example of a (15)(a) party is for example a data publisher; a example of a (15)(b) party is a law firm or EU fund consultancy that reviews the buyer's procurement documents, but does not actually manage the process. Would you agree that these currently don't have a role in OCDS under which information about them could be published? 

### Possible solutions 
Regardless of the option below, we should add two new roles: one for (14)(a) and (14)(b). (Same approach as eForms.)
#### Option 1
- 'procuringEntity' definition stays as it is, i.e. corresponds to (15)(c).
- We add two additional new roles: for (15)(a), (15)(b), 
#### Option 2
- 'procuringEntity' definition is broadened (or the term is replaced with something broader) to cover also (15)(a) and (15)(b), i.e. it becomes a PSP. 

I would go for Option 1 if there is some demand for publishing about bodies defined along the lines of (15)(a) and (15)(b). If not, I would go for option 2, which is analogous to eForms.

**Comment by jpmckinney** [comment]
I forgot #571 was already open. I'll copy these comments there.
