### ISSUE TITLE
Incorporating standardized documents into OCDS

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#1170]
Several partners are beginning to explore standardizing their procurement documents (eg their standard terms and clauses). At least one has expressed an interest in indexing these standard terms and referencing them as part of OCDS data. Starting this issue to discuss what this could look like in case others are exploring similar ideas.

**Comment by jpmckinney** [comment]
https://www.resourcecontracts.org (for extractives contracts) takes the approach of uploading an original document and then referencing terms/clauses, using a standard vocabulary for different clauses (royalty clause, etc.).

In OCDS, we offer a wide variety of fields (especially in extensions) to cover a range of terms. In order to incorporate fields for additional terms/clauses, we would need specific examples of those terms/clauses.

That said, if the terms are largely the same across contracts, it might be very repetitive to include those standard clauses in the data for each contracting process. It might instead be better to simply link out to the contract template.

**Comment by mgifford** [comment]
Interesting to see the resource contracts.  I'd be curious to see other examples from other sectors. Neat that it is global. 

If we could get large organizations to just begin from a common template theoretically we could make them easier for everyone to read. So much of the content is just repeated between contracts, but vendors need to scrape through each one because they are often pretty unique.

**Comment by jpmckinney** [comment]
Related #1169. (This issue is about adding fields for more metadata from documents to OCDS, whereas #1169 is about modelling the documents themselves using other standards.)

Many governments follow templates, but there is often a fair amount of customization of the template. Beyond templates, there are resources like https://contract-design.worldcc.com and https://govlab.hks.harvard.edu/guidebook-crafting-results-driven-request-proposals-rfp to simply write simpler documents (rather than more standardized documents).
