### ISSUE TITLE
Modeling more aspects of 'cost' than price in OCDS

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#1172]
We recently received the following thoughts from a partner in the US:

"the mistake we've made in the US is we measure what is easy to measure: numbers of transactions, contractor demographics (size, location, social/economic status), correlation between budget and spend, volume of competition, etc. Sadly, none of that matters (except for, say, corruption control, which is not the ultimate "purpose" of procurement - obtaining the goods and services governments need to govern/serve, etc.).

Conversely, I (personally) continue to believe that what the US needs most is (alas) exactly what the OCDS does not offer.  We need OUTPUT-based data rather than PROCESS (or transaction) based data.  Among other things, we need to capture better data on:

* Customer satisfaction - from end-user satisfaction, to head of agency/ministry satisfaction;
* Life Cycle Cost/Total Cost of Ownership as opposed to purchase prices;

And, on that note, we need to create the (possibly AI) tools to include "externalities" or "effects" (with regard to climate, etc.) in addition to transaction costs, operating costs, maintenance costs, and disposition costs.

The wild card in all of this is the requirements-to-outcome correlation, which is poorly studied/tracked.  Specifically, for example, did the government USE the things they bought?  (If a government bought more than it needed, that "waste" reflects poorly on the procurement system, but it is rarely measured/captured.)  But, obviously, that's a topic for another day.

Sadly, ... currently ... I don't see OCDS being the vehicle to help us address those needs"

@PaulBoroday recently mentioned that in the mtender system they are trying to capture more aspects of 'cost' than price so curious how this is being modelled in Moldova and whether there are lessons learned to add to the OCDS documentation.

**Comment by jpmckinney** [comment]
The partner covers a lot of issues not related to cost/price, but related to outputs/outcomes (customer satisfaction, climate externalities, "requirements-to-outcome", whether the goods/services were used).

It's important to keep in mind that OCDS is a data format for disclosing information. It is not an IT system for collecting or managing information. As the partner notes, this data is not captured/measured and/or is poorly studied/tracked. So, the solution is, first, to build an IT system to track this data. The format in which that data is then publicly disclosed is a secondary concern.

It puts the cart before the horse to define a data format without first understanding what specifically a government seeks to capture - like deciding the gift-box before choosing the gift. We could spend a lot of time defining models for data that we wished governments would track, but aren't. In terms of priority, the focus has been on standardizing what governments already track (where there is still a lot of work to do), which provides a much more secure foundation for standardization.

----

In terms of cost/price, the partner mentions "Life Cycle Cost/Total Cost of Ownership as opposed to purchase prices" and "transaction costs, operating costs, maintenance costs, and disposition costs".

Many jurisdictions solicit bids expressed in terms of "cost," not simply "price". For example, some contracting processes require the submission of a spreadsheet to breakdown the costs mentioned. I do not know a jurisdiction that publishes this bid information (even for the winning bid), likely due to concerns over commercial confidentiality. As such, it is a difficult target for standardization for the same reasons as above.

That said, in addition to the prospective cost in the bid, there is the actual cost. However, the contracting process is not the correct unit on which to perform this analysis. For example, one procedure might procure machinery, with later procedures for annual maintenance, urgent repairs, fuel/electricity, etc.

In the context of infrastructure, some of these costs can be united at the project level in OC4IDS, which contains multiple contracting processes. We could explore a generic approach for a container of related contracting processes – but again, I do not know a jurisdiction that brings together all contracts for a given piece of machinery, etc. We would need at least one such jurisdiction to begin modelling an appropriate approach.
