### ISSUE TITLE
Merge the submissionTerms extension

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/standard#1183]
> We can consider merging the submission terms extension into core. That extension supports the only clear use case from the discussion in #322, which is distinguishing opportunities for which electronic submission is required/allowed/not allowed.

https://github.com/open-contracting/standard/issues/322#issuecomment-763810724

[submissionTerms extension](https://github.com/open-contracting-extensions/ocds_submissionTerms_extension)

**Comment by ColinMaudry** [comment]
If the submissionTerms extension ends up being added in core:

- [ ]  the deprecation description for `submissionMethod` (https://github.com/open-contracting/standard/issues/322#issuecomment-767625406) must be edited to include guidance explaining how the information entered in `submissionMethod` can be expressed in submissionTerms object

**Comment by ColinMaudry** [comment]
The description could look like this (inspired by the description of `Budget.source`:

> The submission method field used unclear or irrelevant codes. As a result, it has been deprecated in version 1.2. The submission terms field (tender.submissionTerms) can be used to describe the electronic submission policy of the procedure.

**Comment by ColinMaudry** [comment]
It would be sensible to move `submissionMethodDetails` to submissionTerms if it ends up being added to core (cf https://github.com/open-contracting/standard/issues/322#issuecomment-767626046).

I mean depracating `submissionMethodDetails` and adding it to SubmissionTerms. However that might not be feasible in a minor version. It may be simpler to wait for 2.0.

**Comment by jpmckinney** [comment]
`submissionMethodDetails` is a top 100 field according to [this sheet](https://docs.google.com/spreadsheets/d/1HJbqmgoM1wOFyQfmv7WZXjvyyO6hzKpquiMwtMFo8AE/edit#gid=1299987550).

The [submissionTerms](https://extensions.open-contracting.org/en/extensions/submissionTerms/master/schema/) extension doesn't have a `description` field like other extensions, like [bidOpening](https://extensions.open-contracting.org/en/extensions/bidOpening/master/schema/), because `submissionMethodDetails` already existed.

I don't think the benefit of a predictable field path outweighs the cost of a deprecated field. So, I would prefer to create a 2.0 issue if this issue is closed.

**Comment by jpmckinney** [comment]
When merging into OCDS, we should review field titles/descriptions against the style guide (as part of https://github.com/open-contracting/standard/issues/850). I think it conforms since it is a recent extension, but we can do a quick check.

Also, we should rename `electronicCataloguePolicy` to `electronicCatalogPolicy`. We will need to notify the UK and Scotland about this when contacting them about the OCDS 1.2 upgrade.

And, we should close this issue: https://github.com/open-contracting/ocds-extensions/issues/169

**Comment by jpmckinney** [comment]
Submission terms has many fields now that might only be used in the EU.

The reason for merging this extension was to offer to migrate the 'electronicSubmission' code from the deprecated `submissionMethod` field to the new `electronicSubmissionPolicy` field.

I think we should only merge that field.

We can make a 1.2 version of the extension that removes this field.

**Comment by odscjen** [comment]
So we're just moving `submissionTerms.electronicSubmissionPolicy`?

Noting that this will need to be moved into the Lots extension as well in this case.

@jpmckinney

**Comment by jpmckinney** [comment]
Hmm, let's maybe keep the field in the extension, while adding it to 1.2. Users of 1.2 and of that extension will cause the extension to overwrite the 1.2 field, but we can commit to keeping them in sync. That way we don't have to change lots and have multiple versions of the extensions for 1.1 and 1.2.

**Comment by jpmckinney** [comment]
Created follow-up issue for Lots: https://github.com/open-contracting/ocds-extensions/issues/212
