### ISSUE TITLE
Bids: Add support for disclosing notified suppliers

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1245]
In Paraguay, some tendering process require the Procuring Entity to send invitations to bid to certain suppliers. These invited suppliers can or not make a bid then and become a tenderer. An example can be found here: https://www.contrataciones.gov.py/licitaciones/convocatoria/362337-construccion-polideportivo-9no-etapa-1.html#invitados

To publish this information it is proposed to add an array of invitedSuppliers (organization reference) to tender and  "invitedSupplier" role in the Organization roles codelist.

Example:

```json
 {
 "parties": [
    {
         "id": "2340874-0",
         "name": "BERLINDA PARRA NUÑEZ",
         "roles": ["invitedSupplier"]
    } 
 ], 
  "tender": {
      "invitedSuppliers": [
            {
               "id": "2340874-0",
               "name": "BERLINDA PARRA NUÑEZ"
           }
       ]
  }
}
```

**Comment by dwasyl** [comment]
What about something along the lines of 'interested' organization?

Would that be different than using bid status of `invited`?

Related, and perhaps this needs a separate ticket, but one of the challenges we have is the lack of any specific point to hold a list of planholders (interested parties that have downloaded/accessed the tender documents). Often the 'invitation' process here comes from adding a potential bidder to the planholder list. In some ways the entire planholder list is a list of potential bidders, but that's not really how we handle the information.

**Comment by jpmckinney** [comment]
Noting comments in this PR: https://github.com/open-contracting/standard/pull/1225#discussion_r589624278

**Comment by ColinMaudry** [comment]
@jpmckinney @yolile Are you ok to solve this with an 'invitedToParticipate' partyRole code? I think it covers the following use cases:

- Second stage of framework agreement
- Design contests invitations
- Selective and direct procedures in general

I don't think it necessary to add a `tender.invitedToParticipate` field (like in https://gitlab.com/dncp-opendata/ocds_tender_notifiedsuppliers_extension), as it means repeating information. However, it would follow the pattern we use for tenderers ('tenderer' partyRole code + `tender.tenderers`).

If adopted, this role should be mentioned in several places (at least in the EU profile instead of 'selectedParticipant').

**Comment by jpmckinney** [comment]
I think having a code without a field is fine. Is the choice of term 'invitedToParticipate' based on something?

**Comment by ColinMaudry** [comment]
"invited" was found in MAPS (https://github.com/open-contracting/standard/issues/1245#issuecomment-795229360), although UNCITRAL and GPA use it meaning "exclusively invited". That's fine for the "FA 2nd stage" and "selective/limited procedures" scenarios, but is a bit of a stretch in the case of design contests.

"participate" is a broad terms that intends to cover many ways to join a contracting process. In our master glossary, it only appears in "request for participation". 

If you find it too broad, we could add one code in core for exclusive invitations, and leave one code in eu extension for design contests.

**Comment by jpmckinney** [comment]
Roles tend to be noun phrases (procuring entity), not verb phrases (invited to participate), so maybe 'invitedParticipant'?

**Comment by yolile** [comment]
I think that 'invitedParticipant' is fine

**Comment by duncandewhurst** [comment]
This issue was originally about non-exclusive invitations to participate. The research in https://github.com/open-contracting/standard/issues/1245#issuecomment-795229360 concludes that:

> "Invitation" tend to be used when the possibility to submit is exclusive.

As such, I don't think we should use 'invitedParticipant' to describe non-exclusive invitations. I don't think 'notifiedParticipant' is too broad - implicitly, the notification is about the contracting process.

> Related, and perhaps this needs a separate ticket, but one of the challenges we have is the lack of any specific point to hold a list of planholders (interested parties that have downloaded/accessed the tender documents). Often the 'invitation' process here comes from adding a potential bidder to the planholder list. In some ways the entire planholder list is a list of potential bidders, but that's not really how we handle the information.

The 'interestedParty' code can be used to represent organizations that have downloaded or accessed the tender documents.

**Comment by jpmckinney** [comment]
I'm not 100% sure on the term. "invited/notified participant" seems like it contains a contradiction, as an entity can't be participating if they have only just been notified. In the time since this issue was last discussed, the style guide was updated to prefer "potential supplier" for such entities. We could do "notifiedPotentialSupplier", which is long, but correct...

https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/style_guide.html#word-choice

**Comment by duncandewhurst** [comment]
Good point. The other alternative is 'notifiedOrganization', which would cover cases where other interested parties that are not potential suppliers are notified about a contracting process; for example, in the Red Compartida PPP, the planning stage included a feedback process for the draft tender documentation, in which organizations that were not potential suppliers submitted comments.

**Comment by jpmckinney** [comment]
If there's only a use case for the broad semantics, then we can use it (similar to Colin's comment here https://github.com/open-contracting/standard/issues/1245#issuecomment-793978368).

However, if there's a use case to pick out the organizations that were invited to participate as potential suppliers, then the narrower code is needed.

**Comment by duncandewhurst** [comment]
I checked back to Red Compartida and it looks like they only published a [list of organizations and individuals that submitted an expression of interest](http://www.sct.gob.mx/red-compartida/inversionistas-4a-eng.html) and a [list of organizations that submitted comments on the draft tender documentation](http://www.sct.gob.mx/red-compartida/inversionistas-4b-eng.html), which are both covered by the existing 'interestedParty' role, as is @dwasyl's scenario in https://github.com/open-contracting/standard/issues/1245#issuecomment-794440377.

So that leaves us with the original question from Paraguay, which is indeed about invitations to participate as potential suppliers, so I'm happy to go with 'notifiedPotentialSupplier, even if it is a bit long.

**Comment by jpmckinney** [comment]
In this issue, I think we only have evidence for Paraguay as a potential user of this new code. That said, I know in Canada (at all levels of government) it's common to put together supplier lists and to notify the vendors on those lists, so it's a common enough procurement concept that I figure it can be added without further evidence/demand.

**Comment by jpmckinney** [comment]
Noting that UK FTS has a related concept of indicating that tender notices will only be provided to dynamic market members. It does so with an additional field: tender/communication/futureNoticeRecipients = "Members only"
