### ISSUE TITLE
Incorrect manually entered award values

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1295]
In Ecuador, they have identified some cases where the awarded values, manually entered into the system by the procurement entities, are incorrect. They identified these errors by comparing the awarded values against the budget values (the budget values are connected to the budget system and filled automatically so that values are considered correct). In this case, as they know the values are incorrect, they could use another field to disclose this "incorrect" information and not set the award/value. 
They can have an extension instead, using another field like `valueEntered` to disclose the known incorrect award value.

cc @jpmckinney

**Comment by jpmckinney** [comment]
Thanks for logging the issue!

If we hear of similar cases, we can consider a common approach and re-open this issue.

For now, I will tag it as a local extension and close it.

**Comment by jpmckinney** [comment]
In the UK CRM-7381, a user can select a corporate register from a dropdown, or manually enter the register's name if it is not in the list. Since the manual entries are non-standardized, one option is to use `scheme` for dropdown entries and `schemeEntered` for manual entries. This separates data with a known issue, and makes a (narrow) semantic distinction.
