### ISSUE TITLE
Better Guidance/Map structure

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1300]
I think we can improve https://standard.open-contracting.org/latest/en/guidance/map/ with the following steps:
1) Remove the title and level (not the content) "Map your data to OCDS" in Guidance/Map. Semantically, the title "Map your data to OCDS" is identical to "Map" above it, which I find confusing. Furthermore, it will allow us to reduce the overall depth of the guidance/map section. The text in "Map your data to OCDS" can be put under two new sections: "Mapping templates" (first four paragraphs) and "Localizing OCDS" (last paragraph). This will have the added benefit that https://standard.open-contracting.org/latest/en/guidance/map/localization/ will no longer be linked to in the table of contents without having a heading in the text one level above it, which is currently the (anomalous) case. The sections "Mapping organisation identifiers", "Working in parallel", "Splitting up the work" and "Mapping the hard cases" will consequently be directly under "Map". 
2) Remove "Mapping organisation identifiers" (including the content), because it only contains links to two better resources on organisation identifiers (and copy-pasted text from them), one of which is in just the neighbouring section "Mapping the hard cases" and also contains a link to the other resource. 
2) Rename "Mapping the hard cases" to "The hard cases". (Just a detail, but probs no need to repeat "Map", plus, arguably and not quite consistently with the general headline, some sections such as "Organisation identifiers" and "Personal identifiers" are not about mapping, but about filling in.) 
3) Reorder the sections by meaning, e.g. so that we first talk about the "people/organisational topics" and then "data topics". I would suggest:
    - Involve the right people 
    - Identify your data sources 
    - Working in parallel 
    - Splitting up the work
    - Mapping templates
    - Localizing OCDS
    - The hard cases
    - Extensions
    - Linked Standards
    - Wrapping up

**Comment by jpmckinney** [comment]
Sounds good in general!

* "Working in parallel" is a single paragraph, so we can consider whether to just merge it into another section or the intro.
* We use verb clauses as heading names in the guidance pages ("Involve the right people", etc.), so we should try to follow that style for the others ("Split up the work", "Address the hard cases", "Consider extensions and linked standards").
* I think it's better to "Download the mapping templates" before "Split up the work", since it's less clear what "the work" is until a publisher has looked at the template.
* Since the first clause about localization is to say that it should be done before mapping, we can just put "Localize OCDS to your context" before "Download the mapping templates".

The navigation issues will be largely resolved by the new theme, but these suggestions improve the flow of the text in any case.

**Comment by JachymHercher** [comment]
Should I make a PR?

**Comment by jpmckinney** [comment]
Yes, please do :)

**Comment by JachymHercher** [comment]
PR ready. Compared to the discussion here, it proposes the following (cosmetic) changes:
- Address the hard cases --> Deal with the hard cases
- Extensions --> Consider using extensions
- Linked standards --> Link OCDS with other standards
- Wrapping up --> Wrap up

additionally, I proposed changing a couple of words in the text. 

As you suggested, I moved working in parallel into the intro.
