### ISSUE TITLE
Fix markup to avoid unwanted links

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1309]
linkify automatically hyperlinks URLs. We need to:

* Add backticks around release.id in the schema
* Remove the sentence about buyandsell.gc.ca from itemClassificationScheme.csv (no other code has a similar sentence)

Once that's done, we can remove the lines in `conf.py` that ignore the auto-created links.

**Comment by Ravf95** [comment]
> Add backticks around release.id in the schema

I understand that is for prevent because if we remove `'^http://(?:identifier|release).id$'` from ignore list nothing happens (at least in the web reference of the schema), the same case for `identifier` word. Should the ignore list work with [changelog.md](https://github.com/open-contracting/standard/blob/1.2-dev/docs/history/changelog.md)? (e.g https://standard.open-contracting.org/latest/en/history/changelog/?highlight=release.id#schema-definition-updates)

Currently, only these paths have a description that contains `release.id` in the schema

- contract/amendments/amendsReleaseID
- constract/amendments/releaseID

**Comment by jpmckinney** [comment]
I don't understand the question, but we should still add the backticks.
