### ISSUE TITLE
Update guidance related to the planning stage/process for OCDS 1.2

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1362]
Changes that can be made in 1.1 (to avoid conflicts):

* [x] Update the unsuccessful processes worked example to have one ocid for the planning stage, another for the unsuccessful tender, and a third for the successful tender.
   For the third ocid, we can either have two entries in the related process array, for the unsuccessful tender and the planning process, or we can just have one for the unsuccessful tender.
* [x] Update all the JSON examples where the planning object is used. In cases where the planning object is not relevant to the example, it can simply be removed from the JSON.
* [x] Check whether to rephrase "planning stage" in these worked examples: milestones, organizational_units, unsuccessful_processes

Changes that need to be made in 1.2:

* [x] Update the versioned release example at the bottom of `records_reference.md`
* [x] In `codelists.md`, replace "the requirements identified at the planning stage" with "identified needs"

**Comment by yolile** [comment]
As part of #1414, I've updated the unsuccessful tenders example, including its text and JSONs. I've also updated the text and JSONs of the organizational_units worked example. 
However, for the milestones example, I'm not sure what to do in the  ["Planning and tender milestones"](https://standard.open-contracting.org/latest/en/guidance/map/milestones/#planning-and-tender-milestones) example. Here the example shows how to update a planned milestone when the tender is published. If we change this to have two separate contracting processes, should we update the milestone `dateMet` in the first (planning) contracting process, or in the second one (tender process)? Note that, in the example, when the milestone is met, the tender has also an `id` and the 'active' status.

For the other JSONs that contains a planning object:

- [Change history guidance](https://standard.open-contracting.org/latest/en/guidance/build/change_history/): here the first release of the example is a planning release. Should we simply remove the planning section from there? (and remove the planning section from all the JSONs in there as well)
- [Merging](https://standard.open-contracting.org/latest/en/guidance/build/merging/#fields), the planning object is mentioned just for one example, that it is about the merging routine and not about the planning itself, so I guess we could change this one for another example, maybe with a 'tender' and a 'tenderUpdate' release instead of 'planning' and 'tender'

**Comment by jpmckinney** [comment]
In the [Communication](https://extensions.open-contracting.org/en/extensions/communication/master/) extension, we have a `futureNoticeDate` field, because the future notice date is important for bidders' use cases. In general, universal or very common events should have fields, whereas milestones should be for less common or procedure-specific events.

In practice, I don't know any system that tracks its performance with respect to anticipated publication date and real publication date (the main use case for milestone statuses). At any rate, it would be straightforward to compare the futureNoticeDate to the datePublished #892. So, I think that particular example should be removed/replaced.

Change history guidance: Sounds fine to me.

Merging: Yes, let's do that.

**Comment by yolile** [comment]
> In practice, I don't know any system that tracks its performance with respect to anticipated publication date and real publication date

In Paraguay, during the planning stage, they include the estimated tender date, but that is disclosed in a separated field, similar to `futureNoticeDate` (but in planning not in tender)

**Comment by yolile** [comment]
> In codelists.md, replace "the requirements identified at the planning stage" with "identified needs"

Was made in https://github.com/open-contracting/standard/commit/b31a5c0aa9fd7d55dd197708a942a13b76ea5e7c#diff-d6958c79ed9293ec0b969c4db1ebbeeeeb6542bc6d2124e25b01769896e5b7fc

> Update the versioned release example at the bottom of records_reference.md

The `records_reference.md` mentions a planning stage, but the JSON file doesn't have one 🤷🏻 So I will change "This shows that the amount changed between the tender stage and the planning stage while the currency did not." to "This shows that the amount changed between the tender stage and a tender amendment while the currency did not." and I think that's the only thing we are missing to close this issue.

**Comment by jpmckinney** [comment]
Sounds good!

**Comment by yolile** [comment]
Closed by #1472
