### ISSUE TITLE
tender.submissionMethodDetails: review description

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1397]
Per https://github.com/open-contracting/standard/pull/1200 we don't have a `submissionMethod` field anymore in OCDS 1.2. 
But we still have a `submissionMethodDetails` field which description is 

> Any detailed or further information on the submission method. This can include the address, e-mail address or online service to which bids are submitted, and any special requirements to be followed for submissions.

Maybe, we shouldn't use the term "submission method" there anymore. And, we also have now extensions like [submission terms](https://extensions.open-contracting.org/en/extensions/submissionTerms/master/) where we can put some information about the bids submissions.

**Comment by jpmckinney** [comment]
At minimum we should remove "detailed or further", and describe what is meant by submission method. The description of `submissionMethod` was:

> The methods by which bids are submitted, using the open submissionMethod codelist.

We didn't add a free-text field in the submission terms extension, because `submissionMethodDetails` already satisfies that need. While it would be cleaner to nest a free-text field under `submissionTerms`, it is an unnecessary change in terms of backwards-compability. So, we should keep the field, and refer to the submission terms extension as an option for structured data, like we do in other fields.

**Comment by yolile** [comment]
closed by #1442
