### ISSUE TITLE
`method` codelist: consistency and semantics

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1399]
The current descriptions of codes in https://standard.open-contracting.org/1.1/en/schema/codelists/#method are: 

> Open | All interested suppliers can submit a tender.
Selective | Only qualified suppliers are invited to submit a tender.
Limited | The procuring entity contacts a number of suppliers of its choice.
Direct | The contract is awarded to a single supplier without competition.

The use of suppliers is incorrect, see https://github.com/open-contracting/standard/issues/1398. Furthermore, I would say the structure could be more uniform, e.g.: 

> Open | All potential suppliers can submit a bid.
Selective | Only previously qualified potential suppliers can submit a bid.
Limited | Only potential suppliers chosen by the buyer or the procuring entity can submit a bid.
Direct | Only a single supplier chosen by the buyer or the procuring entity can submit a bid. 

Depending on the outcome of the discussion in https://github.com/open-contracting/standard/issues/1395, we might also need to slightly change the semantics.

**Comment by jpmckinney** [comment]
We had started with the exact GPA wording, but we substituted 'bid' and now 'potential supplier' so I think it is fine to make whatever changes are appropriate for clarity.

> Only previously qualified potential suppliers can submit a bid.

This can be confusing, because some jurisdictions maintain qualified supplier lists, that exist outside a procurement procedure. (That said, in many such cases, the buyer does a limited invitation from the list.)

In any case, for 'selective' we want to be clear that it covers cases where the suppliers are qualified *during* the procedure.

In #1395 I had suggested "All interested suppliers can qualify to submit a bid", which is a bit closer.
