### ISSUE TITLE
Review occurrences of publication plan in docs

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1407]
From CRM-6496: 

> we should review the occurrences of the publication plan in the OCDS documentation, decide whether it is supporting/necessary in that step (and if it duplicates another template). If it's not needed, we can remove it from that step. And if it's removed from all steps as a result, that's fine.

cc @jpmckinney

**Comment by yolile** [comment]
The publication plan template has the following sections:
1.  Goals (design)
2.  Priority data  (map)
3.  Priority documents
4.  Technical architecture (build)
5.  Publication policy (publish)
6.  Roadmap (iterate)

For 1 we can put that section as part of the Technical Assessment template update work in CRM-5284, for 2 and 3, we can integrate that into the Field Level Mapping template itself. 4 and 5 are already covered by the publication policy template.
If we agree on replacing all the sections of the document with other existing templates, then:

In the standard documentation, the publication plan is mentioned in 3 different stages:

- Design: 
  - It is the action in the ["Understand your context"](https://standard.open-contracting.org/latest/en/guidance/design/#understand-your-context) section. A "scoping study" is also mentioned. We could replace it here with the Technical Assessment template, or just removing that action from there.
  - And then, at ["Set your goals and priorities"](https://standard.open-contracting.org/latest/en/guidance/design/#set-your-goals-and-priorities), for documenting goals and priorities. We can refer to the mapping template, or remove that Action from there
  - However, then we have a specific section for ["Develop your publication plan"](https://standard.open-contracting.org/latest/en/guidance/design/#develop-your-publication-plan). We could remove this section entirely
- Map:
  - At the general "Map" [section](https://standard.open-contracting.org/latest/en/guidance/map/#map), we mention "As you make progress through this phase, we encourage you to update your publication plan, in order to help set priorities and ease communication within your team, with your stakeholders, and with the OCDS Helpdesk. You can start by filling in the Goals (design) section.". We could point to the Technical Assessment template instead.
  - Then we mention that the publication plan should be updated again at the "Identify your data sources" [section](https://standard.open-contracting.org/latest/en/guidance/map/#identify-your-data-sources)
  - And finally, at the "Wrap up" [section](https://standard.open-contracting.org/latest/en/guidance/map/#wrap-up). We can just remove that sentence.

- Build:
  - At the "Build" main [section](https://standard.open-contracting.org/latest/en/guidance/build/#build), to document the selected architecture. We could replace that by mentioning the Publication Policy instead.

**Comment by jpmckinney** [comment]
1. I think the instructions in the Guidance are already better than in the template. We can just remove the prompt to use the publication plan.
2. Priorities need to be higher-level than individual fields. The field-level mapping is also already too long and complex. That said, the [technical assessment](https://docs.google.com/document/d/1DcKHvYKCpZVpLb74sKdcu39qVG_yf2luwr5OG24GobM/edit?pli=1#heading=h.btd2a4srx3yi) already has a list of concepts to disclose in section 4.4, so we can just add instructions about prioritization.
3. Similarly, section 5 of the technical assessment deals with documents, so there can be instructions about prioritization. Having said that, partners struggle to know which fields are priorities (which is what Camila has helped some people with). So. maybe we should just have a general prompt to prioritize according to which concepts/documents are required for the goals, and to contact OCP/helpdesk for assistance. We can also link to our use case/indicator resources.
4. This is covered by technical assessment sections 2 and 3 for source systems and 8.1 for technical architecture. The publication policy comes much later, because it only details the systems *actually used* in the implementation, whereas the technical assessment is more about understanding context. I think the short section 8.1 is better than the plan template, since no one knows their technical architecture at the stage of preparing a publication plan.
5. Yes, this is the publication policy itself.
6. Not that helpful, so fine to lose.

So, yes, we should replace all references to the publication plan with similar content/links, or remove the content.
