### ISSUE TITLE
mapping of notice type information

### ISSUE THREAD

**Issue by odscjen** [open-contracting/standard#1469]
In the [pilot OCDS publication for Canada](https://open.canada.ca/data/en/dataset/60f22648-c173-446f-aa8a-4929d75d63e3) an additional field has been used, `tender/noticeType`. The values used within this field are:
* ["invitation to Tender (ITT)"], 
* [“Advance contract Award Notice (ACAN)”], 
* [“Notice of Proposed Procurement (NPP)”], 
* [“Request for Proposal (RFP)”], 
* [“Request for Quotation (RFQ)”], 
* [“Request for Standing Offer (RFSO)”]

The initial thought was to map to `procurementMethodDetails` but as these values relate to the tender notice type (as the field name suggests) rather than the contracting process that perhaps wouldn't make sense in the context of a compiled release? 

It's therefore unclear how best to map this data. Possibly using `tender/documents/documentTypeDetails` extension https://gitlab.com/dncp-opendata/ocds_document_type_details?

**Comment by jpmckinney** [comment]
Related: #750 #1144

Canada's terms are defined here: https://buyandsell.gc.ca/for-government/buying-for-the-government-of-canada/solicit-bids/types-of-bid-solicitations

These are all different types of procedures (each procedure uses a different initial notice), so `procurementMethodDetails` would be appropriate.

Right now Canada is using the pair `procurementMethod` and `procurementMethodDetails` for:

* open: All interested suppliers may submit a bid
* qualified: If 2+ bids offer Canadian goods/services other bids will not be considered
* qualified: Suppliers on permanent list or able to meet qualification requirements
* qualified: The bid solicitation document will be sent directly to Conforming Suppliers.  

Note that 'qualified' is not an allowed code for `procurementMethod`. My understanding is that it should be 'selective'.

* "All interested suppliers may submit a bid" is the description of the 'open' code. This content is not needed.
* "If 2+ bids offer Canadian goods/services other bids will not be considered" is more like `tender.selectionCriteria` (a new field scheduled for 1.2). It's an interesting sort of conditional criterion that I haven't seen before.
* For "Suppliers on permanent list or able to meet qualification requirements", the second clause is the meaning of 'selective', and the first clause is more or less a repetition, since the only way to get on the list is to be qualified. So, this content is not needed.
* "The bid solicitation document will be sent directly to Conforming Suppliers." This is more about communication, for which we have an [extension](https://extensions.open-contracting.org/en/extensions/communication/master/). In the EU, we [modelled](https://standard.open-contracting.org/profiles/eu/latest/en/forms/F02/#I.3) restricted access to solicitation documents as a participation fee, though access can be restricted without fees. This might instead involve a change to the communications extension.

So, all told, `procurementMethodDetails` is the correct mapping, and the content that is currently in `procurementMethodDetails` either belongs elsewhere or nowhere.

**Comment by jpmckinney** [comment]
I've opened an issue for the last bullet: https://github.com/open-contracting/ocds-extensions/issues/178
