### ISSUE TITLE
`Tender.awardPeriod`: consider renaming it to `evaluationPeriod`

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1473]
This issue was raised during a conversation with a future publisher:

The definition of `awardPeriod` refers to the start and end of the evaluation period:

> The period for decision making regarding the contract award. The end date should be the date on which an award decision is due to be finalized. The start date may be used to indicate the start of an evaluation period.

However, the name suggests that the field is more about the period when the award will be made, which could confuse some users. We could consider if we should rename this to something more explicit, for example, `evaluationPeriod`

**Comment by jpmckinney** [comment]
We typically only deprecate and rename fields when they present a severe semantic issue. That's because the more renames we have, the less standardized the data is across versions.

I don't think this is severe enough. The only recent example is `eligibilityCriteria`, whose semantics were horribly unclear. For `awardCriteria`, the semantics are clear – it's just the name that's sub-optimal (same for `tenderers`, etc.).

For the same reason we aren't renaming `tenderers` or `tenderPeriod` to `submitters` and `submissionPeriod`, I think we close this issue.
