### ISSUE TITLE
Replace "contracting process" with "contract" in fields linked to budget and value

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1516]
1) Fields in `budgets` and `Budget` use formulations such as "budget [....] which provides funds for this contracting process". 

    This is possibly splitting hairs - I'm not sure - but anyway: 
     - The budget doesn't "fund" the contracting process (e.g. in the sense of people working on the process), it is rather/perhaps "reserved" for the process. 
    - More specifically, the main story isn't about the money and the process, but the money and the future/eventual contract. 

     Shouldn't we replace the phrasing along the lines of "funds a contracting process" with "will fund future contract(s)" or "will fund the eventual contract(s)"? 

     (We could also talk about "funds contracts that will stem from the contracting process(es) stemming from this planning process [where you are publishing the budget block]", but that might be a slight overkill.)

___ 

2) Similarly, the descriptions of `tender.minValue` and several `value` and `amount` fields contain "A negative value indicates that the _contracting process_ may involve payments from the supplier to the buyer". Wouldn't it be more precise to say that the _future contract(s)_  may involve payments from the supplier to the buyer"?

**Comment by jpmckinney** [comment]
1. Yes, the language around budgets is old and the understanding at that time was unsophisticated. You might find inspiration (or perhaps further errors!) in https://extensions.open-contracting.org/en/extensions/budget/master/ and https://extensions.open-contracting.org/en/extensions/budget_and_spend/master/
2. Yes, that would be more precise. We can make that change.

**Comment by odscjen** [comment]
In checking for other fields that might suffer the same phrasing issue around contracts vs contracting process or negative values:
1. `transaction` "A spending transaction related to the contracting process." Should this be "A spending transaction related to the contract." as it is used with respect to a specific contract (appearing in `contracts.implementation.transactions`)?
2. `awards.value` "A negative value indicates that the award may involve payments..." Is it not the contracts that will result from this award that will involve payments rather than the award itself? So change to "A negative values indicates that the future contract(s) resulting from this award may involve payments..."

**Comment by jpmckinney** [comment]
1. Yes to "contract" for transactions.
2. Yes. I think we can omit "future" in this instance, as "contract(s) resulting from this award" already entails that they are in the future with respect to the award.
