### ISSUE TITLE
Simplify, align and clarify related processes

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1520]
I have a few suggestions linked to related processes, please see numbered items below. Let me know if they make sense in principle and I would then prepare a concrete draft.

The description of `relatedProcesses` is           

> The details of related processes: for example, if this process is followed by one or more contracting processes, represented under a separate ocid. This is commonly used to refer to subcontracts and to renewal or replacement processes for this contract.

The description of `RelatedProcess` 

> A reference to a related contracting (or planning) process: generally one preceding or following on from the current process.

The text from https://standard.open-contracting.org/staging/1.2-dev/en/schema/codelists/#related-process 

> The related process block is used at the release level to point backwards to prior processes, such as planning or framework establishment, and at the contract level to point onwards to subcontracts or to renewal or replacement processes. The related process codelist determines the kind of relationship that is being described.

___ 

(1) From the descriptions above, it seems that we want users to mark related processes both in the parent release and in the child release. Why do we want that? Isn't it enough to just mark related processes in the child release? eForms only links from child processes to parent processes, so I would be inclined to it the same way here. (Because otherwise it seems as an unnecessary complication / burden.)

If we want to change this approach, we should change the descriptions accordingly and deprecate all the "related child" codes, i.e. 'subContract', 'replacementProcess', 'renewalProcess'. Furthermore, we should probably split the 'prior' code, because it is currently a "related parent" for both replacements and renewals and we want to be able to distinguish them.

(If we wanted to keep the "both parent and child" approach, we should add the missing related children codes: "Framework agreement procedure second stage", "Contracting process following a planning process", "Another attempt following an ussuccessful procedure". We should then clarify that they should be retrospectivelly pusblished for the "parent" processes. Furthermore, we should reorder the codelist so that "parent-child" pairs are always next to each other.) 

___ 

(2) I think the descriptions in the beginning should also more emphasize the two important, popular and possibly less intuitive use cases: connecting planning and contracting processes and connecting different stages of a multi-stage procedure. Furthermore, the wording of all the texts shold be more aligned. 

______ 

(3) The description of 'framework' ("Framework agreement procedure first stage") is 

> "This contracting process follows on from the related process to establish a framework. The suppliers on the framework are listed in the award section of the related process." 

Isn't "to establish a framework" incorrect? The framework is established by the related process, not the current process, so I would think it shold rather be "that established the framework", no? 

___ 

(4) https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#relatedprocess says "In OCDS each contracting process can have only one planning and tender stage." Since we have split planning and contracting processes, the first relationship is no longer true - a contracting process can now be linked to multiple planning processes. 
i) I don't think that's a problem. It can happen and being able to model it is a feature (e.g. two buyers start two planning processes and then they realize they can do one joint procuremnet and start just one contracting process). 
ii) The formulation above will be solved (by removing "planning") in https://github.com/open-contracting/standard/pull/1513. As far as I'm aware, we don't talk about a "single planning per process" anywhere else, but I did just a superficial check. 

If you're ok with this, then there shouldn't be anything left to do because of this point. 

____ 

Annex: when thinking of this, I found it helpful to mark, for quick reference, the codelist with groups (i.e. which parents and children go together) and whether a code identifies a related parent or a related child. Here it is, in case someone else also find it useful.

Group | Identifies related parent / child | Code | Title | Description
-- | -- |-- | -- | -- 
 1 | parent | framework | Framework agreement procedure first stage | This contracting process follows on from the related process to establish a framework. The suppliers on the framework are listed in the award section of the related process. 
 2 | parent | planning | Planning process | This contracting process follows on from the related planning process. 
 3 | parent | parent | Parent contract (for sub-contracts) | This contracting process might result in a sub-contract of the related process.
 4 | parent | prior | Prior process | This contracting process is the renewal or replacement of the related prior process. 
 5 | parent | unsuccessfulProcess | Unsuccessful process | This contracting process follows on from an previous unsuccessful process.
 3 | child | subContract | Sub-contract | The related process might result in a sub-contract of this contract.
 4 | child | replacementProcess | Replacement process | The related process might result in the replacement of this contract.
 4 | child |  renewalProcess | Renewal process | The related process might result in the renewal of this contract.

**Comment by jpmckinney** [comment]
1. Agreed. We should follow the "child refers to parent" approach, since new data comes in the form of a child. Updating an old parent process is just extra effort.
2. Agreed. Honestly, I think most of the codes have not been used (much). They were added for #371 1727ae40d1e62317fc69ce995412403de906fec5. Some discussion also in #375.
3. Yes, that is the meaning of the sentence, but it's worded ambiguously. Feel free to rephrase entirely.
4. 👍

**Comment by jpmckinney** [comment]
Summarizing (1) from issue description:

* [x] Deprecate "parent-to-child" codes: subContract, replacementProcess, renewalProcess
* [x] Add codes (or sub-codes) to distinguish 'prior' between replacement, renewal, and maybe also additional and repetition (see https://github.com/open-contracting/european-union-support/issues/77#issuecomment-1308980818)
* [x] Expand the description of 'prior' to cover all its sub-codes, so that it's a generic "this process follows from this other previous successful process".

We will end up with codes for:

* Relating back to planning processes (new concept in OCDS 1.2)
* Relating back to first stage of multi-stage procedures
* Relating back to an unsuccessful process
* Relating back to a successful process
* Relating to a parent contract (from a sub-contract)

I think this covers all the possible relationships, with successful having sub-codes.

**Comment by duncandewhurst** [comment]
>     * [ ]  Deprecate "parent-to-child" codes: subContract, replacementProcess, renewalProcess

Noting for future reference that there's a more detailed rationale for this decision in https://github.com/open-contracting/standard/issues/476#issuecomment-475393025

**Comment by jpmckinney** [comment]
Do we have any examples or additional content to clarify the difference between renewal/replacement and additional/repetition? I'm worried anyone outside the EU won't know the difference.

**Comment by duncandewhurst** [comment]
Looking back to https://github.com/open-contracting/standard/issues/184, the use case for 'replacement' was to link a contract to the process to re-tender it (although we've since decided to make the link in the opposite direction), i.e. the re-tendering is a competitive process. Whereas, I would expect 'renewal' to mean awarding a contract to the same supplier. Another interpretation is that both cases are a replacement, with renewal being a subset.

EU directive [2014/24/EU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02014L0024-20220101) has this to say for 'repetition':

>  5. The negotiated procedure without prior publication may be used for new works or services consisting in the repetition of similar works or services entrusted to the economic operator to which the same contracting authorities awarded an original contract, provided that such works or services are in conformity with a basic project for which the original contract was awarded pursuant to a procedure in accordance with Article 26(1). The basic project shall indicate the extent of possible additional works or services and the conditions under which they will be awarded.

So the criteria seem to be: similar works or services, same economic operator, and part of the same 'basic project', which indicated that additional works or services were a possibility. There's no definition of "basic project" in the directive.

For 'additional', in eForms, this code only applies to the procurement of works and services (not supplies/goods) under the EU defence procurement directive ([2009/81/EC](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02009L0081-20220101)). I think it relates to the following paragraphs:

> for works contracts and service contracts:
> (a)  for additional works or services not included in the project initially considered or in the original contract but which have, through unforeseen circumstances, become necessary for the performance of the works or services described therein, on condition that the award is made to the economic operator performing such works or services:
> (i) when such additional works or services cannot be technically or economically separated from the original contract without major inconvenience to the contracting authorities/entities, or
> (ii) when such works or services, although separable from the performance of the original contract, are strictly necessary for its completion.

The criteria seem to be: unforeseen circumstances, necessary for the performance of the original contract and either inseparable from the original contract or strictly necessary for its completion.

**Comment by jpmckinney** [comment]
'repetition' and 'additional' are from the [direct award justification](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/direct-award-justification) authority table, where they are (not very usefully) defined as:

> repetition: New works or services, constituting a repetition of existing works or services and ordered in accordance with the strict conditions stated in the Directive

> additional: Need for additional works or services by the original contractor

The other codes that relate to previous contracting processes are:

> existing: Partial replacement or extension of existing supplies or installations by the original supplier ordered under the strict conditions stated in the Directive

This was discussed as matching 'prior' (but in the discussion here, 'prior' now stands in for 'successfulProcess').

> irregular: Only irregular or unacceptable tenders were received in response to a previous notice. All and only those tenderers of the previous procedure which have satisfied the selection criteria, have not fulfilled the exclusion grounds and have satisfied formal requirements, were included in the negotiations

> unsuitable: No suitable tenders, requests to participate, or applications were received in response to a previous notice

These two were [discussed](https://github.com/open-contracting/european-union-support/issues/77#issuecomment-1308980818) as matching 'unsuccessfulProcess'.

----

All this said, maybe we don't care to subdivide 'prior'? EU countries can use the [Procurement method rationale classifications](https://github.com/open-contracting-extensions/ocds_procurementMethodRationaleClassifications_extension) extension to give the direct award justification, i.e. to indicate whether the justification is repetition, additional, etc. (reasons that might not translate to non-EU countries).

In that case, 'prior' can perhaps be:

> The contracting process aims to extend, renew, repeat or replace one or more contracts from the related contracting process. 

----

For 'unsuccessfulProcess', instead of:

> The contracting process is another attempt to conclude some contract(s). The related process is the contracting process that attempted and failed to conclude the contract(s) previously.

For more consistency:

> The contracting process is another attempt to conclude one or more contracts. The related process is the contracting process that attempted and failed to conclude the contracts previously.

(Sidenote: I'm remembering now that "previously" is there so that a process that is restarted 3 times refers to the previous attempt, not the first attempt. We use "failed" like in the descriptions of "unsuccessful" tenderStatus and awardStatus codes. Presumably, this code is not used if a buyer cancels a process and then decides to do it again. Otherwise, we'd have to change the language. The original text used "unsuccessfuL' as the only keyword.)

> This contracting process follows on from an previous unsuccessful process.

**Comment by duncandewhurst** [comment]
I don't find the definitions in the direct award justification authority table particularly helpful since they mostly just repeat the title of the code - that's why I looked at the directives to find additional content that describes what 'additional' and 'repetition' etc. actually mean. However, I've no idea whether those terms carry the same meaning outside of the EU so I'm happy with your proposed solution.

**Comment by jpmckinney** [comment]
Indeed - just putting it all here in one place for easy reference. Sounds good!
