### ISSUE TITLE
Keep the definition of monetary unit

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/standard#1535]
In 2015, Peru's [law 30381](https://www.bcrp.gob.pe/transparencia/datos-generales/marco-legal/ley-que-cambia-el-nombre-de-la-unidad-monetaria-de-nuevo-sol-a-sol.html) changed its currency name ("Nuevo Sol" to "Sol") and its currency symbol ("S/." to "S/"), however, ISO 4217 maintains the code "PEN" for its currency.

The team that implements the OCDS for Peru OSCE wants to keep both currency descriptions (they have historical data that use old currency descriptions).

### Proposal
I think we don't have an extension that maps this use case, we can consider a local extension for them.

[CRM-8257](https://crm.open-contracting.org/issues/8257)

cc @yolile @jpmckinney

**Comment by yolile** [comment]
You can see the older codes in the historical list of currencies:
https://www.six-group.com/en/products-services/financial-information/data-standards.html#scrollTo=maintenance-agency
![image](https://user-images.githubusercontent.com/6834122/179089787-df518c81-f702-441f-9ac6-379a0b1044f9.png)
And these codes are part of the standard code list https://standard.open-contracting.org/latest/en/schema/codelists/#currency (see the valid until column)
So they can use de ISO codes as usual.

**Comment by yolile** [comment]
Reopening as indeed the code "PEN" appears in the historical list but also as "Sol" in the current list of codes

The inclusion of "Sol" with PEN was made [here](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/dl_currency_iso_amendment_162.pdf). 

I guess they could have a local extension that adds a "`currencyName`" field in the `Value` object and document in their publication policy that since 2015 PEN stands for "Sol" and not "Nuevo Sol" anymore (although this is already documented in the ISO code list). The other option is not adding any new fields, and data users that want to show the currency name and symbol should cross reference dates and currencies with the ISO records (both historical and current lists) to show the correct currency name.

**Comment by jpmckinney** [comment]
I'm confused. What's the problem? OCDS is not responsible for the display of currency names (which change across languages and across time, like in this case). The entire point of having codes is to avoid worrying about such issues.

If Peru wants to display PEN as "Nuevo Sol" before 2015 and "Sol" after 2015, that is an application-level issue, and is not something to be addressed by the standard. If they really want it in the data, they can make a local extension.

**Comment by jpmckinney** [comment]
We can continue discussion in CRM-8257 and only re-open here if there is a clear role for the standard.

**Comment by yolile** [comment]
Agree, as the only use case that this issue affects is if they want to display the currency in an application, there are no issues for users that want to do data analysis, for example. So yes, the options are a local extension or doing anything.
