### ISSUE TITLE
Package metadata: add a reference to publisher object

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/standard#1551]
[Package metadata](https://standard.open-contracting.org/latest/en/schema/reference/?highlight=metadata#package-metadata) doesn't contain a reference to [publisher object](https://standard.open-contracting.org/latest/en/schema/reference/#publisher) so we can reference it

Some additional text to description like this:
Information to uniquely identify the publisher of this package.
See [Publisher](https://standard.open-contracting.org/latest/en/schema/reference/#publisher)

cc @jpmckinney @yolile

**Comment by jpmckinney** [comment]
The table is rendered by https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema

It adds "See ABC" links only if a `$ref` is used.

Instead, just remove `publisher` from `:collapse: releases,publisher` in `reference.md`.

Another option would have been to extract the contents of `publisher` to a new definition, so that it can be `$ref`erenced, but `publisher` is being deprecated in #1084.
