### ISSUE TITLE
Regarding OCDS launch statistics

### ISSUE THREAD

**Issue by Kenneth-Chau** [open-contracting/standard#1564]
Hello everyone, 

This is my first time posting here so if I have violate any rules please let me know. I was doing some research on the increase in Traffic when launching OCDS jsons files. Could anyone relay me some news article or statistics that related to this topic?

**Comment by jpmckinney** [comment]
Hi @Kenneth-Chau I'm not quite sure what you are looking for, can you describe at greater length?

**Comment by Kenneth-Chau** [comment]
Hello James, thanks for taking the time to respond to my question. 

About your question, I am currently researching whether implementing OCDS standards affects people interested in government procurement. I was looking for data on what happens after a government implements OCDS standards to their open datasets. From my research, I found data from the UK mentioning an increase in interest from SMEs to bid on government contracts. Still, I could not find any data related to the traffic on Open Data sets before and after OCDS implementation. Here are some examples of the data I'm looking for. (E.g., Traffic on Open Datasets before implementing OCDS vs. Traffic after Implementing OCDS, Initial week of traffic when implementing OCDS, and the traffic dropoff after implementation. Finally, traffic differences in accessing the open datasets sorted by groups. From businesses, Academics, and the general public)

If you can point me to research articles or news regarding these topics, it will be a great help. Thanks again reading through my comments and have a great day

**Comment by jpmckinney** [comment]
You will have to contact the publishers whose datasets are of interest to you. Our [Data Registry](https://data.open-contracting.org/) links to the publisher's website in each dataset's description.

Generally, we are not so concerned with dataset traffic as we are with effective use of the dataset (like the SME example). Traffic numbers depend a lot of update frequency, access method (API vs bulk), server reliability, etc. I am not sure how to control for these variables considering the relatively small sample size of OCDS publishers.

For many/most governments, their OCDS publication is their first publication of contracting data in any format. So the change will be from 0 to (some number). I don't think any publisher can sort traffic by groups, because the data is not "gated", so users do not need to identify themselves before downloading.

Anyhow, I recommend contacting Camila Salazar, Lead Data Analyst, about your research. csalazar@open-contracting.org
