### ISSUE TITLE
tender.enquiryPeriod and tender.submissionMethodDetails are inconsistent

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1579]
The description of `tender.enquiryPeriod`states that details of how to submit enquiries should be provided in `tender.submissionMethodDetails`:

> The period during which potential bidders may submit questions and requests for clarification to the buyer or the procuring entity. Details of how to submit enquiries should be provided in attached notices, or in submissionMethodDetails. Structured dates for when responses to questions will be made can be provided using tender milestones

However, the description of `tender.submissionMethodDetails` is about submission of bids, not enquiries:

> Information about the methods by which bids are submitted. This can include the address, e-mail address or online service to which bids are submitted, and any special requirements to be followed for submissions. More structured information can be provided using the submission terms extension.

**Comment by jpmckinney** [comment]
I propose to eliminate the problematic sentence from `enquiryPeriod`, since it isn't the role of one field to describe the semantics of another field.

If we want to provide details on how to submit enquiries, we can open a new issue. I think this can perhaps be answered through a worked example (without adding new fields), where one party has the role 'processContactPoint' (and the answer is to contact them via their contact details).
