### ISSUE TITLE
Rewrite examples on Identifiers page to use a common thread, remove types of identifiers section

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1595]
We can consider linking the examples on [this page](https://standard.open-contracting.org/latest/en/schema/identifiers/) together to build on one another, i.e. instead of Anytown, Mexico, and the UK, we choose one scenario/context and use it across all three.

**Comment by duncandewhurst** [comment]
I have a couple of reservations about the current structure of the examples:

* There is a lot of crossover between the [globally unique identifiers](https://standard.open-contracting.org/latest/en/schema/identifiers/#globally-unique-identifiers) worked example and the [contracting process identifier](https://standard.open-contracting.org/latest/en/schema/identifiers/#contracting-process-identifier-ocid) worked example
* `ocid` appears in the globally unique identifiers worked example before it is introduced in the contracting process identifier section.

I think it would make sense to combine those two examples so that there is only one example about globally unique contracting process identifiers and for that example to appear under the contracting process identifier heading.

Regarding the scenario/context:

* For the organization identifiers example, I suggest that we stick with the UK since it has a public register of organization identifiers. We can replace Development Initiatives with Microsoft since it is a more readily recognisable organization.
* For the contracting process identifiers example, I suggest that we replace Town A, Town B and Mexico City with two national-level publishers so that readers don't need to be familiar with subnational entities in a particular country. For consistency with the organization identifier example, one can be the UK and the object of the contracting process can be productivity software, whilst the other can be another English-speaking country, e.g. Canada.

We can also add JSON snippets to the organization identifiers example and include the `publisher` and `tender` objects to illustrate the example:

```json
{
  "ocid": "ocds-fh349f-0005",
  "publisher": {
    "name": "UK Atomic Energy Authority"
  },
  "tender": {
    "id": "0005",
    "title": "Productivity software"
  }
}
```

```json
{
  "ocid": "ocds-twb234-0005",
  "publisher": {
    "name": "Health Canada"
  },
  "tender": {
    "id": "0005",
    "title": "Office furniture"
  }
}
```

The proposed organization identifiers example, for completeness:

```json
{
  "parties": [
    {
      "identifier": {
        "scheme": "GB-COH",
        "id": "01624297",
        "legalName": "MICROSOFT LIMITED",
        "uri": "http://data.companieshouse.gov.uk/doc/company/01624297"
      } 
    }
  ]
}
```

@jpmckinney let me know if that sounds good and I'll draft the updates. Happy to use a different scenario/context if you prefer.

**Comment by duncandewhurst** [comment]
Hmm, maybe we should wait until https://github.com/open-contracting/standard/issues/1524 is done (redrafting content) before deciding on the examples.

**Comment by duncandewhurst** [comment]
> Hmm, maybe we should wait until #1524 is done (redrafting content) before deciding on the examples.

I've added the blocked label until the content is redrafted.

**Comment by jpmckinney** [comment]
This direction looks good to me.

I'm fine with eliminating "Types of identifiers" entirely, since the content comes up again in each section (it should, anyway).
