### ISSUE TITLE
Deprecate most package metadata

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1621]
While #1084 and #426 are postponed, in 1.2, we can still remove validation properties from package metadata (`required`, `uniqueItems`, etc.) and deprecate fields like `uri`, `publisher` (already at release level), `publishedDate`, `license`, `publicationPolicy`.

In other words, only `version`, `extensions` and `releases` / `records` are not deprecated.

We can also revert the `links` field from #1422.

There was also a comment in #1084 about re-organizing the content about packages: https://github.com/open-contracting/standard/issues/1084#issuecomment-1198826910

Note that when we review the documentation, we can probably also close

* #605
* #1551

**Comment by jpmckinney** [comment]
As part of this, we can remove the package schema from the extension template.

**Comment by duncandewhurst** [comment]
> While #1084 and #426 are postponed, in 1.2, we can still remove validation properties from package metadata (`required`, `uniqueItems`, etc.) and deprecate fields like `uri`, `publisher` (already at release level), `publishedDate`, `license`, `publicationPolicy`.
> 
> In other words, only `version`, `extensions` and `releases` / `records` are not deprecated.
> 
> We can also revert the `links` field from #1422.

I've made the above schema changes in https://github.com/open-contracting/standard/pull/1640

> There was also a comment in #1084 about re-organizing the content about packages: [#1084 (comment)](https://github.com/open-contracting/standard/issues/1084#issuecomment-1198826910)

The comment is about reducing the length of the Reference menu, which has the following items related to releases, records and packaging (I'm assuming that we won't touch the items from Merging onwards as part of this issue):

* Release Reference
* Release Schema
* Release Package Schema
* Record Reference
* Record Package Schema

In https://github.com/open-contracting/standard/issues/716, I proposed adding a Record Schema page, which would increase the length of the Reference menu. I still think that we should do that. To reduce the number of packaging-related items, we could put them under a Packaging item. Given that the package schemas are small, I don't think there's much value in putting the schema browser and reference documentation on separate pages so the packaging item could have two sub-pages:

* Release Reference
* Release Schema
* Record Reference
* Record Schema
* Packaging
  * Release Package Reference (Schema browser and content from the [Package Metadata](https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#package-metadata) section of the release reference)
  * Record Package Reference (Schema browser and content from the [Package metadata](https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#package-metadata) section of the record reference)

If a bulk data format is added in 1.3.0/2.0.0, those pages could then be moved under an 'API format' sub-page:

* Release Reference
* Release Schema
* Record Reference
* Record Schema
* Packaging
  * API Format
    * Release Package Reference
    * Record Package Reference
  * Bulk Data Format

@jpmckinney does that sound good?

> Note that when we review the documentation, we can probably also close
> 
> * [Improve packaging documentation #605](https://github.com/open-contracting/standard/issues/605)

@jpmckinney since the proposals in that issue predate the improved Primer and Guidance documentation, could you give an idea of which of your proposals still need to be addressed?
 
> * [Package metadata: add a reference to publisher object #1551](https://github.com/open-contracting/standard/issues/1551)

Done in https://github.com/open-contracting/standard/pull/1640 (uncollapsed `publisher` per https://github.com/open-contracting/standard/issues/1551#issuecomment-1264225461)

**Comment by jpmckinney** [comment]
> @jpmckinney does that sound good?

Sounds good!

> @jpmckinney since the proposals in that issue predate the improved Primer and Guidance documentation, could you give an idea of which of your proposals still need to be addressed?

I can't find any :)
