### ISSUE TITLE
Record reference has no jsonschema directive for the Record definition and thus no #record anchor

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1630]
The `records` field tries to link to `#record`, but there is no table to link to.

https://standard.open-contracting.org/latest/en/schema/records_reference/#record-package-schema.json,,records
https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#record-package-schema.json,,records

**Comment by duncandewhurst** [comment]
The link within https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#record-package-schema.json,,records is just to an HTML anchor so this issue could be addressed simply by changing the ['Record structure' heading](https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#record-structure) to 'Record`.

That said, it seems useful to actually have a jsonschema directive for the Record definition so, as well as changing the heading, I've added the directive too: https://standard.open-contracting.org/staging/1630-update-record-reference/en/schema/records_reference/#record

However, the schema table incorrectly reports the type of `releases` as object when it should be array:
![image](https://github.com/open-contracting/standard/assets/19265814/4ad497a2-aa7b-4793-a539-9f18af121647)

I think that's because the jsonschema directive [defaults to object when there's no `type` keyword at the top-level of a property](https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema/blob/c166a008b5d4188d08323adf6922a9f6e5a4f1df/sphinxcontrib/jsonschema.py#L227) and the `type` keyword for `releases` is nested (and repeated) under a `oneOf`:

```json
{
          "title": "Releases",
          "description": "All the releases about the contracting (or planning) process at the time of the record's publication. The releases must be sorted in date order, from oldest to newest.",
          "oneOf": [
            {
              "title": "Linked releases",
              "description": "A list of references to releases.",
              "type": "array",
              "items": {
                "$ref": "#/definitions/LinkedRelease"
              },
              "minItems": 1
            },
            {
              "title": "Embedded releases",
              "description": "A list of releases, with all the data.",
              "type": "array",
              "items": {
                "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
              },
              "minItems": 1
            }
          ]
        }
```

I tried [factoring the schema](https://json-schema.org/understanding-json-schema/reference/combining#factoring-schemas) to move the `type` keyword to the top level of the `releases` property, but that causes the `releases` row to disappear altogether:

```json
{
          "title": "Releases",
          "description": "All the releases about the contracting (or planning) process at the time of the record's publication. The releases must be sorted in date order, from oldest to newest.",
          "type": "array",
          "oneOf": [
            {
              "title": "Linked releases",
              "description": "A list of references to releases.",
              "items": {
                "$ref": "#/definitions/LinkedRelease"
              },
              "minItems": 1
            },
            {
              "title": "Embedded releases",
              "description": "A list of releases, with all the data.",
              "items": {
                "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
              },
              "minItems": 1
            }
          ]
        }
```
![image](https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema/assets/19265814/61c76691-565d-4bd0-b8f1-0a190781e332)

I've opened an [issue](https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema/issues/56) on the jsonschema directive repo.

@jpmckinney let me know your preferred course of action:

1. Fix the jsonschema directive's handling of oneOf (not sure how involved that might be)
2. Keep the schema table and live with the incorrect type
3. Remove the schema table and just update the heading

**Comment by jpmckinney** [comment]
I prefer (1) - perhaps jsonschema simply shouldn't assume an object if type is missing.

**Comment by duncandewhurst** [comment]
~~Blocked until https://github.com/OpenDataServices/sphinxcontrib-opendataservices-jsonschema/issues/56 is done~~
