### ISSUE TITLE
Indicate encoding for CSV serializations

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#166]
From Jamon on the mailing list: 

> When grabbing data from CKAN repositories, I've run into issues with CSVs and byte order markers. That and general encoding issues. I would very much like to know the encoding of a file beforehand, say, with a simple string field called 'encoding'. Said field could use any of the ISO8859-_, CP_, windows-_, KOI_ and UTF-\* encodings.
> Then for any release that contains a designated encoding, I don't need to write a parser to fiddle with and figure out BOM stuff.

**Comment by timgdavies** [comment]
@kindly Could you check what we currently say about encoding for both CSV and JSON, and perhaps work up a proposal for what we should state in future? 

I recall we recently had some issues with JSON encoding that this issue may relate to also.

**Comment by kindly** [comment]
I think we should say

**JSON**: Only support UTF-8
**CSV**:  Support UTF-8 and windows-1252

The reason for windows-1252 is that it is hard to export CSV files in any other encoding from excel.  Other spreadsheets software make UTF-8 easy or standard.

This will need to be added to docs somewhere as far as I can tell there is no guidance on this.

**Comment by timgdavies** [comment]
This issue is under consideration for the 1.1 milestone. 

## The problem

Currently the standard doesn’t specify how CSV data should be encoded. 

## Proposal

Documentation and validation tools will be updated to require either UTF-8 or windows-1252 for CSV encoding. 

## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
Related to #323 which addresses JSON encoding.

**Comment by JachymHercher** [comment]
> The reason for windows-1252 is that it is hard to export CSV files in any other encoding from excel. Other spreadsheets software make UTF-8 easy or standard.

Good point about excel and UTF-8 exports. Note though that Microsoft seems to be working on the issue, so at some point .csv could also be limited to UTF-8 only. (https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/10006149-support-saving-csv-in-utf-8-encoding)

**Comment by timgdavies** [comment]
I've staged an edit to the implementation guidance for this.

@kindly @Bjwebb What checks does the validator currently run on encoding of incoming CSV files?

**Comment by Bjwebb** [comment]
Currently the validator tries the following encodings in order: UTF-8, Windows 1252, Latin 1 https://github.com/OpenDataServices/cove/blob/95b502e1e84251e05945c96ef522a7ebfbbf1232/cove/lib/converters.py#L45
No further checks are run, so if a file is not windows-1252, but uses all the same bytes, it will be misinterpreted.

The dev cove site will warn if UTF-8 is not used (because we think that's the preferable option).
