### ISSUE TITLE
Country of benefit (relevant to contracting processes by multilateral organizations)

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1719]
Sometimes, multilateral organizations are in charge of conducting the procurement process for a country (e..g in OCDS, the procuring entity is the multilateral procurement unit), the buyer could be the donor, e.g a country, and finally, they also have the information about the "Beneficiary Country". Neither the buyer nor the procuring entity covers the beneficiary of the procurement, therefore we need another place to disclose this information. 

In https://github.com/open-contracting-extensions/public-private-partnerships/issues/235 is discussed how to disclose data about beneficiaries, and in https://github.com/open-contracting/standard/issues/1388#issuecomment-909690167 the [beneficiaries extension](https://gitlab.com/dncp-opendata/ocds_beneficiaries_extension) was created (adding beneficiaries at the item level and without a location).

Using tender.items.location could be an option but the beneficiary country information is not available at the item level (and sometimes the item information is not available at all) but at the tender level.

So another option could be to change the existing beneficiaries extension to: Add the Address object and Beneficiaries at the tender level.

cc @allakulov

**Comment by jpmckinney** [comment]
Beneficiaries in OCDS for PPPs, etc. are about, e.g., which community benefits from a new school or road. The government would not be considered the beneficiary; rather, the government acts for the benefit of residents. Whether the government achieves this benefit (like a school or road) with its own funds and procurements or via an MDB's funds and procurements – the beneficiaries will be the same (the people in that community).

Generally speaking, the donor (e.g. the particular country that contributed funds to the MDB) has no authority over the procurement. They might have attached conditions to their funds (e.g. can be used for health and education, cannot be used for defence, etc.), which might even be very specific (e.g. "for a new water treatment plant in Camelot"), but they do not fill the role of buyer:

> The organization aiming to conclude a contract with a supplier or to use the goods, services or works resulting from the contract. (OCDS 1.2)

To lay out the facts that we're trying to model, let's be more specific. Example:

The IADB loans funds to the Dominican Republic to [improve the facilities of the Port of Manzanillo](https://www.iadb.org/en/project/DR-L1141).

Scenario 1: Let's say the IADB uses the DR's e-GP. This should be modelled with DR as the buyer and/or procuring entity (following OCDS definitions, depending on how they run the procurement). The [finance extension](https://extensions.open-contracting.org/en/extensions/finance/master/) can describe the loan. Indicating which country provided the funds to the IADB would be a new need, for which we have no field. We can discuss how to model that, but it would be among the budget/finance fields. Edit: Per next message, `source` can be used for this.

Scenario 2: Let's say the IADB runs the procurement through its own system. In this scenario, we need to know more about the procurement rules / how the contracting process is governed. Let's assume the IADB is performing the procurement *on behalf of* the buyer (which would then be the DR government), which makes them a procuring entity (see a useful analysis of procuring entity roles in https://github.com/open-contracting/standard/issues/1180). We can then model the financing information the same as scenario 1.

So, the only difference between the two scenarios is that in scenario 2, the IADB is the procuring entity. That makes sense, as there is only one change between the two.

**Comment by jpmckinney** [comment]
So:

```json
{
  "buyer": {
    "id": "1",
    "name": "whatever relevant public body in the country's government, don't set buyer if unknown"
  },
  "tender": {
    "procuringEntity": {
      "id": "2",
      "name": "the MDB ONLY IF the MDB takes responsibility for running the procurement, within its own system"
    }
  },
  "planning": {
    "budget": {
      "finance": {
        "id": "1",
        "financingParty": {
          "id": "2",
          "name": "the MDB"
        },
        "financingPartyType": "multilateral",
        "source": "this field can be used for the country that contributed funds to the MDB, if not otherwise needed"
      }
    }
  }
}
```

**Comment by yolile** [comment]
Thanks, but I think there is an additional scenario to consider:

- The multilateral runs the procurement process using their systems (procuring entity)
- There is a donor that funds this, that is, the entity paying for this but is not the government
- A country receives the benefits of this project/contracts

[Here](https://data.unops.org/projects/11875-003?filters=(year~*2023)~#table) is an example from [UNOPS](https://www.unops.org/expertise/procurement/procurement-agent-services):

- Procuring Entity: UNOPS
- Donor/Buyer: Initiative for Climate Action Transparency (ICAT)
- Beneficiary country: Denmark

**Comment by jpmckinney** [comment]
> A country receives the benefits of this project/contracts

Like I said, this is not how the word "benefit" or "beneficiary" is used in procurement. For "Hotel rooms" on that page, the beneficiaries would be the people who sleep in those rooms. Beneficiaries are the target population for whom the intervention is designed. This, in general, is not an entire country.

That said, if data quality is poor, it's possible that the only thing we know about the beneficiaries is the country in which they live. In that situation, we have two options: (1) add a field specifically for this purpose, e.g. `countryOfBenefit` or (2) design a model for beneficiaries, such that we can declare their location without saying anything else about them.

The [referenced extension](https://gitlab.com/dncp-opendata/ocds_beneficiaries_extension) hasn't been reviewed for inclusion in the extension registry, and from a quick review, I suspect it will not satisfy the wide variability in beneficiary information. https://github.com/open-contracting-extensions/public-private-partnerships/issues/235 has a different model, for instance.

Unless we want to do a deep dive on beneficiary information, the best option is to add a simple field like `tender.countryofBenefit`.

----

It looks like we are modelling UNOPS data (important context to share). This is a different context, than, for example, modelling Denmark's contracting processes, some of which might be funded by UNOPS.

In this example, it matters to know what ICAT is. It turns out it is both an UNOPS project and [an organization](https://climateactiontransparency.org/governance/) ("ICAT was created as a multi-stakeholder partnership and is governed by a Donor Steering Committee together with an Advisory Committee.") It appears as both project and partner on [this page](https://data.unops.org/countries/DK?filters=(year~*2023)~#table), for example. The project has a hyphen.

I don't know how to get more detail on individual contracts, so I'll just assume that the partner is "the organization aiming to conclude a contract", i.e. the buyer. In many cases with MDBs, the partner is a government entity in a country.

The model is mostly as before. The example shared has no donor information as far as I can see. This assumes that the "amount" in the table is both the amount financed and the amount awarded.

```json
{
  "parties": [
    {
      "id": "XM-OCHA-HPC8",
      "name": "United Nations Office for Project Services",
      "roles": [
        "procuringEntity",
        "funder"
      ]
    },
    {
      "id": "1",
      "name": "ICAT Initiative for Climate Action Transparency",
      "roles": [
        "buyer"
      ]
    },
    {
      "id": "2",
      "name": "Klosterhof Hotel-Veranstaltungen GmbH",
      "roles": [
        "supplier"
      ],
      "address": {
        "countryName": "Germany"
      }
    }
  ],
  "buyer": {
    "id": "1",
    "name": "ICAT Initiative for Climate Action Transparency"
  },
  "tender": {
    "procuringEntity": {
      "id": "XM-OCHA-HPC8",
      "name": "United Nations Office for Project Services"
    }
  },
  "awards": [
    {
      "id": "UNOPS-3175505",
      "title": "Hotel rooms",
      "suppliers": {
        "id": "2",
        "name": "Klosterhof Hotel-Veranstaltungen GmbH"
      },
      "value": {
        "amount": 5000,
        "currency": "USD"
      }
    }
  ],
  "contracts": [
    {
      "id": "UNOPS-3175505"
      "awardID": "UNOPS-3175505",
      "status": "terminated"
    }
  ],
  "planning": {
    "budget": {
      "finance": {
        "id": "11875-003",
        "title": "ICAT - Initiative for Climate Action Transparency",
        "description": "Initiative for Climate Action Transparency (ICAT) integrates guidance, capacity building and knowledge sharing to engage countries in the use of a common framework to assess the impacts of their policies and actions and report progress, fostering greater transparency, effectiveness and ambition. The Initiative will improve the availability and quality of data and enable countries to promote efficient, cost-effective policies. The Initiative will also provide a platform for countries to share lessons learned and build mutual confidence in their climate actions. The United Nations Office for Project Services (UNOPS) manages the trust fund through which the Initiative is funded. This structure allows new donors to join the trust fund, to expand its work and reach.",
        "financingParty": {
          "id": "XM-OCHA-HPC8",
          "name": "United Nations Office for Project Services"
        },
        "financingPartyType": "multilateral",
        "value": {
          "amount": 5000,
          "currency": "USD"
        }
      }
    }
  }
}
```

**Comment by yolile** [comment]
Thanks, `countryOfBenefit` sounds sufficient for this case. 

Another example is [this](https://data.unops.org/projects/20519-001?filters=(year~*2023)~#table) one, where the country of benefit is Argentina, UNOPS is managing the procurement contract and one contract is financed by/the donor is the World Bank.  The modeling would be as you described and in both examples, we could use  `countryOfBenefit` to indicate the first example is for Denmark and in the second example Argentina.

**Comment by jpmckinney** [comment]
In terms of word choice, I chose "country of benefit" based on its usage like at:

* https://www.cgiar.org/dashboards/grants/ "Each grant is mapped to the country or countries of benefit and implementation. For purposes of these data visualizations, the amount per country is an average share of each country of benefit or implementation for the grant."
* https://apps.who.int/gb/ebwha/pdf_files/EB107/eeid4.pdf "The present WHO systems do not allow for a break down of all expenditure to show the country of benefit. Expenditures recorded as global and interregional include funds expended for the benefit of countries, but under global or regional management authority. Future financial systems will be developed to facilitate such analysis."

We also already have `countryOfOrigin` in another extension, so it fit the same pattern.

In the context of international aid, the term "recipient country" is often used ([like in IATI](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/recipient-country/)). However, within some MDBs, "recipient country" has a special meaning (e.g. a country can have the status of being a "recipient country" or not). Since we are not trying to model whether a country belongs to such a list, but instead are just trying to model the country in which benefits are realized (which is of wider utility, outside the context of international aid), I chose to avoid that term.

According to ChatGPT (I'm being lazy), other terms from international aid include:

* beneficiary country (similar term; from a quick web search, seems to especially be used for preferential tariffs)
* developing country (not preferred, as we want "developed" countries to be able to be where benefits are realized)
* project location (it's an okay term, but our initial intention was to describe the benefits/beneficiaries not the project; if we were to use it, we'd want to establish that beneficiaries are always at the project location)

Considering that last option, for some use cases, the country of benefit could be implied by the [delivery location](https://extensions.open-contracting.org/en/extensions/location/master/) of items (if that level of details is provided); for example, if an EU institution procures something that benefits a specific country.

I found the following to not be a good match for our desired semantics:

* destination country
* focus country
* host country
* implementation country
* partner country
* target country

**Comment by jpmckinney** [comment]
For future reference, I also checked the use of "beneficiaries" in different contexts.

For co-occurrences with "procurement", I could only find things like EU funding instruments [like this one](https://eni-cbc.eu/lr/en/calls-for-proposals/1st-call-for-proposals-closed/guidelines-for-applicants-and-beneficiaries/271) and the [OSS procurement rules](http://www.oss-online.org/sites/default/files/Beneficiaries_procurement_rules_OSS-EN.pdf), which describe recipients (which can be contracting authorities) of funding as "beneficiaries". This makes sense from the perspective of a funding program, as they are the first to "benefit" from the funding. That said, for compatibility with other contexts, I would prefer to call them the "recipients", because they "receive" the funding, but (unless there is corruption) they are not the ones who will benefit, ultimately.

In other contexts like project beneficiaries, beneficiaries of social impact bonds, etc. the meaning is always along the lines of the people affected by a problem, "the ultimate recipients of the services or interventions provided by the project or program" [[1](https://www.evalcommunity.com/career-center/beneficiaries-in-monitoring-and-evaluation/)], "people directly and indirectly affected by the project activities" [[2](https://padem.org/en/project-cycle-management/3-1-program-writing-direct-and-indirect-beneficiaries/)], etc. – which is consistent with the meaning in this discussion. Many funders refer to beneficiaries in this sense, e.g. when a funder asks a recipient to [report](https://portal365.org/en/posts/what-is-the-difference-between-targeted-groups-and-final-beneficiaries) on the beneficiaries of a funded project.

In the EU or other places with French influence, it's possible that "beneficiary" is more commonly used where we'd expect "recipient", because "bénéficiaire" is commonly used as the term for a recipient (like in this [Canadian glossary](https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32563&section=glossary)).
