### ISSUE TITLE
Add “Type” as property for "Organization"

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#181]
From #171 

Add “Type” as property for "Organization"

>  we have to state whether the supplier is a small or medium enterprise and whether it is a voluntary or community sector organisation (it could be both an SME and a VCS organization). Suspect there will be similar issues in other jurisdictions, eg minority-owned businesses in US.

**Comment by CountCulture** [comment]
I think "Type" is a bit of a misleading label -- I might read type to mean legal form, or whether it's profit/non-profit. What's being discussed here appears to be more of a classification than a type, and more than that a classification that is jurisdiction-specific (or maybe even agency/domain-specific). For example, I have a feeling the UK SME classification is subtly different from the EU (although the EU may be used in EU contexts). Also our experience in US contracting is that this is one of a number of classifications, including minority or veteran-owned, and so there perhaps needs to be 0..n such classifications. Finally these are probably classifications for the organisation at time of contract award, rather than an immutable attribute. HTH

**Comment by jpmckinney** [comment]
[W3C Registered Organization Vocabulary](https://www.w3.org/TR/vocab-regorg/) uses `orgType` to mean "SA, PLC, LLC, GmbH etc." (Aside: in terms of terminology, in OCDS we've avoided abbreviations – so it'd become `organization_type` – and we also avoid repeating the class name before the property name – so it'd then become `type`.)

I think to resolve the issue @CountCulture addresses, we can use [Classification](http://standard.open-contracting.org/latest/en/schema/reference/?highlight=classification#classification) objects with specific schemes? Thoughts?

**Comment by timgdavies** [comment]
This issue is taken forward in #369

**Comment by jpmckinney** [comment]
Closed with creation of https://github.com/open-contracting/ocds_partyDetails_scale_extension
