### ISSUE TITLE
Identifiers for UK Administrative Bodies

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#195]
The Local Government Association have provided [schema guidance](http://validator.opendata.esd.org.uk/) for all UK Local Authorities implementing the [transparency code](https://www.gov.uk/government/publications/local-government-transparency-code-2014) which includes space for an optional Open Contracting ID. 

It is desirable to create identifiers for all UK local government entities on mass / allow re-use of existing identifiers, in order to avoid each needing to apply for an identifier:

* (a) To streamline the process of people publishing;
* (b) To minimise the creation of new identifiers for UK Government Organisations - as there are concerns about a current proliferation of identifiers

The current [OCID guidance](http://ocds.open-contracting.org/standard/r/1__0__RC/en/key_concepts/identifiers/#construction) suggests a pattern of:

* A prefix agency (characters 1 - 4) - currently only ‘ocds’ (Open Contracting Data Standard)
* A '-' separator
* A registered prefix (characters 6 - 11) - a random alphanumeric string given to publishers
* A publisher namespace (characters 12 - 13) - for allow publishers to maintain separate series of local identifiers.
* A ‘-’ separator
* An internal identifier (characters 15 and above) - drawn from publishers existing systems

The best candidate for identifying UK local authorities at present appears to the ONS GSS Coding System, which provides each area of administrative geography with a 9-digit identifier. The first three characters indicate the level of geography and the six digits following define the individual unit.

To incorporate these as OCID prefixes, given the six-digit prefix patter in the current OCID approach, we could either:

* (a) Create a prefix agency for each of the Levels of Geography, and include the second part of the GSS as the registered prefix (e.g. 
* (b) Create a prefix agency for ONS GSS, and relax the rules on the length of the prefix

E.g. in **schema a**, Norfolk would be something like ```GE10-000020-``` (with the G added to the ONS GSS three-digit code), and in **scheme b** it would be something like ```ukgs-E10000020-```

## Recommendation

We should adopt **scheme b** and create a prefix agency code for ONS GSS codes. 

These codes should be used to refer to the legally responsible body for the identified geographic level and geographic areas

These codes should only be used where there is a one-to-one mapping between the legal party to the contract and the geographic area identified by the code. 

### General

* Is there a strong rationale for keeping the position-based / character limited criteria for OCIDs? 

### UK Specific

* Are the ONS GSS codes the appropriate list to use? Are there any times where they would not correspond to a related government entity, or where a government entity might have multiple GSS codes that identify it?

**Comment by akuckartz** [comment]
In any case please consider providing URLs, so that Linked Data / JSON-LD can be supported.

**Comment by practicalparticipation** [comment]
@akuckartz Can you say more about the URL approach that would be preferred?

I.e. URLs for the organisation IDs? Incorporating the URL of the organisations website?

One approach we could take would be to provide known URL patterns for each prefix agency where an identifier can be resolved, as sometimes there will be a range of possible dereferenceable URIs, such as, for .e.g. in the Norfolk case above

http://opendatacommunities.org/doc/geography/administration/cty/E10000020

and

http://statistics.data.gov.uk/id/statistical-entity/E10000020

The latter is more 'authoritative', but the former provides much more useful information.

A codelist of registration prefix agencies could list something like:

```json
"prefixes": [
  "ukgs" : {
     "url_patterns": [
"http://opendatacommunities.org/doc/geography/administration/cty/",
"http://statistics.data.gov.uk/id/statistical-entity/"
     ]
  }
]
```

to allow consuming applications to select the linking they want. 

Alternative suggestions / worked up examples of how you want linkage to work really welcome.

**Comment by AlCollier** [comment]
Tim

Thanks - I like your approach (b). It has the advantage that the registration agency can be passive - we are simply adopting an authoritative list that already exists.

In the English local government context, LGA has an ambition to get down to a single identifier per authority. We should loop Mike Thacker, their standards lead, into the conversation. I'll email him.

Regards

Al

**Comment by akuckartz** [comment]
Quick and brief answer: "URLs for the organisation IDs"

If there is a need for templates I suppose that they could/should be specified using RFC 6570 (http://www.rfc-editor.org/rfc/rfc6570.txt).

The "Norfolk case" is a very good one. Simple answer: Generally the URL which is most authoritative _and_ most persistent should be used to identify the organisation. I do not know which one I would prefer for Norfolk.

Several URLs can be declared to identify the same organisation. Such declarations do not need to be part of Open Contracting specification. I will attempt to provide more feedback on that.

Incorporating Website URLs also would be good, but that is a different matter - though both _could_ be identical.

**Comment by MikeThacker1** [comment]
For all work with the LGA and associated open data standards, we use:

- DCLG's Open Data Communities URI to identify the council organisation, eg http://opendatacommunities.org/id/county-council/norfolk

- the ONS GSS code URI to identify the area the council governs, eg :  http://statistics.data.gov.uk/id/statistical-geography/E10000020

Ideally contracting standards should use the council organisation URI because the area it governs might change over time and so it would govern an area given by a different GSS code.

That said, I don't know how often such a change would happen.  Also the Open Data Communities (ODC) URI is not ideal in that it builds in council type and name (which ideally would just be properties of a URI with a simple code).

I'll ask ODC people if they wish to chip in.

Also, does Open Contracting need its own code rather than using someone else's full URI?  Maybe it does at this stage of maturity of URIs for contracting bodies.

**Comment by akuckartz** [comment]
@MikeThacker1 asked
> does Open Contracting need its own code rather than using someone else's full URI? Maybe it does at this stage of maturity of URIs for contracting bodies.

I do not know. But I likely would not complain if Open Contracting evaluates the situation and then decides to provide (and maintain!) its own set of URLs knowing what kind of work that implies. My main concern is that URLs (or URIs) are used.

BTW: A very similar situation exists in Germany. Here also different branches of the government and the national public library organisation each maintain there own sets of URLs to identify municipalities.

**Comment by AlCollier** [comment]
I'm not sure that a URL/URI works for this use case. We need to go back to the purpose of the OCID. It provides a prefix to which the contracting authority appends its file reference to form a unique identifier for the sourcing exercise. We don't want that identifier to be too long, and more fundamentally it seems to me that we can't take a URL and append a file reference, otherwise we create an invalid URL.So to return to Norfolk, I have file references of the form NCCT99999 for my sourcing exercises. We can't take http://opendatacommunities.org/id/county-council/norfolk and append /NCCT99999 because that URL will not point to anything.

**Comment by akuckartz** [comment]
@AlCollier 
> ... it seems to me that we can't take a URL and append a file reference...

Why do you want to do that? _Can_ that file be accessed on the web?

(If that is needed then one could perhaps consider
http://opendatacommunities.org/id/county-council/norfolk#NCCT99999)

**Comment by AlCollier** [comment]
@akuckartz sorry perhaps not making myself clear.

By "file" I mean the sourcing exercise. We give the sourcing exercise an identifier - in the physical world, a "file reference". We need to combine a globally unique organisation prefix -the OCID - with a file reference that is unique within the purchasing organisation to create a globally unique identifier for the sourcing exercise.

Hence the prefix in my view shouldn't be a URL.

**Comment by akuckartz** [comment]
@AlCollier I see: You want to mint a globally unique identifier and like to use the OCID and a local identifier as components of that identifier. No problem. How about one of these:

- `https://ocds.open-contracting.org/_OCID_/_local_identifier_`
- `https://opendatacommunities.org/id/county-council/_OCID_#_local_identifier_`

Maybe the first URL can not be dereferenced: that would not be nice, but that is not a big issue.

**Comment by MikeThacker1** [comment]
My message is that it is generally a bad idea to try to put meaning into identifiers.  This applies to ODC putting the council type and name (= label) into council URIs AND it would apply to the OCID including the organisation identifier.  However, in the latter case, I can see that having the organisation means that sequential numbers can be assigned independently within each organisation.

Our work for esd.org.uk has shown that, over the last two years we believe just four councils have been assigned new GSS codes because of slight changes in the boundaries between two pairs of councils.

If you can live with that small degree of change, then use of the GSS code should work.

**Comment by akuckartz** [comment]
@MikeThacker1 :+1:

**Comment by AlCollier** [comment]
@MikeThacker1 I agree with you that embedding meaning into identifiers is not helpful. There's a case for simply assigning new, non-meaningful, identifiers to any council (or anyone else) that applies for one. That was the original plan, and I've no issue with it. The reason we're having this debate is the chorus of "not another identifier!" that went up when this was suggested.

I'm nervous about using GSS because (a) it's wrong semantically (the OCID refers to an organisation, not a geography); and (b) we might (crystal ball time) see wider organisational change in future.

If we want to go with an existing identifier to avoid proliferation I wonder whether the whole of government accounts counterparty ID might be a good candidate. We already have to use it, it's short and it refers to an organisation. Any thoughts?

regards

Al

**Comment by MikeThacker1** [comment]
@AlCollier I think you and I see things the same way.

I didn't know the government accounts counterparty ID (see https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/316759/01_2013-14_CPID_11042014_b.xls ) but it seems a good candidate if with proper quality data (accuracy, longevity, provenance, etc).

I'll try to bring more knowledgeable public sector people into this discussion.  The National Information Infrastructure (Cabinet Office paper out for review) should include proper quality identifiers for government organisations, but there is no firm plan for making that a reality.

**Comment by timgdavies** [comment]
Closing as an implementation issue for the UK likely to be handled through helpdesk, and upcoming organisation identifier work-stream of Joined Up Data Standards group (info coming soon). Can re-open if required in future.
