### ISSUE TITLE
Add Bid section to Tender

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#197]
Bidding information was not included in the 1.0 RC due to a range of different proposals. There is however demand to be able to express bidding information

Based on discussions in #78 we should provide an updated bidding schema proposal and work this up as an extension.

**Comment by timgdavies** [comment]
There is a clear proposal at http://api-docs.openprocurement.org/en/latest/standard/bid.html which we should consider, work up and test with data from Mexico City and other contexts.

(cc @myroslav  - any learning from use of your bid section we should take into account?)

**Comment by myroslav** [comment]
Our procurement process has no pre-qualification and so called self-declaration principle is employed. i.e. it is assumed that all bidders are able to provide qualification `documents` "when needed" and thus provides only significant documentation in advance i.e. specs of a product to deliver, and the `value`. After auction (so called reduction) where bid value is reduced there is clear sequence of bids to do qualification process (from lowest to highest value).

The winner (and only the one) is able to provide her extra qualification `documents`, that were omitted in earlier bidding stage. These documents appear to be the same in data structures as the ones provided in advance, but in fact they have to clearly separated, since they were provided for different bid amount (i.e. the one significantly reduced by reduction). We do that differentiation by date, since we know when auction took place, but that solution is not the most elegant one. The winner can be disqualified, and next Bid in the sequence is allowed to provide extra documentation for qualification purposes.

The other not-so-smooth part was bid `value`, since it has currency and VAT flag that should match the one of the tender. It is information duplication requiring extra validation.

There is only single element in `tenderers` array, since collective bids always have some single Organization here.

Bid `status` is not used at all, yet. We are employing Awards for the qualification process.

These are the most important elements of Bid in our procurement process.

**Comment by timgdavies** [comment]
Bidding information is also desired in Taiwan, where draft data includes a block along the lines below, capturing failed bids:

```
withoutTenderer: [
   {
     bidAmount: 1536406,
     number: 1,
     failReason: "資格、規格合於招標文件但非最低(高)標"
  },
  { 
     bidAmount: 1536406,
     number: 2,
     failReason: "資格、規格合於招標文件但非最低(高)標"
   }
]
```

**Comment by timgdavies** [comment]
I've not had time to work up a full schema here yet, but as a quick example of what a bids block could look like which would fit with the current approach in Ukraine, and potentially help model the Taiwan data, here's an example:

```json

{"bids":[
  {
    "id":"123",
    "date":"2015-12-05T13:11:59+00:00",
    "tenderers":[{ }],
    "status":"failed",
    "statusDetails":"",
    "value": {
       "amount":12356.00,
       "currency":"USD"
    },
    "documents":[]
    
  } 
  ]
}
```

In this case, the data above from Taiwan could be modelled as:

```json
{"bids":[
  {
    "id":"1",
    "status":"failed",
    "statusDetails":"資格、規格合於招標文件但非最低(高)標",
  },
{
    "id":"2",
    "status":"failed",
    "statusDetails":"資格、規格合於招標文件但非最低(高)標",
  },

  ]
}
```

**Comment by timgdavies** [comment]
Developed in #379
