### ISSUE TITLE
Publication levels documentation does not include Planning stage

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#212]
The documentation embedded [here](http://ocds.open-contracting.org/standard/r/1__0__RC/en/implementation/publication_levels/#content-what-to-include) includes basic, intermediate or advanced fields for each of the tender, award, contract and implementation stages of the contracting process, but not for planning.

We might want to say that:

* Linking back through the planning section to the project or budget that funds a contract is intermediate;
* Being able to provide forward-looking planning information (i.e. a planning release), is advanced;

but this may need input from @LindseyAM and @marcelarozo to confirm.

**Comment by marcelarozo** [comment]
Hi all,

I think that budget should be basic and project intermediate, since having a budget line to which the contract is attached is a basic requirement of best practice. Linking contracts to projects could be well placed in intermediate  The rest might be put on advanced.

Happy to hear @lindseyAM opinion.

Marcela

Sent from my iPhone

On Jul 2, 2015, at 12:54 PM, timgdavies <notifications@github.com<mailto:notifications@github.com>> wrote:


The documentation embedded here<http://ocds.open-contracting.org/standard/r/1__0__RC/en/implementation/publication_levels/#content-what-to-include> includes basic, intermediate or advanced fields for each of the tender, award, contract and implementation stages of the contracting process, but not for planning.

We might want to say that:

  *   Linking back through the planning section to the project or budget that funds a contract is intermediate;
  *   Being able to provide forward-looking planning information (i.e. a planning release), is advanced;

but this may need input from @LindseyAM<https://github.com/LindseyAM> and @marcelarozo<https://github.com/marcelarozo> to confirm.

-

**Comment by LindseyAM** [comment]
I will think about this some more but my first impression is that having a
procurement plan with the most basic elements is basic (pdf), and that
having it as structured, disaggregated data (including cost estimates)
would be intermediate, and that including the ID for the planned
procurement(s) with the actual tender release(s) would be advanced.

**Comment by marcelarozo** [comment]
Yeah that Seems right too

Sent from my iPhone

On Jul 3, 2015, at 10:36 AM, LindseyAM <notifications@github.com<mailto:notifications@github.com>> wrote:

I will think about this some more but my first impression is that having a
procurement plan with the most basic elements is basic (pdf), and that
having it as structured, disaggregated data (including cost estimates)
would be intermediate, and that including the ID for the planned
procurement(s) with the actual tender release(s) would be advanced.

On Thu, Jul 2, 2015 at 4:41 PM, marcelarozo <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Hi all,
>
> I think that budget should be basic and project intermediate, since having
> a budget line to which the contract is attached is a basic requirement of
> best practice. Linking contracts to projects could be well placed in
> intermediate The rest might be put on advanced.
>
> Happy to hear @lindseyAM opinion.
>
> Marcela
>
> Sent from my iPhone
>
> On Jul 2, 2015, at 12:54 PM, timgdavies <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
>
>
> The documentation embedded here<
> http://ocds.open-contracting.org/standard/r/1__0__RC/en/implementation/publication_levels/#content-what-to-include>
> includes basic, intermediate or advanced fields for each of the tender,
> award, contract and implementation stages of the contracting process, but
> not for planning.
>
> We might want to say that:
>
> * Linking back through the planning section to the project or budget that
> funds a contract is intermediate;
> * Being able to provide forward-looking planning information (i.e. a
> planning release), is advanced;
>
> but this may need input from @LindseyAM<https://github.com/LindseyAM> and
> @marcelarozo<https://github.com/marcelarozo> to confirm.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/open-contracting/standard/issues/212>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/open-contracting/standard/issues/212#issuecomment-118194839>
> .
>

-

**Comment by timgdavies** [comment]
This was fixed in the documentation updates earlier this year, so publication levels now cover all stages.
