### ISSUE TITLE
Add Russian National Classifications to itemClassificationScheme codelist

### ISSUE THREAD

**Issue by ElenaMinina** [open-contracting/standard#225]
There are two items classifications in Russia: the old one OKPD (ОКПД in Russian) (begins with http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=143095;fld=134;from=14052-7;rnd=0.33374630799517035) and the new one OKDP (ОКДП in Russian) (http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=163703;fld=134;from=170864-15;rnd=0.39699640963226557). They don't complitly mach each other and don't match codelists from Item Classification Scheme.

**Comment by timgdavies** [comment]
We should add these [to the itemClassificationScheme codelist](https://github.com/open-contracting/standard/blob/master/standard/schema/codelists/itemClassificationScheme.csv).

Here's a first draft of possible codelist entries, and some questions:

| Code | Title_en | Description_en | Source |
|---|---|---|--|
| OKPD | Russian National Classification of Economic Activities, Products and Services (1994) | Part of the unified system of classification ad coding of technical, economic and social information of the Russian Federation, in use for Russian Procurement information until January 1, 2016. Superseded by OKDP) | http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=143095;fld=134;from=14052-7;rnd=0.33374630799517035 |
| OKDP | Russian National Classification of Products by Economic Activity | ? | http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=163703;fld=134;from=170864-15;rnd=0.39699640963226557 |

One quick question:

* The [the link you gave for OKDP](http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=163703;fld=134;from=170864-15;rnd=0.39699640963226557) the descriptions appear to talk about 'JECFA 2' (I'm reading through Google Translate... so I may be missing something), rather than OKDP.  Where does the OKDP name come from?

And an observation (just to log it somewhere):

JECFA talks about being based on harmonisation with the [Statistical Classification of Products by Activity in the European Economic Community, 2008](http://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_NOM_DTL&StrNom=CPA_2008&StrLanguageCode=EN&IntPcKey=&StrLayoutCode=HIERARCHIC) and there seem to be some [cross-walks with other European codelists here](http://ec.europa.eu/eurostat/ramon/relations/index.cfm?TargetUrl=LST_REL&StrLanguageCode=EN&IntCurrentPage=4) although I couldn't see a cross-mapping to CPV (which is the main European codelist).

## Processes for agreeing new codelist entries

ItemClassificationScheme is an open codelist, so you can add your own codes, but ideally we should get consensus on any codes to be adopted. 

So - I think next step is to leave this issue open for discussion and feedback briefly, and then if there are no objections, to agree on starting to use these codes. 

Right now, we've not got a great system for codelist management, so I've labelled this up as codelist, and when we have better codelist management sorted we can take forward getting this into the official docs.

**Comment by ElenaMinina** [comment]
Google translate just translates OKPD 2 as JECFA 2. OKPD is based on JECFA, but has some differences because of national economic features.
In the draft the first one should be OKDP (Superseded by OKPD), and the second one - OKPD. They both are Russian Classification of products by economic activity. OKPD has been in use since February 1, 2014; coul be used in legal relations arising from 1 January 2014.

**Comment by timgdavies** [comment]
Great. Thanks :) Updated version below

| Code | Title_en | Description_en | Source |
|---|---|---|---|
| OKDP | Russian National Classification of Products by Economic Activity (1994) | Part of the unified system of classification and coding of technical, economic and social information of the Russian Federation, in use for Russian Procurement information until January 1, 2016. Superseded by OKPD | http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=143095;fld=134;from=14052-7;rnd=0.33374630799517035 |
| OKPD | Russian National Classification of Products by Economic Activity (2014) | Part of the national standardisation system of the Russian Federation and based on harmonisation with the Statistical Classification of Products by Activity in the European Economic Community, 2008. In use from January 1 2014 | http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=163703;fld=134;from=170864-15;rnd=0.39699640963226557 |

**Comment by timgdavies** [comment]
Summarised for 1.1 in #387
