### ISSUE TITLE
One framework contract with multiple tenders (sub-tender)

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#233]
In the Ukrainian procurement systems (both Zovnishtorgvydav and Prozorro?) there are [framework contracts](http://ocds.open-contracting.org/standard/r/1__0__RC/en/schema/reference/#framework-contracts) in which an additional sub-tender takes place to decide which specific participant in the framework agreement receives a specific award.

Is the best way to model this currently to add the extra tenders as separate OCDS processes? We might then want an extension describing how a "sub-tender" might reference it's parent tender?

@myroslav May have more information to add.

**Comment by Bjwebb** [comment]
Referencing another contracting process has previously been discussed for sub-contracts - https://github.com/open-contracting/standard/issues/144

**Comment by LindseyAM** [comment]
@Bjwebb @myroslav Can we break this down a little bit more?  Am I correct in understanding that we are talking about a situation in which multiple contractors have entered into framework contracts to provide a specific good or service and then a tender is conducted between them to determine who will receive a specific order?  Is it something like a preselection criteria?

**Comment by Bjwebb** [comment]
@LindseyAM I think that's correct.

**Comment by myroslav** [comment]
There are different cases, and it appears that there will be more in future.

The tender is conducted to select multiple winners who enter framework agreement with procuringEntity each. And selected winners can have either some priority to procuringEntity or some type of priority based upon subtype of product or delivery location (region of the country). Then under this framework agreements procuringEntity is placing orders, and can use "backup" providers based on the priorities defined.

Alternative approach instead of simple order is mini tender (in most cases with an auction) with participants of framework agreement. This mini tender is equivalent of simplified closed procedure (I.e. no qualification is necessary).

One of the interesting options is open framework agreement, that lets other participants to become member of, after separate qualification process that verifies the vendor.

**Comment by timgdavies** [comment]
So - under the current OCDS set-up:

## Tender > multiple winners > framework > orders
In **scenario 1** this would be modelled as **a single contracting process** (i.e. one OCID), with an award in place for each supplier, and with each order drawn down represented as a 'contract', referencing the award for the relevant supplier. 

If extra details about why a particular supplier was ordered from is needed in each case, this could be attached as an extension of the contract. 

If modelling each order as a contract is problematic, then the alternative might be to have a single award and contract pair for each supplier, and then to extend the ```transaction``` component [within implementation](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#implementation) to include the relevant information for each order. 

(For example, at a stretch, items and their delivery locations could be nested within transactions, and some transaction types introduced to indicate a commitment to pay, rather than the actual payment).

## Tender > multiple winners > framework > mini-tender

**Scenario 2** in which there is a mini-tender process would be modelled as **multiple contracting processes* as we have more than one tender (and we define contracting process as that which has a single tender). 

Here we do need a solution to the related OCID problem which @Bjwebb mentioned above (c.f. issues #72 #144) - although I've put an updated note in #72 which might help with this. 

## Open Framework

In this case, it sounds like there would be an open ended tender in a record, and new awards and contracts added as and when participants become members of the framework, with the dates of the award and contract elements indicating when they joined the framework.

**Comment by timgdavies** [comment]
Are there problems with using the approaches above?

**Comment by LindseyAM** [comment]
So, I may need to wrap my head around this a bit more but from what I understand, we have already thought about how to express the fact that in some cases a tender can result in 'award' to multiple vendors under a framework contract and then from there multiple orders can be placed (each treated as a contract).  And, the issue is that sometimes there is a competitive auction between the awardees? So could it not be attached somehow to the order notice that the reason that this order was placed was because of competition i.e lowest price or because of the defined hierarchy of priorities?

The idea for the open framework is that it would never close and result in multiple awards to multiple vendors at any point in time?  Would it not make sense to instead do some type of rolling or ongoing qualification process and then have simple direct contracts according to defined priorities and qualifications?

**Comment by timgdavies** [comment]
> "...the issue is that sometimes there is a competitive auction between the awardees?"

That is the issue for **scenario 2** which @myroslav described above. 

If we simply attach information about why the contract/order was made with a given supplier to a contract entry, then this means we don't have any structures in which to store details of how the competition took place. 

This may or may not be important.

> "The idea for the open framework is that it would never close and result in multiple awards to multiple vendors at any point in time? Would it not make sense to instead do some type of rolling or ongoing qualification process and then have simple direct contracts according to defined priorities and qualifications?"

That sounds like what I was describing. When qualified, an award is created.

When an order is made, a contract is created.

**Comment by duncandewhurst** [comment]
See also [#352](https://github.com/open-contracting/standard/issues/352) for another type of framework contract. We should also consider the types of framework contracts used by the Crown Commercial Service in the UK.

**Comment by timgdavies** [comment]
Continued in #310
