### ISSUE TITLE
Guidance: How to model awards and contract suppliers in different scenarios

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#249]
This issue is being considered for an extension in the 1.1 version of OCDS. 
## The issue

At present, we do not include a `supplier` field or array within `contract` objects, requiring instead that each contract references an award which contains the supplier information.

This was based on the idea that all `contract` should follow from, and be linked to, an `award` in which suppliers are named. However, it is creating difficulty in modelling the situation in countries where a single award is made, but then specific contracts signed with different suppliers, each with their own value ([e.g.](https://github.com/open-contracting/implementation-and-extensions/issues/7)). 
## The proposal

A proposed extension will add a `supplier` array into the `contract` object, allowing for suppliers to be specified explicitly at the contract level.

The [full proposal is here](https://github.com/open-contracting/implementation-and-extensions/tree/master/proposed_extensions/proposed_contract_supplier).

This will be included an an **optional extension** to OCDS.
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
Views on this proposal are welcome.

**Comment by myroslav** [comment]
In fact we'd included it in our contracting module already as [`suppliers` attribute of `Contract` object](http://contracting.api-docs.openprocurement.org/en/latest/standard/contract.html), as well as in [Tendering module](http://api-docs.openprocurement.org/en/latest/standard/contract.html).

**Comment by agm3dc** [comment]
If suppliers are included in an array, will there be a way to denote hierarchy? In some data sets (USA Spending, for example), sub-contractors play a key role and receive a significant amount of funding. You could justify including suppliers in the implementation phase as well, to facilitate tracking of payments to each supplier (including sub-contractors). But distinguishing between prime and sub-prime is critical.

**Comment by timgdavies** [comment]
@agm3dc At the moment this proposal would not cover distinguishing prime and sub-contractors, although in the updates to organisation handling in #368 it would be possible to tag suppliers in the overall `entities` array as a subcontractor. 

This however feels like it would be complicated for a naive application to process, as it would have to lookup the tags that applied to each of the organisations listed in the `release.contracts.suppliers` array in the `release.entities` to check if it was primary of subcontractor.

I suspect it might be better to handle subcontractors at this level with an explicit extension, perhaps with an array of `subcontractors`.

In this case we would define:
- `contracts.suppliers` - the supplier with whom the contract is signed.
- `contracts.subcontractors` - an array of entities who have been awarded subcontracts under this contract. 

`contracts.subcontractors` would most likely be an extension, if if wanted, is something we should open a new issue for.

Without any extensions it would be possible to indicate the payments to subcontractors using the payee (#372) field of transactions to provide their identifier.

**Comment by timgdavies** [comment]
@juanpane I believe the proposal here to include `contract.suppliers` as a core extension should help address the key modelling issue with Paraguay awards->contracts relationships we discussed yesterday.

**Comment by juanpane** [comment]
@timgdavies , yes, that would solve the issue

**Comment by timgdavies** [comment]
Feedback from Jachym Hercher during peer-review process, **rejecting** this change:

> I think this proposal is not consistent with the OCDS approach of putting supplier in the award section. Essentially, it means that information about suppliers can be found in two > different places depending on national legal particularities. That goes directly against the idea of a standard. 
> 
> The documentation says "However, there are some contracting processes in which a single award to multiple suppliers, results in multiple contracts, each to a single supplier. In these instances, it is important to specify suppliers at the contract level." I assume this can for instance be a framework agreement, where there could be five contracts within one procurement process. Concerning how such use cases can be met: 
> 
> - While a contract is a clear thing (the "paper" document signed by two or more parties) I'm not aware of an exact definition of what an award is. For me, it's essentially a decision by the buyer. As such, I'm not sure why a "single award" could not be modelled by OCDS as an "array of awards". In other words, in a framework agreement, whether from a legal point of view there was "one award" or "five awards", this could be still modelled as five OCDS awards, leading to five contracts. As far as I understand from the documentation, this could meet the use case without needing any change to the standard. 
> 
> - If the solution above is not sufficient, then the supplier information should be moved to the contract section. That seems to make more conceptual sense (because the information is linked to the tightly defined physical "contract"), and it is also the way proposed for the new EU forms as well as the way it is done in Ukraine. We should go right for that (which probably requires OCDS 2.0), but there should be no intermediate non-systematic solution in the meantime. That just adds confusion. 

@juanpane Thoughts on the above?

**Comment by duncandewhurst** [comment]
Noting that Belarus also have this issue, re-opening and adding to 2.0 milestone.

**Comment by duncandewhurst** [comment]
> I'm not sure why a "single award" could not be modelled by OCDS as an "array of awards".

I think the issue with this approach may be that the source systems do not have data on the breakdown of the award value by supplier and duplicating the award value across multiple awards could lead to double counting.

**Comment by jpmckinney** [comment]
My understanding from a call was that they can have suppliers on both awards and contracts (though they use `winners` in one case). The reasons are that:

1. They have two systems that don't speak to each other: one system gets up to the award decision; the other starts from the contract. They can't set an `awardID` to relate a contract to an award, which would otherwise provide a user with access to the supplier data for each contract.
2. Furthermore, while an award might go to a parent company, the individual contracts might be with its subsidiaries; for example, the parent company might promise to deliver 150 tables, through its two subsidiaries who have the capacity to provide 100 tables and 50 tables each.

In the first case, I don't know that it's OCDS' responsibility to provide an alternative for systems that lack links between stages. That's open to discussion.

For the second case, we might want a way to specify, on the contract, the parties to the contract to handle the above case.

**Comment by duncandewhurst** [comment]
> For the second case, we might want a way to specify, on the contract, the parties to the contract to handle the above case.

The [contract signatories extension](https://github.com/open-contracting-extensions/ocds_contract_signatories_extension/blob/master/README.md) was created for this purpose (in context of the PPP profile)

**Comment by jpmckinney** [comment]
Perfect.

Regarding @JachymHercher's feedback, I don't think we can pursue the second option, as there can be award decisions relating to specific suppliers that never reach the stage of signing a contract (for example, if the award was unsuccessful), for which we still want to disclose the suppliers. We wouldn't want to create a `Contract` object to disclose these suppliers, as the existence of a `Contract` object, I think, would suggest at least the existence of a draft physical contract. 

The first option is the one we presently pursue, as I agree that the distinction between "one award" or "five awards" is not a deeply meaningful one. A procuring entity might share its decisions in one notice instead of five notices (e.g. to avoid paperwork), but OCDS cares more about the process than about the number of notices involved. From that perspective, I don't see an issue with saying that there were five awards, even if there were only one notice.

**Comment by duncandewhurst** [comment]
> From that perspective, I don't see an issue with saying that there were five awards, even if there were only one notice.

Repeating my earlier comment, in case it was missed:

I think the issue with this approach may be that the source systems do not have data on the breakdown of the award value by supplier and duplicating the award value across multiple awards could lead to double counting.

**Comment by jpmckinney** [comment]
> I think the issue with this approach may be that the source systems do not have data on the breakdown of the award value by supplier and duplicating the award value across multiple awards could lead to double counting.

I'm not saying that, in every case, we should split awards by supplier. In that case, ~~and in the [Paraguay case](https://github.com/open-contracting-archive/implementation-and-extensions/issues/7) (good discussion from @juanpane there)~~, I think having one "big" award and then multiple contracts is fine, and the signatories extension can be used to disambiguate which supplier is involved in each contract.

I've renamed the issue, as it seems clear we could use guidance that works through different scenarios.

**Comment by jpmckinney** [comment]
In at least [Paraguay](https://www.contrataciones.gov.py/licitaciones/adjudicacion/340885-lp1367-18-adquisicion-seccionadores-descargadores-1/resumen-adjudicacion.html#proveedores) and Chile, the procurement systems have an identifier for an award notice disclosing many award decisions, but not an identifier for each award decision. However, the notice does provide detailed information about each award decision (e.g. supplier, items, value).

The ideal would be to mint new identifiers for each award decision, and to disclose each separately. In both systems, it seems that awards are only ever to a single supplier, so it would be possible to mint an identifier my concatenating the award notice ID with the supplier ID.

There seems to be resistance from implementers to adopt this approach. The present alternative is to wait until contracts are signed, and then use the contract signatories extension (or the contract suppliers extension…), to provide the detailed information from the award notice.

However, we don't want to have to wait until contracts are signed to disclose this information (especially given that not all awards will necessarily result in contracts).

The two approaches are:

1. Status quo. Implementers who choose not to split award notices into award decisions will simply have worse data.
2. Change the Award object to allow subdivision into award decisions. The options I've considered so far are worse than the status quo (viz. standardization, complexity, analysis). For example, if some implementers use Award as an award notice and others as an award decision, its semantics would be inconsistent. If we change the semantics so that Award is an award notice (and not an award decision as it is now), that will result in a more nested (and thus complex) structure. If we offer two options to implementers, analysis across datasets becomes more difficult.

cc @yolile

**Comment by jpmckinney** [comment]
Note: #895 has a better approach to clarifying the 'award' – moving away from the 'award decision' term, and instead focusing on the desired semantics for the Award object.

**Comment by jpmckinney** [comment]
Note: I should break up this issue into component parts, as "different scenarios" from issue title covers too much ground to be resolved in one issue.

**Comment by jpmckinney** [comment]
Some guidance has been merged as part of #974. Next step is still to break up this issue.

**Comment by jpmckinney** [comment]
The new guidance covers many of the scenarios discussed here. https://standard.open-contracting.org/1.1-dev/en/guidance/map/awards_contracts_buyers_suppliers/

If there is demand, we can always add more examples for more scenarios. There is an open issue about suppliers/signatories on contracts: https://github.com/open-contracting/ocds-extensions/issues/86
