### ISSUE TITLE
Location information

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#26]
The work of Development Gateway in Nepal has focused on the importance of geo-ocation data for contracts. Whilst not often available from suppliers right now, there are clear uses cases for wanting this at the level of:

* The locations of buyer and supplier
* The locations of items and deliverables

Is the current proposal that this would be an extension?

**Comment by timgdavies** [comment]
In the extensions folder I've added [a second proposal for the location extensions](https://github.com/open-contracting/standard/tree/master/standard/schema/extensions/proposed_location). 

The [JSON schema patch](https://github.com/open-contracting/standard/blob/master/standard/schema/extensions/proposed_location/schema_usecase_2.json) can be found here, and [a draft codelist can be found here](https://github.com/open-contracting/standard/blob/master/standard/schema/extensions/proposed_location/codelist_usecase2.csv). 

I would welcome feedback on this proposal. Things to note:

* It includes both an ```activityLocation``` and a ```deliveryAddress``` property, as per @myroslav's [comment above](https://github.com/open-contracting/standard/issues/26#issuecomment-67568480) - although I've opted for ```activityLocation``` as opposed to ```deliveryLocation``` so the location can be more general (e.g. for concessions contracts)
* ```activityLocation``` splits into ```geometry``` using GeoJSON, and ```gazetteer``` using a code from a known gazetteer
  * Either or both of these can be provided
* It doesn't capture names or URIs for individual gazetteer entries (in order to keep things simple), but does allow that the overall description could include relevant text for user interfaces, and that a URI can be given to further information on the location specified. 

I've not yet adding multi-language or mergeStrategy support to this draft schema, and still need to test with some live examples, but thought I would share a this point for any thoughts and comments.

**Comment by myroslav** [comment]
It would be great to have some examples of `gazetteer` and `activityLocation` (specifically something like point, line (road), circle, polygon) property values.

The question about `activityLocation` vs `deliveryLocation`. Can "delivery" be treated as place for service delivery? This way the same property can be used for tangible and intangible procurement items.

**Comment by timgdavies** [comment]
I'll work up some examples to share soon.

The issue with the term delivery I think comes in when we're using this to
capture concessions type contracts as well, so I was trying to future-proof
the concept.

I.e. whilst it might be natural to think of delivery covering both tangible
and non-tangible places where a service is offered, delivery doesn't work
so well for an oil exploration license.

Whereas, keeping 'deliveryAddress' as the physical place something should
be sent to, an activity location could capture:

- The geographic area where products should be delivered;
- The geographic area where a service is delivered;
- The geographic area where oil exploration activity will take place;
- The geographic area where beneficiaries of an aid activity are intended
to be;

However, the alternative to this generalising of the property name would be
to recognise a distinct 'deliveryLocation', 'licenseLocation' etc. so open
to suggestions on this.


On Tue, Mar 24, 2015 at 11:04 AM, Myroslav Opyr <notifications@github.com>
wrote:

> It would be great to have some examples of gazetteer and activityLocation
> (specifically something like point, line (road), circle, polygon) property
> values.
>
> The question about activityLocation vs deliveryLocation. Can "delivery"
> be treated as place for service delivery? This way the same property can be
> used for tangible and intangible procurement items.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-contracting/standard/issues/26#issuecomment-85452013>
> .
>



-- 


+44 (0)7834 856 303
@timdavies
http://www.timdavies.org.uk

**Comment by AlCollier** [comment]
Hi Tim delivery will often be in the sense of service delivery; an old people's home, an area for rubbish collection, etc

-----Original Message-----

**Comment by timgdavies** [comment]
Below is a quick worked example of combining a point location in Cumbria, with a set of region descriptions from the NUTs classifications. In practice, most use-cases would choose between point location and gazetteer, but we make it at least theoretically possible to mix them. 

```json

"activityLocation": {
     "description":"Scotland, North West England",
     "geometry": {
          "type":"point",
          "coordinates":[54.5, -3.25]
      },
      "gazetteer": {
          "scheme":"NUTS",
          "identifiers":["UKA","UKD"]
      },
     "uri":"http://nuts.psi.enakting.org/id/UKD/"
}
```

**Comment by myroslav** [comment]
FYI, the primary idea for `deliveryLocation` was the places that do not have postal address yet. The other possible use case is exact delivery place in cases where postal address is too general to be informative (i.e. the exact hangar in huge industrial complex). And yet another case is some road works, but geometry would probably help in that case more.

**Comment by timgdavies** [comment]
Ok - so it's sounding to me like having ```deliveryLocation``` rather than ```activityLocation``` is important for the procurement context, and can capture both tangible and intangible examples.

If later modifications to incorporate concessions need it, then they could add ```activityLocation``` separately (using same model as deliveryLocation). Does that sound reasonable?

**Comment by timgdavies** [comment]
This is now summarised in issue #250, which can be used for further discussion.
