### ISSUE TITLE
More than one contact point

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#266]
From Mexico City via @gabelula 

> There can be multiple contact points for the buyer and also for the procuring entity. The question is how they add more than one person as a contact.

Contact points are related to [organization](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#organization) objects via  ```contactPoint```, and have a one-to-one relationship with Organization right now. 

Options here might be to:

* (1) Propose turning ```contactPoint``` into an array;
* (2) Allow comma separated lists of contacts in ```contactPoint``` object;
* (3) Propose an extension property of ```additionalContactPoints``` which is an array;

Option (3) is the most backwards compatible (option (1) would need to wait for a standard upgrade, and option (2) might need that, and at least would require tools to be aware of this). 

Option (3) requires that publishers are able to distinguish a **primary contact point** from other contact points. 

@gabelula Any thoughts? Do you have examples of the Mexico data to share to understand what the different contact points are? (e.g. do they play a different role, or are they all substitutes for one another)

**Comment by jpmckinney** [comment]
I suppose `additionalContactPoints` would match `additionalIdentifiers` and `additionalClassifications`, but as far as I'm aware, there are rarely primary and secondary contact points - they are all equal. With identifiers and classifications, there's often a primary, because a particular scheme is preferred; but contact points are all the same - they have no scheme.

I prefer option 1. I like option 2 least; it's just bad modeling to use commas when arrays are available as a data structure. Option 3 only makes sense if backwards-compatibility is truly sacred and option 1 could never happen.

**Comment by kindly** [comment]
Please look at the closed ticket #291 for more discussion, but that has been closed at its the same issue as this one.

**Comment by timgdavies** [comment]
Related #275

**Comment by timgdavies** [comment]
The updated organisation handling proposal in #368 offers a way to model this by repeating an organisation block with alternative contact details - tagged for the different roles that contact point plays.
