### ISSUE TITLE
Validation API that connect to other platforms for validation

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#319]
Based on a publisher request, I'm creating this issue to track demand and use cases. Please add yours to this thread for consideration.

**Comment by Bjwebb** [comment]
We've discussed building an API for [Cove](https://github.com/OpenDataServices/cove), the software that powers the [OCDS Validator](http://standard.open-contracting.org/validator/). There's potentially two parts to this. One is a JSON REST api to get the data the validator currently returns on the HTML page https://github.com/OpenDataServices/cove/issues/320. The other would be to make Cove accessible as a Python library https://github.com/OpenDataServices/cove/issues/207.

It would be great to here more about people's use cases for these sort of APIs so that it can influence our development plans.

**Comment by mireille-raad** [comment]
in an OCDS 1.1 community call on 2017-06-21, two people showed interest especially because large files on the validator time out. 

I am adding this to the conversation in github issue to help you "track the demand"

**Comment by jpmckinney** [comment]
Tracked in CoVE instead.
