### ISSUE TITLE
Float for Item.quanity

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#329]
Sometimes there's need to purchase exact `4567.76 kg` of some substance, and these 760 grams are essential.

There is possibility to specify volume as `4567760 grams`, but gram is less common way to specify Unit in that class of Items.

Should we let `float` be specified in `Item.quantity`, or stay with `integer` and insist on conversion of units on producer and consumer sides?

**Comment by timgdavies** [comment]
The proposal to change to a float makes sense to me. Moving this into discussion for 1.1 upgrade. 

Again a quick questions for @bjwebb on whether this would be a backwards compatible change to make?

**Comment by Bjwebb** [comment]
JSON schema's equivalent of a float is `number`. From http://json-schema.org/latest/json-schema-core.html#anchor8 this is "Any JSON number. Number includes integer.", so the change would be backwards compatible.

**Comment by timgdavies** [comment]
This issue is under consideration for the 1.1 milestone. 

## The problem

item.quantity currently must be an integer, which means it’s not possible to specify a fractional amount. Fractional quantity makes sense for divisible units, e.g. kilogrammes.

## The proposal

Change item.quantity from integer to number. 

All integers are also numbers, so existing data won’t be affected.

## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by duncandewhurst** [comment]
Re-opening and adding to 1.0.3 bugfix milestone

**Comment by jpmckinney** [comment]
Fixed in #514.
