### ISSUE TITLE
OCDS Extension proposal (using JSON Merge Patch)

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#335]
Extending the standard is a very common request from publishers.  At the moment the approach is to allow extra fields in the JSON and to document these changes.  We also encourage people to generate and [propose extensions](http://standard.open-contracting.org/latest/en/schema/conformance_and_extensions/#extensions) and produce a JSON Patch of the changes.  However we have not fully formalised how these extensions should be published.

This proposal covers two areas:
1. To propose a file layout for what an extension should look like. This will normally mean a github repository for each extension.  So we have a specified way that anyone can publish an extension.
2. To propose a change from using a JSON patch to using [JSON merge patch](https://tools.ietf.org/html/rfc7386)

To help clarify what this change will look like, a new repository has been created, to try and fulfil point 1 above and to explain how point 2 will work in practice:

[Proposed extension template](https://github.com/open-contracting/standard_extension_template)

Any particular improvements to the extension file layout should be added as issues or pull requests to that repository.

As to point 2, moving to JSON merge patch.  That change can be discussed in this issue in more detail. Here are the main advantages and disadvantages to the change.

Advantages:
-  Much clearer patches that can be easily read by people who understand JSON Schema
-  Can tell more easily what extension is doing by just looking at the patch
-  Larger patches are easier to read and less verbose when modifying to same parts of the JSON schema.
-  Less concepts to learn, no need to also understand json-patch format. Merging objects already part of how relesases/records work.
- Simple way to express how to extend the schema by just using the same filename in the extension.

Disadvantages:
- No way to extend lists (have to overwrite whole list).  In JSON Schema this applies to only enum field types and oneOf allOf, someOf declarations.
- JSON patch is more mature
- Tooling is not as good as JSON patch at the moment.

**Comment by timgdavies** [comment]
Having discussed this with @kindly I'm in favour of the shift to JSON Merge Patch and the new extension structure.

I will have a go at porting an existing extension to this new structure shortly.

**Comment by LindseyAM** [comment]
This is great. At what point would we update documentation to better guide users?

**Comment by timgdavies** [comment]
We should highlight this early in the upgrade process. If there is consensus, we would adopt this model for 1.1-dev, and then it would be formally adopted in 1.1.

**Comment by robredpath** [comment]
@kindly would it make sense to make this part of 1.0.2?

**Comment by timgdavies** [comment]
In preparation for OCDS 1.1 we are updating our extension handling approach to use a new template for extensions, and distinguish 'standard' and 'local' extensions.

### Updated extension template

As discussed above, version 1.1 of OCDS will use:
- a new file layout for what an extension should look like. The [template is provided here](https://github.com/open-contracting/standard_extension_template). 
- a change from using a JSON patch to using JSON merge patch for extensions

And as discussed in #326, we will introduce a property to release and record packages for:
- `extensions` providing an array of full URL paths to the extension.json meta-data of extensions used.

### Updated documentation: standard and local extensions

(Draft of new documentation for the [extension pages of the documentation](http://standard.open-contracting.org/latest/en/extensions/) - to be applied in version 1.1)

The core OCDS schema provides a set of sections, building blocks and fields for describing a wide range of different contracting processes. 

Data publishers or users may have additional data that they could publish, or that they need. Instead of ignoring this data and leaving it unpublished, OCDS encourages publishers and users to collaborate on the creation of extensions to the standard.

This can result in two kinds of extension:
- **Core extensions** provide new sections, building blocks and/or fields that are likely to have widespread utility. A standard extension is likely to be useful in many different countries and contexts. 
- **Community extensions** document the fields used by a single publisher, application or locality. For example, a local extension may describe how to provide information required by a particular national level system, but where such an extension is unlikely to be useful in other countries or contexts. 

Both kinds of extension provide documentation and schema that can be used to produce and validate extended OCDS data. 

Standard extensions may be formally embedded within the OCDS reference documentation, highlighting to data publishers and users the optional extensions that are available. Each version of the documentation will be pinned to a particular version of a standard extension.

Links to externally hosted local extensions may be included in the OCDS reference documentation, drawing on the [extensions registry](https://github.com/open-contracting/extension_registry). 

### Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
Just flagging up https://github.com/json-schema-org/json-schema-spec/issues/15 where there was discussion of a $merge keyword for JSON schema. 

It's not being taken forward into JSON Schema v0.5 - but I thought it could be worth skimming just in case anything relevant for us here.
