### ISSUE TITLE
Develop a self-service OCID prefix generator

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#339]
A simple web based tool to generate OCID prefixes to replace the current OCID prefix request process via the helpdesk.

The tool should also capture name, organization and contact details for the publisher.

Some publishers have also requested the ability to link OCID prefixes for national and sub-national publishers from the same country.

**Comment by jpmckinney** [comment]
This has come up as a governance issue, regarding concerns that OCP can act as an authority, deciding who gets a prefix or not.

**Comment by robredpath** [comment]
Concerns that we talked about: 
- Some people don't want OCIDs to be public, especially if they're very early in their implementation
- We've always found this a complex problem to solve
- We do want to capture OCIDs and details as people register
- MVP may be an autogenerated OCID and an email to us to contact them and see if they're ready to be registered

**Comment by jpmckinney** [comment]
By 'OCID' I assume you mean 'OCID prefix'.

Can we expand a bit on what we've found complex? e.g. if we would want publishers to come back when they are ready for their prefix to become public, they would need a way to authenticate themselves. (That doesn't necessarily imply logins; if they use a government domain as their email address, we can use that in a sort of email-based transaction, in which we send them an email with a link to complete the transaction or creating a prefix or making it public.)

**Comment by robredpath** [comment]
My understanding is that the story broadly goes like this:
- We want people to be able to generate their own OCID prefixes, as this is a largely mechanical task carried out by helpdesk, and some people are using their own prefixes
- We maintain a public register of known prefixes, but we always ask people's permission before adding them to this list because we don't want to accidentally reveal an implementation that's not ready for public attention yet. 
- Therefore, we have to decide whether we don't store them at all (and rely on people informing us and risking collisions), store them on a different list (which relies on people storing the prefix / risking generating several before going live) or storing them in a way that people can come back to them (which involves auth of some sort)
- If we don't store them, how do we know who's considering publishing? If we don't want to publish them immediately, how do we know when it's ok to publish them? 
- If we're doing all of this manual work in any case, what's the benefit of a self-registration tool? 

@Bjwebb @kindly did I miss anything?

**Comment by jpmckinney** [comment]
Good summary of the issues.

In terms of benefit, a concern was raised around governance and control: that one entity, however altruistic at present, could decide at a later date to withhold issuing a prefix or not recognize a self-generated prefix (creating a 6-character alphanumeric string is easy, but that's different from having it recognized by an issuer). A self-service tool would somewhat remove the role of "issuer" or limit its power. The self-service tool, once developed, could theoretically be managed by an independent entity to more fully protect against coercive behaviour by a malicious issuer. In terms of recognition, we presently have a [registration process](http://standard.open-contracting.org/latest/en/implementation/registration/#registration) that is effectively about recognizing prefixes.

I agree we want the following features for our prefix system (whether operated by humans or computers or both):

1. Generate prefixes
1. Issue prefixes
1. Store prefixes (to avoid collisions and to track adoption – though the latter is not mandatory)
1. Allow for the requester's details to remain private (question as to whether we make the whole record private including the prefix, or just the requester's details)
1. Allow for the requester's details to become public
1. View all public prefixes (I don't see why we can't publish just the prefix while a requester's details remain private, i.e. all prefixes are public)

I'm not sure what the requirements are for the register. Is it necessary to disclose the requester's organization, date, etc.? If it's only required to disclose the prefix itself, then step 5 is not required, making step 4 easy to implement in an app/form (store the requester's details when they make the initial request, then manually update it if necessary). If so:

* Screen 1 (Issuance): form with fields for Organization name, Contact person name, Contact person email, Requester email.
* Screen 2 (Success): congrats, here's your prefix.
* Screen 3 (Register): simple list of all prefixes.

We could have an optional, manual process to allow the requester to make their details public, but I don't think the publicity of a requester's details is a governance/control issue – only the issuance of prefixes is an issue.

Separately, where do we currently store people's prefixes before they're made public? I only know the spreadsheet where there's a private second tab in which we have private email addresses, but otherwise all the rows end up on the first public tab.

**Comment by jpmckinney** [comment]
Also, separately, where do we document the operation of the current Google Form? I think we can do my proposal by having a public Google Form, which populates a spreadsheet, in which we can set a cell in a "Disclose requester's details?" column to "Yes", and then have a separate sheet that publishes all the prefixes, and then only publishes requester's details if that column is "Yes".

Who the owner of that Google Form and spreadsheet is (and who has access to perform maintenance) can be determined at a later date, but we will have at least implemented the product.

**Comment by julijahansen** [comment]
Just noting down some potential issues we could encounter by making the ocid prefix registration open to all publishers:
- How do we handle multiple prefixes being registered for the same publisher (this could happen if e.g. several different people from the same organization use the tool to generate a prefix)
- For cases with multiple prefixes registered for one publisher, how do we select one to remain active and flag others as "inactive"; need to also flag this to the publisher
- How do we ensure consistency across organization names - e.g. if there are a few ways to record an organization name (e.g. one with an abbreviation at the end and one without), this might have to be deduped manually 
 - How are we notified of form submissions

**Comment by jpmckinney** [comment]
I recovered the old Google Form and made some edits, just to see how it will look: https://docs.google.com/forms/d/e/1FAIpQLSctgQIglxuaqhL0XyzUAbb6sospnWqnLR-WPTdejcXuAloMkQ/viewform

I haven't edited the logic of the Prefixes spreadsheet to conform to my earlier proposal, as I want to check if we think the Google Form makes sense, now that we have something to look at.

**Comment by jpmckinney** [comment]
Hmm, I'm not sure the auto-generation of prefixes worked in the [old Google Form](https://docs.google.com/forms/d/e/1FAIpQLSes_YppziIST72LSaTcCswr7ojBqE3ohFlwtx64280DRwdnCA/viewform). I upgraded to the new Google Forms, but the following didn't work. I think it's only possible to pre-populate fields through the URL, not through App Scripts, but we don't want people sharing the same URL with the same prefix pre-populated.

```
function makePrefix () {
    var prefix = "",
        characters = "abcdefghijklmnopqrstuvwxyz0123456789";

    for (var i = 0; i < 6; i++) {
        prefix += characters.charAt(Math.floor(Math.random() * characters.length));
    }

    return prefix;
}

function doGet (e) {
  var form = FormApp.openById("1fsQbayCNk0EgpR5IFmWblFabU-OI6uvxFHAm29rzIl8"),
      item = form.getItemById(1992482572),
      formResponse = form.createResponse(),
      itemResponse = item.asTextItem().createResponse(makePrefix());

  formResponse.withItemResponse(itemResponse);
}
```

**Comment by jpmckinney** [comment]
Closing as this hasn't come up as an issue except in one meeting in the last year. In terms of governance concerns, there are ways to assure that OCP will provide a prefix to anyone who asks. Creating a self-service option runs the risk of people accidentally creating multiple spurious prefixes, which then creates an issue of how to un-register a prefix.
