### ISSUE TITLE
Reviewing terminology of 'procurement', 'tender' and 'process' for future-proofing standard

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#358]
## Upgrade proposal

In version 1.1 of OCDS we should look at where the word 'process' can be used in place of 'procurement' without losing the meaning of fields.
## Original issue: Clarify the use of the term 'procurement'

The term 'procurement' is widely used in the documentation, most commonly as a synonym for tender. 

We should review this:

(a) To ensure we are using terms consistently and clearly;

(b) To assess where the language should be adapted to support application of OCDS to non-procurement contexts.

**Comment by robredpath** [comment]
With the PPP work coming up, this becomes more important. I'll take a look at this as I think it'll do me good to dive into the docs a bit more.

**Comment by mireille-raad** [comment]
Let me know if there are extracts of text from the documentation that you want the team here to review. Team has excellent writers and procurement background and I am sure they will be happy to chip-in.

**Comment by chrisalexsmith** [comment]
The Charted Institute of Purchasing and Supply (CIPS) defines procurement as follows:

Procurement describes all those processes concerned with developing and implementing strategies to manage an organisation’s spend portfolio in such a way as to contribute to the organisation’s overall goals and to maximise the value released and/or minimise the total cost of ownership.  Procurement is a more comprehensive term than purchasing, which is more focused on the tactical acquisition of goods and services and the execution of plans rather than the development of strategies.

Procurement can be a department, a role and/or a process.  As a process, procurement begins with the review of the spend portfolio and the development of an opportunity analysis.  Once categories are defined, the procurement process involves identifying and engaging with potential stakeholders, defining business needs and preparing a business case.  Once the market has been reviewed, a reconciliation of the business need and the supply market character ensures that appropriate procurement strategies are developed.  Strategies may involve insourcing, outsourcing, competitive bidding, direct negotiation, and a variety of other sourcing strategies.  Once the strategy is developed, the execution will involve market engagement and the issue of the RFI and the RFP and/or negotiation.  Once offers are evaluated, the optimum solution will be selected and the appropriate contractual agreement established.

Procurement differs from sourcing in that the procurement process addresses all pre-contract and post-contract processes.  Supplier relationship management, performance management and supplier development are key procurement activities to realise the potential value created during the sourcing phase.

Procurement as a full-time role is a specialised job requiring a range of skills and capabilities.  Traditional analytical capability is helpful to undertake spend analysis and evaluate offers, but the ability to understand and interact with supply markets is just as important.  In terms of interpersonal skills, influencing skills and facilitation skills are just as important as negotiation skills.

As an organisation, procurement structures vary with the culture and structure of the host organisation.  Many organisations have a centre-led structure with a small central team setting policy and standards and coordinating activity, which is primarily undertaken in the spending departments. While there are no universally accepted standards, most people agree that vendor management applies to post-award processes (though some vendor managers do manage the end-to-end process apart from market engagement).  Similarly, sourcing involves all those processes up to the award of the contract.

In Europe and Asia, the term ‘purchasing’ is used to describe transactional processes such as raising purchase orders and reconciling invoices. However, in North America the term ‘purchasing’ is sometimes used to describe the whole procurement process. The procurement process in North America usually begins with the review of an organisation’s spend portfolio, and the development of appropriate strategies, and proceeds right the way through to the review of procurement arrangements and the disposal of goods at the end of their life.

Some category managers are not full-time procurement staff but functional practitioners who also undertake business planning for that discipline. For example, a company counsel may be the category manager for legal services, but also plan the size and shape of the organisation’s legal services.  Police officers with special responsibility for firearms may be the category manager for weapons.  In such cases, category management will not only comprise the application of the procurement process to a specific category, but may include elements of business planning as well.  See also Category Management and Purchasing.
https://www.cips.org/knowledge/procurement-glossary

**Comment by timgdavies** [comment]
Thanks @chriscrownagents for this: really useful.

I've reviewed all the references to 'Procurement' in the current schema and documentation, and have found that they:

(a) Appear consistent with the definitions above;

and 

(b) Are mostly used intentionally in relation to fields like `procurementMethod`

or

(c) Are used as a synonym for 'process' (e.g. 'Specify the aware criteria for the procurement')

So: I don't see any changes needed in 1.0.2 release.

But - I think in 1.1 we could replace 'procurement' with 'process' in a number of cases in order to make it easier to re-use fields in extractives OCDS extensions etc. without redefining the field.

@dc-coder I'll certainly take you up on the offer of a review of the 1.1 text from procurement experts when that text is ready.

**Comment by timgdavies** [comment]
We will plan a complete review of standard documentation and text in the next major version update. For now, no further action on this issue is planned.

**Comment by jpmckinney** [comment]
As no such plan is documented (as far as I'm aware), I'll re-open and put in the 2.0 milestone.

**Comment by jpmckinney** [comment]
I believe this overlaps with planned work to apply the OCDS Glossary to the documentation and schema, and adjust language where appropriate. Closing as there is no specific change to resolve here.

**Comment by jpmckinney** [comment]
Related: #866 #440
