### ISSUE TITLE
Competitive bidding thresholds

### ISSUE THREAD

**Issue by agm3dc** [open-contracting/standard#393]
In many polities, procuring entities are required to use competitive bidding methods when the tender cost is above a certain threshold. Conversely, direct or sole-source procurement may only be used when the tender cost is below this threshold. In Vietnam, for example, competitive bidding is required for the purchase of goods over US$100,000 or services over US$200,000. For construction, the threshold is US$250,000.

These rules can only be bypassed under specific circumstances (natural disasters, when technological compatibility requires, etc.).

Including a threshold for competitive bidding would be valuable to efforts aimed at detecting corruption risk. There are numerous red flags related to this issue, such as:
- Awards below the competitive bid threshold followed by change orders that exceed such limits
- Splitting purchases to avoid procurement thresholds

Curious to hear other thoughts on this issue.

**Comment by jpmckinney** [comment]
Apologies for the lack of response.

Such thresholds exist outside the scope of a given contracting process; therefore, they are not a good candidate for inclusion in an OCDS release, especially given that the thresholds are stable over long periods of time. My recommendation, for the computation of red flags, would be to configure the software measuring the red flag indicators with the thresholds appropriate to the jurisdiction being analyzed, rather than to expect all OCDS releases to redundantly include this information.
