### ISSUE TITLE
itemClassificationScheme: Add 'CUCOP' code

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#405]
Used in Mexico. See https://sites.google.com/site/cnetcucop/

**Comment by jpmckinney** [comment]
@yolile At https://sites.google.com/site/cnetcucop/, I read:

> Es un clasificador el cual ordena, categoriza y dispone por clases las adquisiciones, arrendamientos, servicios, obras públicas y los servicios relacionados con las mismas

Is this a sufficient description of the classification scheme?

> The Single Classifier of Public Procurement (Clasificador Único de las Contrataciones Públicas) is a national scheme in Mexico for the classification of goods, works, services, leases and acquisitions.

**Update**: These [slides]() use:

> Es un clasificador el cual ordena, categoriza y dispone para las clases de adquisiciones de bienes, arrendamientos, servicios, obras públicas y los servicios relacionados con las mismas

Which clarifies that it is about the acquisition of goods, leases, services, etc. I've updated to:

> The Single Classifier of Public Procurement (Clasificador Único de las Contrataciones Públicas) is a national scheme in Mexico for the classification of goods, works, services and leases.

**Comment by jpmckinney** [comment]
There's a broader question for this codelist whether it makes sense for OCDS to curate a global list of national schemes, or if it should be the responsibility of the jurisdiction to coordinate which code to commonly use to refer to the same classification scheme. Our current approach is to add national schemes when requested, but to otherwise not go out of our way to catalog all schemes.

I would tend toward putting the responsibility on each jurisdiction.

cc @duncandewhurst

**Comment by duncandewhurst** [comment]
I agree that curating a global list of national schemes seems like too much - at least at the moment, where multiple OCDS implementations in a single jurisdiction aren't that common.

I'm happy with the current approach, it involves little effort from the helpdesk and gives a better chance of common codes than entirely leaving it up to individual jurisdictions to coordinate.

**Comment by jpmckinney** [comment]
Let's carry on with the current approach for 1.1.4.
