### ISSUE TITLE
Articulating cross-references in the schema

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#414]
We have a number of points now where our schema requires cross-references.

E.g. 

* contract.awardID should point to a valid award.id
* award.suppliers[].id should point to an entries in parties[].id

Looking at the discussions around JSON Schema v0.5 there are proposals for a $data validation keyword at https://github.com/json-schema-org/json-schema-spec/issues/51 

We should check on the status of this issue, and whether there is emerging consensus that it might be supported in JSON Schema in future before looking at whether we should include our own keywords for articulating cross-references in the schema.

(Note: we might only ever be able to warn on some references when validating releases, such as contract.awardID -> award.id - as I think it is valid for a release to just include the contract without the award, whilst the record would include both together)

**Comment by jpmckinney** [comment]
I don't believe it is yet possible in JSON Schema to express such relationships. Rather than extend the meta-schema (as done for codelists, which was justified as they are a central concept), I figure it best to perform these sorts of 'coherence' checks through a data quality tool. Closing as that wouldn't be a standardization issue.
