### ISSUE TITLE
Guidance on emptying fields and values page: 404

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#424]
The [merging](http://standard.open-contracting.org/latest/en/schema/merging/) page links to [guidance on emptying fields and values](http://standard.open-contracting.org/schema/reference.html#emptying-fields-and-values) which 404s.

**Comment by timgdavies** [comment]
I've got this fixed in the 1.1-dev branch, and have also pushed a correction 1.0.2.

@bjwebb How easy for us to deploy the correction to the latest branch? (Guessing it might also need a quick transifex run and tweak in the translations too?)

**Comment by Bjwebb** [comment]
Not entirely sure what's happening with the 1.0.2 branch. Previously in dev stuff happened on the 1.0-dev branch, and then a pull request made onto the 1.0 branch.

Yes, this will need running through transifex. Should be possible to make this live this week.

**Comment by Bjwebb** [comment]
I think 1.0.2 branch should probably stay at the 1__0__2 tag now that exists. Any non schema fixes for 1.0 should go on the 1.0-dev branch, and then be merged into 1.0.

I've reset 1.0.2, and cherry picked your commit onto 1.0-dev, and I've created a pull request for putting 1.0-dev live https://github.com/open-contracting/standard/pull/427

This issue has been closed because 1.0-dev is set as the default branch, and the commit is now on that branch.
