### ISSUE TITLE
Capturing the statutory relationship between notifiers and publishers

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#428]
In England, certain public bodies **must** notify Contracts Finder about opportunities and awarded opportunities. The publisher in this case is Contracts Finder/Crown Commercial Service (CCS). 

Are there any examples of the relationship between a statutory notifier and a publisher? How is this captured in structured data? Are there any examples from current adopters of OCDS?

Current OCDS practice:

- Notifying body can be the **Buyer** or **Procuring Entity** (the relationship of notifier is not explicit)
- Publishing body is the **Publisher**

**Comment by mireille-raad** [comment]
> Are there any examples of the relationship between a statutory notifier and a publisher?


In a more traditional setting, a "notification" about opportunities or awards has to be done in the official government newspaper or in newspapers in general  (there is usually a minimum number of newspapers in which an ad has to be published)
Sometimes, this depends on the value of the contract.

I believe this is to fight corruption and to increase value for money and competition. Since those are main use cases of Open Contracting, it might be interesting to do an extension or maybe some modeling (if it doesn't exist already). I am not sure tho that this is captured in existing information systems that manage procurement.

**Comment by jpmckinney** [comment]
I am not clear on the use case for identifying the notifier as-such. In all legislation I've seen, the notifier is *defined* as the buyer / procuring entity who has the obligation to notify, so there's no difference. Closing as no use case / use case already served by existing fields.
