### ISSUE TITLE
Clarify the scope of uniqueness of Release ID

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#455]
In OCDS 1.0 & 1.1 we define ```release.id``` as:

> "An identifier for this particular release of information. A release identifier must be unique within the scope of it’s related contracting process (defined by a common ocid), and unique within any release package it appears in. A release identifier must not contain the # character." 

However:

(a) This is conceptually subtle and difficult to communicate;
(b) As we see people starting to aggregate data from multiple sources, this creates a challenge, as an aggregator of information might end up with releases from multiple sources, which have distinct ```ocid``` values, but the same ```release.id```. Strictly then, the re-publisher would have to manipulate the release ids if it wanted to present both in the same package.

This leads to a suggestion from @edugomez that we should just make ```release.id``` globally unique. 

This would be simply enough for people to implement, using their OCDS prefix, and OCID. 

It would likely be a 2.0 issue.

**Comment by jpmckinney** [comment]
I'm not sure why the description includes "A release identifier must be … unique within any release package it appears in". `ocid` should always be used together with `id` to form a unique key.

I think the simpler solution is to relax the description and remove ", and unique within any release package it appears in" (unless I'm missing a clear rationale). This would be backwards-compatible.

**Comment by mpostelnicu** [comment]
*Moved to #834*

yes, in addition to what @jpmckinney mentioned,  i think we need to remember about `records` and `compiledReleases`, too. 

When the standard was initially developed, i remember the release was designed as an atomic modification message of a larger entity, similar to a `git diff` over a larger file. Many of us publish releases directly , with package information. 

But probably what should be published, aggregated and analyzed would be `records`/`compiledReleases` , and that's where we need a better handling of IDs. Even then, maybe the ID of a compiled release could be constructed adding `ocid` to say the compiled release creation datetime, or a random hash. i am not entirely sure that for the same contract, two compiled releases done at a different time and having different content, would have to have the same id or not...

We found this very early, we have imported ~1.5m releases from Ukraine's ProZorro open data page, into a local mongo database, so everything they published, and we found many releases with same ocid, same title and slightly different data, like one release was missing a tenderer , but next one had them all, etc... This was because they were describing the same process , in chunks, and they seemed complete, so the last release had the most up to date info (but i think the standard also allows for incremental releases). So, to avoid double counting, we kept only the most recent one for each `ocid` , based on `release.date`. 

But this problem may be a common issue that publishers closely following the standard may stumble upon, and i think it is normal we will find more and more cases such as these, again showing the fact we may have advise the use of `compiledReleases` in some of these cases, where the standard is strictly followed.

**Comment by jpmckinney** [comment]
*Moved to #834*

Thanks, @mpostelnicu – we should add more guidance about the identification of compiled releases.

For context, `release-schema.json` has `"omitWhenMerged": true` for `id` and `date`, which means that the compiled release will not retain these fields from the releases on which it is based.

The compiled release is essentially the "present state of the contracting process". However, as you note, this "present state" can be published at multiple times, such that you can have many compiled releases for the same contracting process. Without `id` or `date` fields, it's more difficult to distinguish compiled releases, or to establish their sequence (since a record must always include at least one release, a user could look up the latest date among those releases, but this is a greater effort). We might therefore consider introducing a date field on the compiled release, whose semantics would be the time at which it was updated.

**Comment by jpmckinney** [comment]
*Moved to #834*

Since the compiled release reuses the release schema, `id` is required – though with #330 this requirement might be removed for the compiled release. In the meantime, I think it makes sense to set the `id` to the `<ocid>-<date>`, where the date is the last release's date, and to set the `date` similarly.

**Comment by jpmckinney** [comment]
I've created a new issue for the dating and identification of compiled/versioned releases, to avoid overloading this issue: #834
