### ISSUE TITLE
Add call to action in the Validator example errors column

### ISSUE THREAD

**Issue by juanpane** [open-contracting/standard#458]
When there are errors in the validation, the error count column shows the errors for the row.
However, the number does not look like a link.
Perhaps a call to action is needed or format the number to look like a link

Example:  http://standard.open-contracting.org/validator/data/f7d35e4c-d3c8-4a3b-887c-539ceff7a491

**Comment by robredpath** [comment]
It's styled in the same way as all of the other links on the page, but it's useful to hear that you feel it doesn't look like a link. I can totally understand why - the number is on its own so it doesn't stand out compared to surround text (because there isn't any), and on my machine the cursor pretty much obscures the underline on hover. 

As for a solution - any ideas? @kindly @Bjwebb @edugomez @juanpane @yolile @juanpane emanuelzh ?

My first thought is that we could add some text to each row - perhaps "(see all)"?

**Comment by edugomez** [comment]
I think @juanpane is right, it doesn't stand out as a link on the page 

> My first thought is that we could add some text to each row - perhaps "(see all)"?

'see all' text may be the solution @robredpath

**Comment by yolile** [comment]
Yes, maybe the "see all" could work, or maybe we can add an icon like this next to the number: 
![open_in_new_window](https://cloud.githubusercontent.com/assets/6834122/26400987/a8c53096-4051-11e7-8c83-addd87548c2b.png)

**Comment by robredpath** [comment]
As this actually relates to the validator, I've copied it over to the CoVE repo.
