### ISSUE TITLE
Definition of the budget/amount in OCDS

### ISSUE THREAD

**Issue by juanpane** [open-contracting/standard#460]
The current definition of the [Budget](http://standard.open-contracting.org/latest/en/schema/reference/#budget) amount in OCDS 1.0 is:
> amount  : The value of the budget line item

It seems that this definition is open for interpretation as to whether this can mean the total amount of the budget line, not only the amount of money of the total budget amount that has been reserved/estimated for this particular contracting process.

This might need clarification.

**Comment by practicalparticipation** [comment]
To give a worked example, if a budget line-item is for £10,000, and £5,000 is allocated to a particular contracting process, our current definition is unclear as to whether the  ```budget/amount``` for a given contracting process should be £10,000 or £5,000.

OCDS 1.1 also has the same ambiguity, with budget defined as:

> The value of the budget line item. A negative value indicates anticipated income to the budget as a result of this contracting process, rather than expenditure.

However, based on discussions in Manchester, we think this should be:

> The value reserved in the budget for this contracting process. A negative value indicates anticipated income to the budget as a result of this contracting process, rather than expenditure.

This could be further extended to state:

> The value reserved in the budget for this contracting process. A negative value indicates anticipated income to the budget as a result of this contracting process, rather than expenditure. Where the budget is drawn from multiple sources, the budget breakdown extensions can be used.

This change would mean that:

* Any use of ```budget``` to represent the total line-item value would be incorrect;
* Any publishers wishing to provide the total line-item value would either need to (a) publish this in separate fiscal data package (or similar) data, or, to propose an extension to OCDS

We need to identify if anyone has been using ```budget/amount``` to mean **total** budget line, rather than amount reserved for a given contracting process, as this may have an impact on 
 whether this can be a bug fix, decimal or integer change.

**Comment by timgdavies** [comment]
Note that the same issue exists for the [Budget Breakdown extension](https://github.com/open-contracting/ocds_budget_breakdown_extension/blob/master/release-schema.json)
