### ISSUE TITLE
Typo in Spanish Codelist

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#466]
In http://standard.open-contracting.org/latest/es/schema/codelists/#release-tag

The title of **tenderAmendment** says "Enmienta" and should be "Enmienda" and the description, "enterga" should be "entrega"
And in the description of **tenderUpdate** "enterga" should be "entrega" and  "etiqueda" should "etiqueta".

**Comment by timgdavies** [comment]
This was on 1.0.2 - I've updated the translations and pushed the fix which [should be being built now](https://travis-ci.org/open-contracting/standard/builds/243309940). 

Will double check with @bjwebb whether I also need to get this merged into 1.0 in order for the fix to display at http://standard.open-contracting.org/1.0/es/schema/codelists/

**Comment by Bjwebb** [comment]
The 1.0.2 branch shouldn't be altered, it should match the 1__0__2 tag. We've had a bunch of changes on 1.0-dev and 1.0 since then.

Updates for 1.0 should be made on the 1.0-dev https://github.com/open-contracting/standard/commit/574d35a5a2de8a1169fd66f748b2e49228b42568, and then PR'd onto the 1.0 branch https://github.com/open-contracting/standard/pull/477. There's an additional deploy step after merge. The instructions for this come from https://github.com/open-contracting/standard/blob/1.1-dev/DEPLOYMENT.md

**Comment by Bjwebb** [comment]
This should now be fixed - http://standard.open-contracting.org/1.0/es/schema/codelists/#release-tag
