### ISSUE TITLE
milestoneType codelist documentation & validation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#471]
There is a discrepancy in the codes between

1. the milestoneType codelist in the schema; and

2. the milestoneType codelist [in the docs](http://standard.open-contracting.org/latest/en/schema/codelists/#milestone-type) and the [milestoneType csv](https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/codelists/milestoneType.csv).

Also, the [OCDS validator](http://standard.open-contracting.org/validator/data/a874705a-2e06-4562-a826-64521beda6d0) appears to treat milestoneType as a closed codelist, however according to the schema and the docs this is an open codelist.

![image](https://user-images.githubusercontent.com/19265814/27137417-d1ffceba-5115-11e7-9d03-9c85892291c3.png)

![image](https://user-images.githubusercontent.com/19265814/27137439-de7b52b8-5115-11e7-9096-91e4140d64d0.png)

**Comment by timgdavies** [comment]
This looks like a bug to me, down to us introducing the "codelist" links, but not being consistent in where we are then using enums.

I would suggest we add this to a 1.1.1 bug-fix ASAP which would:

* Add enums for all closed codelists - updated via a script based off the .csv files;
* Remove enums for any open codelists;

This proposal might have impacts for our validator, so would need views from @edugomez @Bjwebb or @kindly before we make the change.

The alternative would be a quick removal of that enum list entirely now - but leaving wider issues till later.

**Comment by duncandewhurst** [comment]
@timgdavies could you confirm which is the correct codelist? I'm assuming it's the one in the schema with ```preProcurement``` rather than ```planning``` but I wasn't sure whether Jachym's peer review feedback had resulted in any changes

**Comment by timgdavies** [comment]
Ah - @duncandewhurst you are correct - [it should be preProcurement](https://github.com/open-contracting/standard/issues/373#issuecomment-264467790) rather than planning. 

Ok. That will definitely need to be on a bug fix release as we'll need to update the codelist csv and docs. 

So, two bugs here:

* planning -> preProcurement (and replacing word 'planning' in the description accordingly also)
* removing enum so that this doesn't get flagged as a closed codelist by the validator

**Comment by duncandewhurst** [comment]
@timgdavies should the other codes in the schema also be added to the csv?

* approval
* assessment (in place of adjudication)
* financing

**Comment by timgdavies** [comment]
@duncandewhurst In https://github.com/open-contracting/standard/compare/471-milestone-type I've staged changes that:

* change planning to procurement, and add approval, assessment and financing to reflect the enum list;
* remove the enum list;

As this is an open codelist, we're not breaking any published data - but if any publishers have already mapped to 'planning' rather than 'preProcurement' they would get a warning from the validator about this in future.

**Comment by jpmckinney** [comment]
> Add enums for all closed codelists - updated via a script based off the .csv files

Was it decided not to do this? Otherwise may want to open a new issue. I don't see enums for at least `method` and `procurementCategory`.

**Comment by timgdavies** [comment]
This is issue #475  - If you had time to look at a script solution most welcome. Otherwise I'll be working on a manual version for 1.1.1 on Monday
