### ISSUE TITLE
relatedProcess: Add 'tender' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#476]
From discussion in #371  

In the UK one of the notice types published on the Contracts Finder platform is an early engagement notice, used for inviting feedback from industry on early procurement ideas.

Early engagement notices may not result in a subsequent notice, or may lead to one or more opportunity (tender) notices or future opportunity (planning) notices.

Due to the one-to-many relationship between early engagement and subsequent notices, they are modelled as separate processes in OCDS, using the [relatedProcess block](http://standard.open-contracting.org/latest/en/schema/reference/#relatedprocess) to link them.

As such a new code is required in the [relatedProcess codelist](http://standard.open-contracting.org/latest/en/schema/codelists/#related-process) to link **from** the early engagement notice **to** the resulting contracting processes:

code | title | description
------|-----|------------
tender|Tender process|This contracting process resulted in the related tender process

This would be used as follows:

```json
"ocid": "ocds-123456-AAAA",
"tag": "planningUpdate",
"title": "Early engagement notice: Public transport solutions",
"relatedProcesses": [
   {
       "id":"1",
    "title":"Tender for the purchase of electric buses",
    "relationship":"tender",
    "scheme":"ocid",
    "ocid":"ocds-123456-BBBB",
    "uri":"http://example.open-contracting.org/records/ocds-123456-BBBB"
   },
   {
       "id":"2",
    "title":"Tender for the maintenance of electric buses",
    "relationship":"tender",
    "scheme":"ocid",
    "identifier":"ocds-123456-CCCC",
    "uri":"http://example.open-contracting.org/records/ocds-123456-CCCC"
   }
]
```

**Comment by jpmckinney** [comment]
Note to double-check that code description covers use case from #730.

**Comment by jpmckinney** [comment]
It seems much more likely and natural for a resulting process to refer *back* to its prior process, rather than for the prior process to be updated whenever a new process results. #730 was opened to be able to have pairs of codes for each side of the relation. While I understand that it's useful to easily get a list of subsequent processes, there are many similar use cases we don't support, because the administrative burden of updating old data is too high. There's also the issue that this creates a new opportunity for incoherent data, e.g. a prior notice says it generated a subsequent notice, but that subsequent notice refers back to a different prior notice. It's generally better to model only the side of the relation that fits the most use cases. While it's true that a system could update the data about old processes when new processes are created as described in https://github.com/open-contracting/standard/issues/371#issuecomment-288191986, this seems like a usability feature that belongs at the application level, not at the data level. (In the specific case of replacement contracts #184, there might be a strong enough use case to model both sides.)

Regarding this issue, my understanding is that Contracts Finder Early Engagement Notices are used for pre-market engagement. EU Prior Information Notices can also be used to do that ([example])(https://client.tussell.com/notices/307934-bae09aa122e6d221169bac1ee5f3ed65-speciality-cyber-security-testing-services). As such, I would consider an Early Engagement Notice as simply a planning notice, which can lead to tender notices, or further planning notices.

To refer back to a planning notice, there is already a 'planning' code. As I don't see a strong reason to add a corresponding code for the reverse relationship, I'll close this issue until one is contributed.
