### ISSUE TITLE
IATI-OCDS linkages (linking aid projects and contracts) (proposal from IATI)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#478]
Over in the [IATI Discuss forum](https://discuss.iatistandard.org/t/adding-links-to-related-ocds-contracts/918) there is a proposal on creating the link between aid projects and contracts. 

There is a blog post with further background and a linked working paper on this topic at: http://www.aidtransparency.net/news/blog-linking-aid-and-contracting

Members of the OCDS community with an interest in making contracting<->aid linkages in their data are encouraged to contribute to the IATI issue.

**Comment by mireille-raad** [comment]
one thought: instead of editing codelists or fields... would it make sense to add to the  “release package schema” a reference to a joined OCDS-IATI data uri?

```json
"joined-data" : {
	"IATI" : "http://somethingsomething.com/iati-OCID-prefix.json",
	"another-standard" : "http://somethingelse.com/another-standard-OCID-prefix.json",
	"not—even-a-standard" : "http://somethingelse.com/not-even-a-standard-OCID-prefix.json"
}
```

The string “IATI” + “OCID prefix of the publisher” will ensure that this url is unique in the world.

Then on that uri… you can build a json that links OCDS and IATI, it can include documents, projects, any type of identifier you want, it would be something like:

```json
{
	"IATI - OCDS": {
		"IATI-id": "iati-432-13u1",
		"OCDS": {
			"OCID": ["ocds-929-13uu", "ocds-12-13ae"]
		}
	}
}
```
you can add things like a link to the IATI schema or documentation etc. you'll need to add in which format the data is (value from a codelist) etc... this is just to illustrate a basic idea

(I am assuming that IATI has a unique ID that is built into a unique URI or something that you can use to pull all the data using the ID) 

In the release package you referenced the extensions… i don’t think IATI data is fit as an extension because it is not exactly extending the data standard… it is more for linking data.

 
In the proposed solution in the paper, editing codelists and adding fields and agreeing what extra fields to use is a headache for data modelers... as for implementers, you have to "edit" existing data to link IATI and OCDS... you have to make sure the project ID in procurement matches the project Id of the donor and matches IATI Data... for users of data, you have to navigate or browse all data across multiple years to find aid data.

Having this is in an extension like format adds flexibility and might lower the conflicts by publishing things in a more modular way. (or if you want to say relational, which is what linking datasets is about)

It also addresses the last level in the OCDS 5-star publication system: by providing data users with links to additional data, this makes it easier to link data.

**Comment by timgdavies** [comment]
Thanks @dc-coder - I think I follow the suggestion. We should explore opportunities to try this with real IATI and OCDS data. Do you think there might be some examples from the World Bank we could try with?

**Comment by mireille-raad** [comment]
Here are some public links to start with (let me know how useful) - from data.worldbank.org

### API or CSV download 

Portfolio (or the aid projects)
http://data.worldbank.org/data-catalog/projects-portfolio

Procurement Notices
http://data.worldbank.org/data-catalog/procurement-notices

Contract Awards
http://data.worldbank.org/data-catalog/contract-awards

### No API or bulk download available

Project Documents
http://documents.worldbank.org/curated/en/home (no public API, but I can fetch a sample using intranet if you give me a list of project IDs)

Tell me how useful this is. I think i know the guy who worked on open aid data. I will ask him. (but won't be before early Sept till I am back to DC)

on the internet, I know http://www.aidflows.org - which somehow never works.

Again, let me know how useful and if you have specific questions or data gaps... this was just result of a quick look around.

**Comment by mireille-raad** [comment]
More links from http://data.worldbank.org/data-catalog

### API and CSV 
Corporate Procurement Contract Awards
http://data.worldbank.org/data-catalog/a3d9-f9xv

World Bank Program Budget
http://data.worldbank.org/data-catalog/gprm-cvxz

Paid In Contributions to IBRD/IDA/IFC Trust Funds based on FY of Receipt (this could count as a form of aid)
http://data.worldbank.org/data-catalog/nh5z-5qch

IBRD Statement of Loans - Latest Available Snapshot (might have some interesting data fields for you to compare with trust funds)
http://data.worldbank.org/data-catalog/sfv5-tf7p

MIGA portfolio
http://data.worldbank.org/data-catalog/miga-projects

I hope this gives you some insights on what data or meta data about projects there is for slightly different types of aid projects....

**Comment by mireille-raad** [comment]
btw, maybe devgateway can help....

they already built http://aiddata.org and have an API http://aiddata.org/api-aid

**Comment by jpmckinney** [comment]
A clear issue hasn't been expressed here, which means it can stay open forever. It seems some work has been pursued elsewhere (e.g. in links above). I expect there will be follow-up from those proposals. We can re-open this issue (or open new issues) if there is a clear issue to resolve.
