### ISSUE TITLE
milestoneDocuments extension in both core and community extensions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#489]
The milestoneDocuments extension appears in both the [list of core extensions and the list of community extensions](http://standard.open-contracting.org/latest/en/extensions/#using-extensions).

The [entry](https://github.com/open-contracting/extension_registry/blob/master/milestone_documents/entry.json) in the extension registry shows that milestoneDocuments should be a community extension.

We should remove milestoneDocuments from the list of core extensions in the 1.1.1 bugfix release.

@Bjwebb @edugomez not sure who is best to look at this one

**Comment by timgdavies** [comment]
Just checked against the OCDS 1.1 consultation, and we didn't say either way whether the milestone documents should be a core or community extension.

I realise we need to update the milestone extension so that it unsets the deprecation.

**Comment by Bjwebb** [comment]
This is because the list of core extensions comes from the v1.1 branch, where milestoneDocuments is marked as core - https://github.com/open-contracting/extension_registry/blob/v1.1/milestone_documents/extension.json
Whereas the list of community extensions comes from the master branch, where it isn't http://standard.open-contracting.org/latest/en/extensions/#using-extensions

There exists an issue about this discrepancy - https://github.com/open-contracting/extension_registry/issues/46. This was waiting for us to port some changes back to 1.1, but I think @kindly was saying we want to avoid doing that.

**Comment by Bjwebb** [comment]
Pull request to make milestone_documents consistently core: https://github.com/open-contracting/extension_registry/pull/48

**Comment by duncandewhurst** [comment]
milestone_documents is still displaying in both core and community in [1.1.1-dev](http://standard.open-contracting.org/1.1.1-dev/en/extensions/)

**Comment by timgdavies** [comment]
Might need @bjwebb or @edugomez to take a glance here.

In the master branch of the extension registry here https://github.com/open-contracting/extension_registry/blob/master/milestone_documents/entry.json I see ```"core": true```

but in the deployed javascript at http://standard.open-contracting.org/extension_registry/master/extensions.js I see ```"core": false```

And I see [the build was successfully run](https://travis-ci.org/open-contracting/extension_registry) when I merged in the changes yesterday.

**Comment by Bjwebb** [comment]
This should be fixed now.

Looks like I broke it whilst setting up the OCDS PPP profile deploy.
