### ISSUE TITLE
Features (as a means of expressing structured assessment criteria)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#499]
The [requirements extension](https://github.com/open-contracting/ocds_requirements_extension/blob/master/README.md) covers **eligibility criteria** for procurement processes. 

This does not, as we had initially thought, cover structured **assessment criteria** for a procurement process. 

For this we still need to work up a structured extension based on the Open Procurement API concept of a [Feature](http://api-docs.openprocurement.org/en/latest/standard/feature.html). 

This provides an array of ```Feature``` objects within ```tender.features``` each specifying a feature of an 'item', 'tenderer' or 'lot'.

The feature can specify the valid responses in an enum list, with each assigned a weight, as described in the [Open Procurement MEAT (Most Economically Advantageous Tender guidance)](http://api-docs.openprocurement.org/en/latest/meat.html#most-economically-advantageous-tenders-meat)

**Comment by jpmckinney** [comment]
In an effort to focus on extensions that have significant interest and support, I am closing this issue, due to lack of participation and lack of evidence outside ProZorro. We, of course, welcome extensions contributed by others for inclusion in the [registry](https://github.com/open-contracting/extension_registry). FYI, @myroslav

**Comment by jpmckinney** [comment]
See this draft extension: https://github.com/open-contracting-extensions/ocds_awardCriteria_extension
