### ISSUE TITLE
currency: Incorrect code for Zambian currency

### ISSUE THREAD

**Issue by julijahansen** [open-contracting/standard#554]
We list ZMK as the code for Zambian currency in http://standard.open-contracting.org/latest/en/schema/codelists/ , however the code listed under ISO4217 is ZMW: https://www.currency-iso.org/en/home/tables/table-a1.html

**Comment by jpmckinney** [comment]
We should have a script to generate / validate this codelist.

**Comment by Bjwebb** [comment]
First attempt at a script in https://github.com/open-contracting/standard/commit/f5488f36dce1507806faecd1b357d47bf6202530

This withdrawn codes (that might be needed for historic data), and a new column for the withdrawn date.

There's a problem with duplicate codes, because the upstream lists currencies per country, and some currencies were withdrawn in different countries on different dates.

**Comment by Bjwebb** [comment]
I've now fixed the duplicates, see https://github.com/open-contracting/standard/pull/607/files
