### ISSUE TITLE
partyRole: Add 'interestedParty' code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#557]
From @dwasyl:

> `interestedParty` is a perfect format of what I’m looking for with the register concept. I see where it would be useful in the P3 (public private partnerships) add-on, although I would suggest that it is a decent code to bump up to the main schema since it could easily apply to any tendering process or separate out on it's own. For me it could be linked to the question/answer data model as well.

This code exists in the PPP profile with the following definition:

> A party which has expressed an interest in the project, for example by purchasing tender documents or submitted clarification questions, but has not yet formally submitted a bid.

**Comment by mireille-raad** [comment]
would it make sense to call it something more specific like interestedBidder ? an interestedParty can be anyone like an NGO, a bank, a news media outlet, a developer poking around with open data. I didn't get what it really meant until I read the email....so an open data users can get confused with what it means to be an interested party.

**Comment by duncandewhurst** [comment]
> an interestedParty can be anyone like an NGO, a bank, a news media outlet, a developer poking around with open data

These are all valid uses of the code

`interestedParty` was added to the PPP profile to represent the different types of organization which had purchased bidding documents.

In the pilot PPP we worked with, it wasn't possible to know whether an organization which purchased bidding documents was interested in submitting a bid, or just interested in the process and wanted to submit questions, until they submitted a bid (or the deadline for submissions passed).

Once an `interestedParty` submits a bid they become a `tenderer`, in which case `interestedBidder` is redundant.

**Comment by dwasyl** [comment]
I'd concur with @duncandewhurst. Interest parties in a tender process can be anyone, no one knows who will actually submit a bid until bidding is closed.

Some with the enquiries addon, anyone can ask question, since a proponent hasn't necessarily decided if they will bid or not.

Often the `interestedParty` list would be used to send updates/addendums for the tender.

**Comment by mireille-raad** [comment]
ha! thanks for clarification :D makes much more sense now :)

**Comment by jpmckinney** [comment]
> A party which has expressed an interest in the project, for example by purchasing tender documents or submitting clarification questions, but has not yet formally submitted a bid.

@duncandewhurst Should this not refer to 'contracting process' rather than project? I propose:

> A party that has expressed an interest in the contracting process: for example, by purchasing tender documents or submitting clarification questions.

Regarding whether they have submitted a bid or not: If an interested party becomes a tenderer, the old definition would mean that they can't be an interested party, which is contradictory, because a tenderer is clearly interested. I therefore simply remove that clause here.

**Comment by duncandewhurst** [comment]
Happy with your proposal, the description is taken from the PPP profile, hence the use of 'project', but 'contracting process' should be applicable there too.
