### ISSUE TITLE
Codelists with multiple selected values

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#572]
I have a general question about the OCDS modeling approach (and one that I'm asking myself also for the future EU standard). 

Lists can be modeled in two ways: series of binary fields (a=1, b=0, c=1) or a codelist (x={a,c}). I think that in general, codelists are better because they make the standard shorter.  However, when a codelist can have multiple values, I think it's better to model it as a series of binary fields. (As long as two other more mundane conditions are also met: the list is not very long - i.e. it's not CPV, NUTS, etc.; it is a closed list.)  

I think this is better because of reuse. When reusing the data, people filter, count, tabulate, something like that. Whatever the use, if there is a codelist with multiple values, it will need to be split into individual binary variables. In some tools, this might be easy, in others, it might actually require searching for substrings ("B") in a string ("A,D,E,B,F,C") which is quite a bother. Since everyone needs to convert it back to a list of binary variables anyway, isn't it better to have it that way right away? 

Currently, this question is a bit theoretical because OCDS does not seem to have any closed codelists with multiple values allowed. However, for example, if [PartyRole](http://standard.open-contracting.org/latest/en/schema/codelists/#party-role) in the future becomes a closed codelist, for me that would be a clear candidate to model as a list of binary variables.

What are your thoughts?

**Comment by jpmckinney** [comment]
Let's take the `role` field as an example, and pretend the codelist is closed.

It's easier to add codes to a codelist than to add a field to an object in software implementations. 

If `role` is a single field that is an array of codes, then software can simply read and report the values of the `role` field. If the software loaded the data in `partyRole.csv`, then it can also report the code's title and description. If a new code is added and the new `partyRole.csv` isn't loaded, the software can still at least report the code.

On the other hand, if `role` is multiple boolean fields, the software will need to know which `Party` fields represent the possible `role` values. If a new code is added, the software will misreport the party's roles, because it is unaware of the new field for representing the new code. We don't have a mechanism available for telling software which boolean fields represent `role` values.

So, binary fields are only preferable in a world in which a specification is defined once and then all implementations are made afterwards. But that's not the world of OCDS.

**Comment by jpmckinney** [comment]
In terms of the difficulty or hassle of, e.g. testing whether a party is a buyer, the more likely test is set inclusion (e.g. is 'buyer' in the set of `role` values?), rather than substring searching or explicit comparisons. It's possibly more of a hassle to have to know, in advance, which boolean fields represent the `role` values and to iterate through them, just to get the list of roles.

**Comment by JachymHercher** [comment]
> So, binary fields are only preferable in a world in which a specification is defined once and then all implementations are made afterwards. But that's not the world of OCDS.

> It's easier to add codes to a codelist than to add a field to an object in software implementations.

Fair points. This is a relevant difference between the EU standard and the OCDS. On the other hand, the EU standard wants to become more flexible while, I'm guessing, OCDS wants to become more stable, so perhaps they'll eventually meet mid-way - and thus could have the same approach.  

Concerning software & titles & descriptions, I'm not sure I understand. In the schema, there are titles and descriptions associated with the `roles` field and I'm assuming that there are titles and descriptions associated with its codes in `partyRole.csv`. What I was asking about was having fields called `buyer`, `procuringEntity`, etc. instead of just one called `roles`. In either case, won't the fields be associated with their titles and descriptions in the same way? 

(I'm not sure there is a need to conceptually link `buyer` and `procuringEntity` in any way. However, if there was, this could be achieved by having them in a sub-section called `roles`, no? )

Concerning hassle, I guess it depends on the target audience. I'm thinking of people using Excel, SQL, Stata (i.e. economists and the like, myself included). For those I think it's a hassle. I'm guessing you're thinking of more programming-literate users?

**Comment by jpmckinney** [comment]
If we have a subsection like:

```
"roles": {
  "buyer": true,
  "procuringEntity": false,
  "supplier": false,
  "tenderer": false,
  "funder": false,
  "enquirer": false,
  "payer": false,
  "payee": false,
  "reviewBody": false
}
```

It's not clear to me that this is unambiguously better than:

```
"roles": ["buyer"]
```

For people using tabular data formats (Excel, SQL, etc.), there will need to be a transformation from the JSON to the tabular format; Excel, SQL, etc. cannot use JSON directly. So, I'm not clear on the advantage of structuring the JSON in a way that looks more 'tabular' (e.g. having lots of binary fields most of which are false) since there will need to be a transformation from JSON anyway.

Perhaps the best solution is to discuss what sorts of tabular transformations are most useful to users of Excel, SQL, Stata, etc. rather than trying to change the JSON format.

**Comment by JachymHercher** [comment]
You're right - this is better addressed with the right transformation to tabular data rather than trying to deal with it in the JSON (for the OCDS) or XML (for the EU standard). 

(There's still a bit of truth in the fact that if people independently develop parsers for conversion into CSV, relational databases, etc., - which is our case in the EU - then the structure of the schema will influence the structure of the tabular data. For example, I'm willing to bet that if the first option in your message above was used, all tabular data would have binary variables. If the second one is used, then half of the solutions will be publishing their CSV open data exactly the way they found it in the XML. But yes, the technically sensible solution is not dealing with this in the schema.)

**Comment by jpmckinney** [comment]
This has been a good discussion. I'm not clear that any action is required, so closing, but I'm happy to re-open if there is more to follow-up on.
