### ISSUE TITLE
Docson: Documentation's clarity on [1..] and null 

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#573]
I've been looking at the top of the [Release schema](http://standard.open-contracting.org/latest/en/schema/release/) documentation and some things don't seem 100% clear. @jpmckinney explained them, but I'm opening this issue so that they can perhaps be  explained more clearly. I'm not a developer, so I might be missing things which are obvious. 

1. What does `string [1..]` mean? Is it "Array of one or more strings?" or "Strings with a length of 1 or more"? (I thought it was the former, now I know it's the latter. Is it really useful to highlight that strings must have more than one character?)
2. Why is `array[1..] enum string` not `array[1..] enum string[1..]` or `array[1..] string[enum]`? 
3. What is the difference between `constant string` and `enum string`? Aren't both just values from a codelist? 
4. Why are some `enum` followed by elements from the codelist in violet (e.g. `tag`, `status`) and others are not (e.g. `roles`, `awardCriteria`)?
5. Why isn't `string [1..]` and similar used also for nested properties (e.g. `name`, `id`)?
5. Does `string, null` mean that the field is a string and it is not required? (The latter part is not true, but that would be my first interpretation.)

**Comment by jpmckinney** [comment]
We can take a similar approach to #498 to improve the clarity of the schema viewer.

**Comment by jpmckinney** [comment]
The Docson representation is intended to be a user-friendly way to explore the schema. It is not intended as a reference for all validation properties; the correct reference for those is the schema itself. I've therefore edited Docson as follows:

1. Removed `[1...]` annotations. These only appear in the case of required fields, and are only present to guard against fields being set to empty strings, empty arrays, etc. Most users would assume that data will not be empty, so this is an implementation detail.
1. Changed to "array of strings chosen from:"
1. Changed "constant" "array of strings chosen from:". ("constant" only appeared in the case that an enum had a single value, which currently only occurs in `initiationType`.)
1. We could update Docson to display the codes of open codelists, but this will require fetching 19 CSVs (which will be slow), or building a fast alternative (which is too much effort).
    * To answer the question: If the codelist is closed, then an `enum` validation property can be used (and displayed). If it is open, then we can only link to a codelist.
1. Fixed by (1).
    * To answer the question: In OCDS 1.1, optional fields don't have minimum lengths, and some required fields accidentally don't have minimum lengths.
1. Removed `null` annotations. `string null` means that the field can be set to null in order to remove it during the [merge routine](https://standard.open-contracting.org/latest/en/schema/merging/). This isn't relevant for browsing the schema.
