### ISSUE TITLE
documentType: Add 'priorInformationNotice' code

### ISSUE THREAD

**Issue by julijahansen** [open-contracting/standard#619]
We got a request to add 'priorInformationNotice' to the open ```documentType``` codelist, as prior information notice is one of the most common forms in procurement process.

**Comment by timgdavies** [comment]
Sounds good - can you check around for a possible definition we could use against the codelist entry? 

This would need to be part of a 1.2 upgrade I think.

**Comment by jpmckinney** [comment]
[GPA](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm) has "**notice of intended procurement** means a notice published by a procuring entity inviting interested suppliers to submit a request for participation, a tender, or both;"

**Comment by jpmckinney** [comment]
[EU](http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0024&from=EN) has no explicit definition as such, "Contracting authorities may make known their intentions of planned procurements through the publication of a prior information notice."

**Comment by jpmckinney** [comment]
So, I suppose we can decide between 'priorInformationNotice' and 'IntendedProcurementNotice'.

**Comment by duncandewhurst** [comment]
In the UK, CCS call the EU prior information notice a 'future opportunity notice'.

Though `intendedProcurementNotice` seems the clearer code for the procurement context, being less generic it might not be appropriate for the use of OCDS to represent other types of contracting process.

Therefore I would favour adding `priorInformationNotice` and including the other possible names in either the code description or the glossary.

**Comment by jpmckinney** [comment]
Sounds good to me.

**Comment by duncandewhurst** [comment]
Since there isn't an explicit definition for `priorInformationNotice` and it since it would be good to keep the definition general for use outside of the procurement domain I have staged the code using the GPA definition amended as follows:

> A notice published by a ~~procuring~~ *contracting* entity inviting interested ~~suppliers~~ *parties* to submit a request for participation, a tender, or both

For the time being I've omitted the 'category' field, do we have a view on whether providing a PIN would be considered basic, intermediate or advanced?

**Comment by duncandewhurst** [comment]
Since there isn't an explicit definition for `priorInformationNotice` and it since it would be good to keep the definition general for use outside of the procurement domain I have staged the code using the GPA definition amended as follows:

> A notice published by a ~~procuring~~ *contracting* entity inviting interested ~~suppliers~~ *parties* to submit a request for participation, a tender, or both

For the time being I've omitted the 'category' field, do we have a view on whether providing a PIN would be considered basic, intermediate or advanced?

**Comment by jpmckinney** [comment]
Do we have examples of PINs in non-procurement contexts to inform the definition? "a request for participation, a tender, or both" is still fairly procurement oriented.

The typical neutral term is, I think, 'contracting authority' rather than 'contracting entity'. I think we use 'bid' instead of 'tender' to avoid ambiguity between 'call or tender' and 'submitted tender'.

I'm not clear on the use cases for analyzing prior information notices across contracting domains, so I'm not opposed to having a procurement-exclusive definition, in which case we can use `intendedProcurementNotice` to avoid confusion with potential prior information notices outside the procurement domain.

**Comment by duncandewhurst** [comment]
In terms of a non-procurement use for the code, I had in mind the Red Compartida PPP where a [request for expressions of interest](http://www.sct.gob.mx/uploads/media/COMUNICADO-117-2015.pdf) was issued to begin the process. Other jurisdictions seem to follow this practice too (e.g. [aus](https://www.pppkb.com/Pages/S5P0100.aspx), [nz](https://www.interest.co.nz/sites/default/files/NZ%20PPP%20guide.pdf)).

However given that the PPP domain has its own terminology, even though the concepts are similar, I agree it makes more sense to keep the codes domain specific so users can find the information they are looking for.

**Comment by duncandewhurst** [comment]
Reading more on prior information notices in the EU (e.g. this [guidance](http://www.gov.scot/Topics/Government/Procurement/Selling/SupplierJourney/identify-business-opps/tender/PINs) from the Scottish Government and this [example PIN](http://ted.europa.eu/TED/notice/udl?uri=TED:NOTICE:170832-2017:TEXT:EN:HTML&tabId=1)), I'm not sure the GPA definition as it stands is appropriate, since a PIN in the EU may be informational only and doesn't necessarily invite suppliers to submit either a request for participation or a bid.

Here's an attempt at an updated version of the GPA definition to capture that:

> A notice published by a contracting authority to provide information on a planned procurement or to invite interested parties to submit a request for participation, a bid, or both

@jachymhercher may have a view on whether this is an appropriate definition?

**Comment by jpmckinney** [comment]
Aha, I believe GPA's "notice of intended procurement" is what we call a "tender notice" and its "notice of planned procurement" is what matches the PIN.

**Comment by duncandewhurst** [comment]
Okay, that makes more sense, but unfortunately GPA has no explicit definition of "notice of planned procurement".

Given that in the EU the PIN can be used either to provide information on a planned procurement or as a call for competition we have two options:

### 1. Use a broad definition for intendedProcurementNotice which covers both scenarios

This would make it easier for EU publishers to map their systems to OCDS, but would make it harder for users to distinguish how the PIN was being used.

### 2. Use a narrow definition for intendedProcurementNotice which covers planning information only

EU publishers would need map to either the `intendedProcurementNotice` code or the `tender`(Tender Notice) code, depending on how the PIN was being used (there is a radio button for this on the [EU form](http://simap.ted.europa.eu/documents/10184/99173/EN_F01.pdf)).

This would make it harder for users to find all PINs but easier to distinguish whether the notice is for information or a call for competition

**Comment by jpmckinney** [comment]
For some codelists, like procurement method, it's okay to lose information and distinctions, as there are use cases for that information loss, and alternatives to restore the distinctions (e.g. the guidance to put local codes in `procurementMethodDetails`). With the document type codelist, I think we should prefer no loss of distinction. Given that both GPA and EU have a clear distinction (GPA has different terms, EU has a radio button), let's keep the distinction.

**Update:** Although there's no single sentence to copy from the GPA, VII:4-5 have enough information to compose such a sentence. (It also includes the key phrase, "A procuring entity … may use a notice of planned procurement as a notice of intended procurement provided".)

**Comment by duncandewhurst** [comment]
Since the EU prior information notice and the GPA notice of planned procurement are equivalent, i.e. both are primarily a planning notice, but can also be used as a call for competition in certain cases, I propose we add a single code based on the GPA terminology, since it has the broader scope.

Code | Title | Description |
-------|-------|----------------|
plannedProcurementNotice | Planned Procurement Notice | A notice issued by the procuring authority regarding their plans for a future procurement. In some circumstances the notice may also act as an invitation to bid. Also known as a Prior Information Notice.

We should provide additional guidance to publishers and users on using the `release/tag` field to distinguish when a planned procurement notice is used as an invitation to bid.

> When a planned procurement notice is used as an invitation to bid it should be published in an OCDS release with a `release/tag` value of `tender`, otherwise a `release/tag` value of `planning` should be used.

**Comment by jpmckinney** [comment]
I'll have guidance in https://github.com/open-contracting-extensions/european-union regarding the appropriate release tags to use, but if a 'notice of planned procurement' is used as a 'notice of intended procurement', I think its tags should be both 'planning' and 'tender'.

**Comment by jpmckinney** [comment]
The guidance I mentioned above is here: http://standard.open-contracting.org/profiles/eu/master/en/F01/
