### ISSUE TITLE
Justificación de la adjudicación | Award rationale [ES] [EN]

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#625]
# Versión en español

## Issue

La justificación de la adjudicación es un breve texto que se refiere a las razones por las cuales se adjudicó a un proveedor o contratista en particular. Es un dato que puede ser útil para entender de manera sencilla la conclusión de la evaluación de propuestas. En México, es obligatoria su publicación de acuerdo con la Ley General de Transparencia y Acceso a la Información Pública y es una variable requerida que ya el SIPOT:.

## Propuesta
Agregar el atributo “Justificación de la adjudicación” en el objeto de “Adjudicación”.

- Adjudicaciones
  - Adjudicación
    - id
    - title
    - description
    - **rationale (string)**
    - [...]

Nombre | Descripción
-- | --
Justificación | Razones por las cuales se justifica la elección del proveedor o contratista.

# English version

## Issue

The award rationale is a short text describing the reasons why the award was made for a particular supplier. It is a data that can be useful to understand, in a simple way, the end of the evaluation period. In Mexico, from INAI we have this data in our system and its publication is mandatory according to our Freedom for Information Act.

## Proposal
Add a new field named “rationale” to the “Award” object.

- Awards
  - Award
    - id
    - tittle
    - description
    - **rationale (string)**
    - [...]

Name | Description
-- | --
rationale | The reason why the supplier was selected.

**Comment by JArielMG** [comment]
The following example shows the location where a new field called "award rationale" is added

Worked example:
```
{
  "definitions": {
            "Award": {
                  "properties": {
                            "rationale": {
                                      "title": "Rationale",
                                      "description": "The reason why the supplier was selected.",
                                      "type": [
                                               "string",
                                               "null"
                                              ]
                                         }
                                }
                     }
                 }
}
```
I would welcome views on this suggested modelling.

**Comment by timgdavies** [comment]
@JArielMG Thanks again for a clearly written issue. 

To check: do you currently have *other* values in `award.description` - as that field is intentionally broadly defined (as 'award description') so that it could be used to contain information such as the reason for the award. 

If you don't have anything else going into `award.description` - or you could concatenate a short existing description with the rationale in a uniform way when creating the data - then placing the rationale there, rather than creating a new field, would mean it is visible via tools and platforms that do not know to check a new `rationale` field.

However, if you already have a value in `award.description`, and have a strong use-case for this text to be kept separate, then the approach of the `rationale` field above would make sense.

In definition terms, we already have `planning.rationale` which is defined as:

> "The rationale for the procurement provided in free text. More detail can be provided in an attached document."

and `procurementMethodRationale` defined as:

> "Rationale for the chosen procurement method. This is especially important to provide a justification in the case of limited tenders or direct awards."

and `amendment.rationale` defined as:

> "An explanation for the amendment."

I would suggest if aiming for a community extension that can be used by others, aiming for a definition such as:

*"A short summary of the reasons for making this specific award, and/or selecting the particular supplier, provided in free text. More detail can be provided in attached documents."*

**Comment by antonioherrera** [comment]
We redifine the texts as follows:

**Name** | **Description**
-- | --
`rationale` Award rationale | A short summary of the reasons for making this specific award, and/or selecting the particular supplier, provided in free text. More detail can be provided in attached documents.

**Comment by jpmckinney** [comment]
@antonioherrera I did an initial review of the [extension](https://github.com/INAImexico/ocds_awardRationale_extension), and @JArielMG merged the changes. Would you like this extension to be added to the [extension registry](https://github.com/open-contracting/extension_registry) as a community extension?

**Comment by antonioherrera** [comment]
Sure, go ahead.

**Comment by jpmckinney** [comment]
We are considering a new `statusDetails` field in OCDS, which will satisfy this use case, as well as broader use cases, depending on the `status` value. #764 For example, `statusDetails` can explain why an award was made, but also why an award wasn't made (which is more commonly disclosed, from the bit of research I did to check this use case).

As such, I'll close this issue as a local extension.
