### ISSUE TITLE
Should optional fields be nullable, and required fields be non-nullable?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#630]
release-schema.json has required but nullable:

* /definitions/OrganizationReference/properties/name #639 

And optional but non-nullable:

* /definitions/Amendment/properties/changes/items/properties/property (deprecated)
* /definitions/Item/properties/unit
* /definitions/Organization/properties/id
* /definitions/OrganizationReference/properties/id
* /definitions/RelatedProcess/properties/id

We should document any reasons for optional fields being non-nullable, and for required fields being nullable.

**Comment by timgdavies** [comment]
I believe this is related to merging and the removal of values - but it could certainly do with a review and re-thinking through, and then us writing down the rules and testing for them.

The two places in documentation that we need to draw on are at:

* [Merging](http://standard.open-contracting.org/latest/en/schema/merging/) and
* [Emptying fields](http://standard.open-contracting.org/latest/en/schema/reference/#empty-fields)

One of the key issues here relates to whether, to remove all the items from an array, you can just null out the array itself, or whether each individual item needs to be removed (which would be done by providing the id of the item, but having null for all the properties). 

Now we have some real-world examples of data being integrated from multiple systems, this would be something to work through again and check what is most realistic in terms of data production, and avoiding data loss.

**Comment by jpmckinney** [comment]
Indeed – the issue just shows there's some inconsistency in what is nullable (based on the rules we've written so far), which additional rules and tests will help to avoid in extensions and future versions.

**Comment by jpmckinney** [comment]
Relevant issue re: emptying fields: https://github.com/open-contracting/standard/issues/232

**Comment by timgdavies** [comment]
Thanks. I've been reviewing this, and have drafted guidance below.

I think this grounds all the observed cases above *except* `/definitions/Item/properties/unit` where the field should be an object or null. 

If you agree with that, I'll open a bug ticket to fix `unit`.

I accept that this relies in #232 being resolved fully, which it is not yet, and I did consider that it would be legitimate to conclude we should in fact permit all properties that point to an array of objects to also be `null`, removing the whole array when merging - but my recollection of why this was not done was due to the risk that this leads to unintentional loss of data, particularly when merging data from different places. 

## Documenting current practice for type = null
Any non-required property pointing to a literal, array of literals, or single object should support a type of `null`. E.g.:

```json
{ 
  "status": {
        "title": "Contract status",
        "type": [
            "string",
            "null"
          ]
        }
}
```

Allowing properties to be `null` is important to the [merging process](http://standard.open-contracting.org/latest/en/schema/merging/), in which `null` is used to [remove a value from the compiledRelease](http://standard.open-contracting.org/latest/en/schema/reference/#emptying-fields-and-values).

(To be confirmed:) Any non-required property pointing to an array of objects should not allow `null` as a value, as array entries should be explicitly tagged for removal following the pattern outlined in [Standard#232](https://github.com/open-contracting/standard/issues/232)

**Comment by jpmckinney** [comment]
Makes sense to me. I updated the issue description with only the fields that still don't meet our stated rules.

**Comment by jpmckinney** [comment]
@timgdavies Shall I open a PR to add `"null"` as a valid `type` for:

* /definitions/Item/properties/unit
* /definitions/Organization/properties/id
* /definitions/OrganizationReference/properties/id
* /definitions/RelatedProcess/properties/id

**Comment by timgdavies** [comment]
Will look at this as part of bugfix release

**Comment by jpmckinney** [comment]
I've added this to the '1.1.x Cleanup' milestone – perhaps not all of which will be completed for the bugfix release.

**Comment by timgdavies** [comment]
I've just been reviewing this, and I *think* the `id` fields for 

* `Organization`
* `OrganizationReference`
* `RelatedProcess`

should in fact be required, rather than nullable to accommodate our current preferred option in #232.

**Comment by jpmckinney** [comment]
Wouldn't that be backwards-incompatible?

**Comment by timgdavies** [comment]
If these fields were made required under 1.1.3 it is possible that data that was valid under 1.1.x and which omitted one of the above fields (x<=2) would become invalid under 1.1.3

I'm not sure if our behaviour with respect to backwards compatibility would be different if we consider the omission of `id` requirement to be a bug. However, I've run through reasoning below to check if this thinking could be invoked anyway.

**Can we consider the omission of `id` requirement to be a bug?**

The requirement for `id` is based on an approach to remove objects from the version array, which is not yet formally part of the standard. 

If #232 had been formally adopted, this would be a bug - but in the absence of that - this is just a limitation of the standard.

So I don't think we can consider this a bug. 

**What should our response be?**

I propose to:

(1) Resolve the issue with `item.unit` being nullable

(2) Open a new issue to make `id` fields for:
  * `Organization`
  * `OrganizationReference`
  * `RelatedProcess`

required as of the next MAJOR upgrade. 

(3) Leave the `id` fields as non-nullable, but not required, in OCDS 1.x series

(4) Open an issue to add **warnings** to the validator for when `Organization`, `OrganizationReference` and `RelatedProcess` are missing an `id` field

**Comment by jpmckinney** [comment]
That seems reasonable to me!
