### ISSUE TITLE
documentType: Consider sync with PPP profile

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#643]
http://standard.open-contracting.org/profiles/ppp/latest/en/reference/codelists/#documenttype

See also https://github.com/open-contracting/public-private-partnerships/issues/94

**Comment by timgdavies** [comment]
Are you suggesting we should consider importing all the values from the PPP Document Type codelist into the main OCDS document type codelist?

**Comment by jpmckinney** [comment]
We should consider, though there may be obvious reasons to not import them all – I haven't thought deeply about it.

**Comment by duncandewhurst** [comment]
Importing the whole list wouldn't be appropriate since there are some codes which are PPP specific, e.g. `pppModeRationale`, `projectAdditionality`, `equityTransferCaps` etc.

Until we've seen more use of the PPP extension, I suggest we consider individual codes for inclusion in the core `documentType` codelist as and when publishers are asking for something similar to be added.

**Comment by jpmckinney** [comment]
I judge this issue considered. We can open specific issues for specific codes. Closing.
