### ISSUE TITLE
Update link to the Project Open Data Metadata Schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#685]
The link from the [Dataset and feed discovery](http://standard.open-contracting.org/latest/en/implementation/hosting/#dataset-and-feed-discovery) section of the implementation guidance points to a [deprecated version of the Project Open Data Metadata Schema](https://project-open-data.cio.gov/schema/).

We should check if it is appropriate to update the link to the [current version of the schema](https://project-open-data.cio.gov/v1.1/schema/)

**Comment by jpmckinney** [comment]
Need to consider how much detail to provide in this section, versus just linking out.

**Comment by jpmckinney** [comment]
Closed by #963, which eliminates a discussion of web discovery. This problem is not solved (for data in general), and it is premature to recommend an approach in our documentation. For now, the typical means of discovering data (web searches, browsing open data portals, etc.) work well enough, and OCP will be implementing an OCDS registry. See #963 for other reasons.
