### ISSUE TITLE
Expand Document descriptions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#707]
The documentation extension previously introduced updated descriptions for the document building block and some of its fields (see https://github.com/open-contracting/ocds-extensions/issues/45):

The updated descriptions are copied below for consideration for inclusion in OCDS core:

- `document`: Documentation can be supporting information, formal notices, downloadable forms, or any other kind of resource that should be made public as part an open contracting process. The documentType field can be used to indicate the nature of each document. The description can be used to provide a summary of the document contents where appropriate, and the URL fields used to link directly to downloadable copies of the document.

This description for `document` doesn't add anything to the existing description, beyond information already provided in the descriptions of other fields, so the existing definitions is preferred.

- `document/description`: A short summary of the document.

This description omits the recommended restriction on the length of the summary which is included in the existing description, this is preferable in some cases to allow publishers to provide longer summaries, e.g. of very long documents such as PPP contracts.

- `document/url`: A direct link to the documentation. The server providing access to this document should be configured to correctly report the document mime type. Where the information for this documentType is found within a larger document, the page number or section should be included using a fragment identifier. E.g. #page=32.

This description adds a recommendation on using fragment identifiers, this is preferable when document types are used to identify specific information in larger documents, as in the PPP extension

**Comment by duncandewhurst** [comment]
The readme for the documentation extension also includes some guidance on the use of fields in the core standard, which will be removed. Copying here for consideration for inclusion in OCDS core:

> Contracting processes involve many different documents. There should be a presumption of 'open by default' when it comes to publishing these documents as part of an Open Contracting process.

> These should generally be provided at their own stable URL, without requirements to log-in or authenticate. Redactions should be kept to a minimum.

> ...[OCDS] describes a way to:
> * Summarize the information in the description field of the relevant document block;

> Providing clear summaries allows applications to display this information in a user-interface, allowing users to access key facts and justifications without clicking through to download and search for the information in a full document.

**Comment by ColinMaudry** [comment]
### Document description

> - document: Documentation can be supporting information, formal notices, downloadable forms, or any other kind of resource that should be made public as part an open contracting process. The documentType field can be used to indicate the nature of each document. The description can be used to provide a summary of the document contents where appropriate, and the URL fields used to link directly to downloadable copies of the document.
> 
> This description for document doesn't add anything to the existing description, beyond information already provided in the descriptions of other fields, so the existing definitions is preferred.

I agree, current wording is better :heavy_check_mark: 

### Document's `description` description

> - document/description: A short summary of the document.
> 
> This description omits the recommended restriction on the length of the summary which is included in the existing description, this is preferable in some cases to allow publishers to provide longer summaries, e.g. of very long documents such as PPP contracts.

The current description of `description` says:

> Descriptions are recommended to not exceed 250 words. In the event the document is not accessible online…

I think the current wording gives enough flexibility to publishers, especially if specific documentation (e.g. [PPP profile documentation](https://standard.open-contracting.org/profiles/ppp/latest/en/)) or OCP support advises to provide longer descriptions when necessary. I consequently suggest we don't update the current `description` of Document and maintain the recommendation to limit the size of the string, which, I believe, is relevant in most cases.

### Document's `url` description

> - document/url: A direct link to the documentation. The server providing access to this document should be configured to correctly report the document mime type. Where the information for this documentType is found within a larger document, the page number or section should be included using a fragment identifier. E.g. #page=32.
> 
> This description adds a recommendation on using fragment identifiers, this is preferable when document types are used to identify specific information in larger documents, as in the PPP extension

I agree, this description should replace the current description of `url` as it adds relevant guidance :heavy_check_mark:

**Comment by jpmckinney** [comment]
@ColinMaudry Can you also consider whether to integrate the content from https://github.com/open-contracting/standard/issues/707#issuecomment-514595290 into the docs, perhaps at https://standard.open-contracting.org/latest/en/schema/reference/#document ?

@duncandewhurst Okay to keep the description of the document `description` field as-is?

**Comment by duncandewhurst** [comment]
> @duncandewhurst Okay to keep the description of the document `description` field as-is?

Sounds good.

**Comment by JachymHercher** [comment]
In the EU, eForms' Documents URL (BT-15) field contains several other points of information. Some, e.g. what exactly "direct" and "unrestricted" means, were clarified because they were not considered obvious by stakeholders. These might be useful for the non-normative text mentioned in https://github.com/open-contracting/standard/issues/707#issuecomment-691178955 or could become a normative should: 
1. The internet address for accessing (the non-confidential part of) the procurement documents. (Comment: the parentheses clarify that this covers also the case when part of the documents have been restricted, e.g. for military contracts.)
1. [...] the address must give access that is direct (i.e. the exact webpage with the documents, not a general website)
1. unrestricted (e.g. no registration), 
1. full (i.e. the procurement documents must be complete) 
1. and free of charge 
1. and the documents must be available already at the time of the publication of the notice.

**Comment by jpmckinney** [comment]
Those sound like reasonable recommendations (SHOULD) to make in this part of the reference section: https://standard.open-contracting.org/latest/en/schema/reference/#document

They are less about the semantics of the field, and more about *how* to disclose (e.g. free of charge), so I think it makes sense to put them on that page, rather than in the schema.

If we are uncomfortable adding a SHOULD in a minor version, we can use the non-normative form "ought to".

**Comment by JachymHercher** [comment]
Consistency detail: the definition of `document.url` in https://github.com/open-contracting/standard/issues/707#issuecomment-691107254 mentions "direct". Shouldn't we also move it form the definition to the general #document reference section? 

(If  not, then point 2 from https://github.com/open-contracting/standard/issues/707#issuecomment-731576031 should IMO also be part of the definition, because it just clarifies "direct".)

3,5,6 is definitely for the document reference section; if 2 above made it into the definition, then 1 and 4 imo possibly also could, but it's pretty much fine either way.

**Comment by jpmckinney** [comment]
Good catch. I think 1,2,4 can go into the field description, but using descriptive language (e.g. "The internet address for directly accessing") rather than prescriptive language ("the address must give access that is direct"). OCDS' norms (MUST) are with respect to data format, not with respect to e.g. the completeness of procurement documents, which are more like legal requirements. It's maybe a fine distinction, but OCDS can at best say that a publisher is misusing a field to link to a document, rather than mis-publishing the document.

**Comment by ColinMaudry** [comment]
I'll modify the description of the Document object using points 1,2 and 4 suggested by Jachym, using descriptive language a suggested by James.

I'll modify the reference text using points 3, 5 and 6. I lean toward using non-normative verbs given...

> OCDS norms are with respect to data format, not with respect to e.g. the completeness of procurement documents, which are more like legal requirements.

OK?

**Comment by jpmckinney** [comment]
@ColinMaudry I think @JachymHercher will prepare the PR; it'll be simpler since he was the last to make suggestions.

**Comment by JachymHercher** [comment]
When working on the PR, I had some second thoughts (reflected in the PR):
- I don't mention the confidentiality topic in the definition, as it is complex. Instead, I added text to the guidance.
- I left "direct" and "full" in the definition, but I think it would be nice to leave out both and just deal with it in more detail in the guidance. 

    (Note: when I was drawing the comparisons with eForms, I did not realize that while eForms talks only about procurement documents (in the sense of technical specifications, eligibility criteria, award criteria, etc.), OCDS speaks about documents in a very wide sense.) 
- I _think_ the points I propose in the guidance apply to all the documents, but it might be worth double checking. If not, then instead they should probably go into a few codes in https://standard.open-contracting.org/1.1/en/schema/codelists/#document-type, but repetition would probably be an issue.
- I dropped "attachments", see https://github.com/open-contracting/standard/issues/1188. 

Also, reading

> OCDS' norms (MUST) are with respect to data format, not with respect to e.g. the completeness of procurement documents, which are more like legal requirements.

I am unsure whether the "should" in "The server providing access to this document should be configured to correctly report the document mime type." is ok, @jpmckinney. Shouldn't it stay an "ought to"?

**Comment by jpmckinney** [comment]
I agree with your points on what to put in the definition versus the guidance.

> I am unsure whether the "should" in "The server providing access to this document should be configured to correctly report the document mime type." is ok, @jpmckinney. Shouldn't it stay an "ought to"?

Yes, that is more of an "ought to".

**Comment by JachymHercher** [comment]
I interpret your comment as agreeing with removing "direct" and "full" :). I've removed them and updated the PR. 
> I left "direct" and "full" in the definition, but I think it would be nice to leave out both and just deal with it in more detail in the guidance.

**Comment by jpmckinney** [comment]
All comments are represented in #1189, which also adds links to a couple external resources to support the "open by default" recommendation.
