### ISSUE TITLE
Parent contract - planning data relates to multiple contracting processes.

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#72]
Do we want to have a parent ocid? Could be useful in the case of planning data (this came up somewhere), but could be very unhelpful in that it then provides two v. different ways to reasonably represent framework contracts.  Are there other use cases for a parent & child contract that really make it necessary given the challenges it would bring in.

**Comment by LindseyAM** [comment]
Several countries publish something like a draft invitation to tender or intent to procure including Korea and I believe Mexico and Colombia. But I believe this is a different issue, the desire to link the planned procurement from the procurement plan with the eventual contracting process. This is tough to do because of course the planned procurements could (for example) be combined. A good example of procurement planning data is Indonesia : https://sirup.lkpp.go.id

**Comment by timgdavies** [comment]
If we stick to the strong definition that an OCID represents **a single contracting process**, and a single contracting process can have, at most, one tender, then I think the original fear of offering two ways of representing frameworks might be addressed. 

I.e. If a framework involves **orders** off the framework, then the current nested award and contract approach should be used. If the framework process involves mini-tenders, then a separate OCID and record should exist, cross-referencing back to the framework. 

The question then is whether we can use a common property to indicate both:

* A contracting planning process (which may not have any tender section attached);
* A parent framework;

A candidate property might be ```priorProcess``` - and could either have a value of an OCID, or could have a more complex value including the OCID of the prior process, where it can be found, and more information on the kind of process (e.g.

```
{
   "priorProcess": {
      "ocid":"ocds-123456-23673",
      "processType":"planning",
      "uri":"http://example.open-contracting.org/records/ocds-123456-123562"
    }
}
```

**Comment by LindseyAM** [comment]
@timgdavies I this we should at first consider this planning issue separately from frameworks (as framework is a type of contracting process). The issue as I understand it is that a procurement will be planned in advance but then that plan may not be complied with or the procurement will not match one to one with the plan. For example, It may be that a procuring entity indicates in its plan that it will budget X dollars for procurement of a particular good or service. But then in reality it combines procurement or splits into multiple procurements and didnt match one to one. So, in this situation, you are suggesting that when the contracting process starts (whether with an intent to procure or an actual tender notice) that in that moment there should be a field that links to the relevant portion of the procurement plan?

**Comment by timgdavies** [comment]
> "So, in this situation, you are suggesting that when the contracting process starts (whether with an intent to procure or an actual tender notice) that in that moment there should be a field that links to the relevant portion of the procurement plan?"

Almost. I'm suggesting that each tender that has resulted from a plan could refer back to an OCDS record which contains details of the relevant planning stage.

So you could have one planning record, and 1..n tender records, each of which refer back to that one planning record.

But: there isn't a mechanism here to refer to a 'particular portion of the procurement plan' - if the planning record covers a whole procurement plan. There would need to be a planning record created for each portion of the procurement plan we want to be able to reference. 

Ultimately the issue here remains that we can only do this with data well when procurement plans are managed as structured data... which we've not had good examples of to work from so far.

**Comment by LindseyAM** [comment]
Did you look at the Indonesia example I shared? It is in Bahasa but google translate works decent: https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fsirup.lkpp.go.id%2Fsirup%2Frup%2FdetailPaketPenyedia%2F2746101&edit-text=

**Comment by timgdavies** [comment]
Ok - so this is a good case of where we do have reasonably structured data on procurement plans - broken down to a level likely to result in clearly identifiable tenders. 

Here, each tender resulting from this particular procurement package could include a planning section containing some of the information from that procurement package, and linking back to that page.

**Comment by joshuacpowell** [comment]
Bit of a mixed bag in the Philippines - as some items represent reasonably predictable tenders, while others represent more "shopping lists": http://www.gppb.gov.ph/monitoring/app.php

**Comment by timgdavies** [comment]
We have work to do to better understand, and document, how the planning section should be used.

This may also involve some extensions to the planning section.

**Comment by duncandewhurst** [comment]
This is continued in #371
