### ISSUE TITLE
[extension] Marks/Classifications/Characteristics of a contracting process

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#736]
### Motivation

Some countries, Colombia and Paraguay for example, publishs some marks, classifications or characteristics of a process to identify them. In the Colombia case they have the mark 'Acuerdo de Paz', for mark those process that are part of the peace agreement. 
In Paraguay they publishs an array of "tags", that can have differents values as: "Producción Nacional", "Seguridad Nacional", "Agricultura Familiar", among others. 
Those marks are specif for each country and helps to classificate the process.

### Proposal

Add an  "characteristics" array of open code list values in the release object or an array of strings. 
Example: 

```javascript
....
{
 "releases": [
   {
      "language": "es",
      "ocid": "ocds-03ad3f-246807",
      "date": "2018-07-27T19:15:53Z",
      "characteristics": ["Producción Nacional", "Agricultura Familiar"]
      "tag": [
        "award"
      ],
      "initiationType": "tender",
}
     ....
```

Suggestions are welcome.

**Comment by jpmckinney** [comment]
Could you provide more information about the nature of these tags?

There is a draft [coveredBy extension](https://github.com/open-contracting-extensions/ocds_coveredBy_extension) that may cover some. That extension was created because the Revised Agreement on Government Procurement (GPA) includes: "each notice of intended procurement shall include … l. an indication that the procurement is covered by this Agreement." Is the situation similar with Colombia's peace agreements?

Presumably, Paraguay has "Producción Nacional", "Seguridad Nacional", "Agricultura Familiar" because a government policy, initiative, regulation, or commitment, etc. has a need for those. Could you find out the reason for which the data includes these?

Having a field in which publishers dump tags will not be very meaningful to users. Once we determine why these tags are in the data, and what the meaning of the tags are, then we can model an extension that is appropriate to each case.

**Comment by PaulBoroday** [comment]
@yolile, please clarify, these characteristics (Producción Nacional", "Agricultura Familiar“) should describe (classify, mark,etc) required subject of procurement or some, let’s say, state program in the framework of which this procurement is carried out? Or something else?

**Comment by yolile** [comment]
these are all the marks that Paraguay publish: https://www.contrataciones.gov.py/datos/api/v2/doc/parametros?dominio=MARCA_CONTRATO
on that list, some of the marks can be covered by the coveredBy extension, because the marks has a legal normative that acompaigns the mark, but others are just a higligth characteristic that the publisher wants to remark and maybe it is not necesary to publish it in the standard format.

**Comment by yolile** [comment]
Closing since the coveredBy extension can be used
