### ISSUE TITLE
Extensions list is broken on the party details page

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#741]
From https://github.com/open-contracting/standard/commit/c601cb36da251e7cc76946d46aeb4acdd75c4389#commitcomment-29182892

The extensionlist directive for community extensions on the [party details page](http://standard.open-contracting.org/1.1-dev/en/extensions/party_details/) is broken, it should display the party scale extension.

**Comment by jpmckinney** [comment]
You already fixed it :) https://github.com/open-contracting/standard/commit/ec39047e514d79756f50f5705b42a50622415b63#diff-417406ffc884d8a1b00a68ea075c537f

**Comment by jpmckinney** [comment]
The list is empty because the directive only lists core extensions (or, if used in a profile, only lists the profile's extensions).

Here's the [original code](https://github.com/open-contracting/sphinxcontrib-opencontracting/blame/b1e8fb31a219d08782ec2c2b35a8edbbc1cf9a61/sphinxcontrib/opencontracting.py#L52-L54) before my more recent changes, just to demonstrate that it was only listing core extensions.

~~I'd be happy to change the logic to simply list any extension in the registry with the given category, regardless of core status or profile inclusion.~~ Nevermind: We want to render community extensions as JavaScript, since we don't want to have to rebuild the docs just to include more extensions.

**Comment by duncandewhurst** [comment]
I may have misunderstood @Bjwebb's comment that this was due to the javascript for listing the community extensions wasn't working on that page of the docs, but I thought the directive could also list community extensions, e.g.

![image](https://user-images.githubusercontent.com/19265814/43537500-62bce7bc-95b7-11e8-8416-6b6476cb857f.png)

**Comment by jpmckinney** [comment]
Ah, oops. The directive does only list core extensions, but there is JS for listing community extensions that targets the HTML created by the directive. I think the bug is that the extensionlist JS code only runs if `isSchemaReferencePage` is true, i.e. it's not being run on `extensions/party_details/`.

**Comment by leobaz** [comment]
Is this going to be fixed, still not showing any party detail?

![image](https://user-images.githubusercontent.com/35137491/49376438-84399c80-f707-11e8-8ba4-d42c2a490ade.png)

**Comment by jpmckinney** [comment]
Yes, it will be fixed in 1.1.4, which is scheduled for the first quarter of next year.

**Comment by duncandewhurst** [comment]
@leobaz - in the meantime, Party Details - Scale is the only partyDetail extension, you can find the documentation [here](https://github.com/open-contracting-extensions/ocds_partyDetails_scale_extension/blob/master/README.md)

**Comment by duncandewhurst** [comment]
I think this is still broken in the latest version of the docs: http://standard.open-contracting.org/latest/en/extensions/party_details/

**Comment by jpmckinney** [comment]
It's fixed on dev: http://standard.open-contracting.org/1.1-dev/en/extensions/party_details/

**Comment by duncandewhurst** [comment]
I think this is broken again.

https://standard.open-contracting.org/latest/en/schema/reference/#parties:

![image](https://github.com/open-contracting/standard/assets/19265814/efcc7776-4c1d-4e95-aa96-3dda59ff6bfe)

https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#parties:

![image](https://github.com/open-contracting/standard/assets/19265814/94632ebf-3d8f-49df-81dd-b1e950d2a289)

**Comment by jpmckinney** [comment]
Ah, it was the new Content-Security-Policy. Fixed!
