### ISSUE TITLE
Item: Additional attributes

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#751]
Uruguay has additional information about the items to be procured  and the items awarded as:

	id_color		(color identifier)
	desc_color	(color description)		
	id_variante	(variant identifier)		
	variante		(variant description)
	unidad_medida_variante	 (variant measure unit)
	medida_variante		(variant measure description)	
	presentacion			(presentation)
	medida_presentacion	(presentation measure)
	unidad_medida_presentacion (presentation measure unit)	
	id_detalle_variante		(variant detail identifier)
	desc_detalle_variante	(variant detail description)
	id_marca			(brand identifier)
	desc_marca           (brand description)
			
and dynamic atributtes:

        	id_prop_atributo (attribute id)
        	desc_prop_atributo (attribute name)
        	id_unidad_med_prop_atributo (attribute measure unit identifier)
        	desc_unidad_med_prop_atributo (attribute measure unit description)
        	value 

Proposal:

```javascript
{ "items": [
           "id" : "1",
           "description": "tables",
           "attributes": [
               {
                    "id" : "1",
                     "name": "color",
                     "value": "red",
                     "unit": null
                 }
               ]
] }
```
Add a array of attributes to the item object to mapped all the specific attributes of each item

**Comment by jpmckinney** [comment]
I think for this level of detail, it makes sense to have a generic model as you suggest. The two options are either:

1. An array of objects with generic fields to describe an attribute (like in your example), and similar to the `Metric` and `Observation` classes in the [metrics](https://github.com/open-contracting-extensions/ocds_metrics_extension/blob/master/release-schema.json) extension
1. Key-value pairs, like for `dimensions` in the [metrics](https://github.com/open-contracting-extensions/ocds_metrics_extension/blob/master/release-schema.json#L181-L196) and [tariffs](https://github.com/open-contracting-extensions/ocds_tariffs_extension/blob/master/release-schema.json#L118-L133) extensions, and like `classifications` and `measures` in the [budget and spend](https://github.com/open-contracting-extensions/ocds_budget_and_spend_extension/blob/master/release-schema.json) extension

Since the attributes have more than just a name and value, the first option (i.e. your proposal) seems like the right approach.

For `unit`, we should use the same object as for `Item.unit` in OCDS.

@yolile Has Uruguay started an extension?

**Comment by yolile** [comment]
No, they didnt start the extension yet, and finally they are not going to have time this year to include extensions in their data. But Paraguay can use this extension as well and their are going to start the update of their data in the following months so maybe they will develop this extension

**Comment by yolile** [comment]
the extension is drafted here: https://gitlab.com/dncp-opendata/ocds_item_attributes_extension/tree/master

cc @duncandewhurst

**Comment by jpmckinney** [comment]
Closing as the extension is published.
