### ISSUE TITLE
Worked example (1.2): Contract suspension

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#758]
In the [ageops](https://ageops.net) system in Afghanistan contracts can have status = suspended ([example](https://ageops.net/en/procurement-procedure/contract/progress/RRD%252FMOF%252FNRAP%252FKBL%252FLGR%252F055%252FC2%252F001))

This indicates that the contract is temporarily suspended, for example due to security reasons, and will either be resumed at a later date or cancelled. The system does not capture a reason or description for the suspension.

In OCDS, contract status is a closed codelist with the following codes: pending, active, cancelled, terminated.

Similar to the discussion on suspended tenders in https://github.com/open-contracting/standard/issues/430, there are two main options we could pursue:

**(1) Adding an entry to the contract status codelist**

A contract status of 'suspended' could be added to the codelist.

This would mean that:

* When the contract was suspended, it would cease to show up in lists of active contracts
* Consuming applications would need to be aware of the 'suspended' contract status

Contract status is a closed codelist, which means that any changes would have to be made as part of an upgrade to the standard.

**(2) Adding a new field via an extension**

A true/false `suspended` field could be added to the contract object to indicate whether the contract is suspended

This would mean that:

* Applications that are not aware of the new field would continue to display the contract in a list of active contracts;
* Applications that are aware of the new field could use this to filter views or display extra information about a contract

## Questions

Assuming we pursue option (2), at least until the next standard upgrade:

(1) Do any other systems or legal frameworks use the concept of a suspended contract?

(2) Does a suspended contract fit the description of the `active` code from the contract status codelist:

> This contract has been signed by all the parties, and is now legally in force.

(3) Is 'suspended' the appropriate terminology?

(4) Should an extension also introduce a free text `statusDetails` field where details of the reason for the suspension could be provided.

(5) Should an extension also introduce any 'documentType' codelist entries to link to related reasons for suspension or documentation of the suspension of the contract.

(6) Should guidance include any information on including milestones or other free-text descriptions about suspensions?

**Comment by timgdavies** [comment]
See also long standing issue re status='terminated' #395 which suggests this codelist would benefit from wider revisions.

**Comment by duncandewhurst** [comment]
Feedback from Afghanistan - there isn't a specific legal definition for a suspended contract in Afghanistan, however contracts are suspended in practice.

**Comment by jpmckinney** [comment]
For now, I would recommend putting 'suspended' in a `statusDetails` field, as suggested by #764 

1. A brief web search suggests that contract suspension is indeed a common concept. It appears more at the contract management level rather than at the primary legislation level.
2. The contract is still active, but work has been suspended. For example, a government changes zoning, such that a construction contract is now illegal. The buyer seeks a variance to the zoning change, such that the supplier may proceed. In the meantime, the contract is suspended. If the buyer fails to get a variance, the contract will likely be cancelled/discharged.
3. 'suspended' seems to be the most common and correct term.
4. Yes. See #764, which is likely to be added to the core schema given the number of related issues it resolves.
5. I don't know that such documents are commonly prepared, or are similar across jurisdictions, but codes can be added if so.
6. I'm not aware of milestones related to suspensions, but guidance can be authored once common use cases are known.

**Comment by jpmckinney** [comment]
@duncandewhurst Can you review #430 and, if appropriate, merge this issue into that issue?

**Comment by jpmckinney** [comment]
Merging this issue into #764 as a worked example.

**Comment by jpmckinney** [comment]
Re-opening this issue to be about a worked example or other documentation. Another relevant comment is https://github.com/open-contracting/standard/issues/430#issuecomment-660405607

**Comment by jpmckinney** [comment]
For OCDS 1.1, if desired, we can add more docs to the status details extension.

**Comment by duncandewhurst** [comment]
Sounds good. I'll draft an example that we can use in both places.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/standard/pull/1344

**Comment by jpmckinney** [comment]
#1344 uses `statusDetails`, but this has been changed to `finalStatusDetails` per #1160, so #1344 has to be reverted.

We don't have enough information to resolve this issue. So far, of the requirements in https://github.com/open-contracting/standard/issues/430#issuecomment-660405607, we've only established that the fact "that there is a suspension" can be determined in Afghanistan. Ideally, it would be better to be able to say *when* the contract was suspended, e.g. as a period (`suspensionDate/startDate`), such that when the suspension ends, an endDate can be provided (i.e. so that the fields are "write-once"). However, we need more evidence from more potential publishers before we commit to new fields.

In the meantime, the Status Details extension can continue to be used following the old modelling.

**Comment by duncandewhurst** [comment]
> #1344 uses `statusDetails`, but this has been changed to `finalStatusDetails` per #1160, so #1344 has to be reverted.

Done in #1648
