### ISSUE TITLE
Improve publication policy guidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#759]
The present guidance is: http://standard.open-contracting.org/latest/en/implementation/publication_policy/

There's an opportunity to improve this based on the recent [community call](https://drive.google.com/drive/folders/1x-aboyQ7ppvWHHKyYCRrbwc9hAJkHuGy) and guidance given privately to publishers (e.g. CRM issue 3554 update 22).

cc @LindseyAM

**Comment by pindec** [comment]
The new  [publication policy template is now published](https://docs.google.com/document/d/1IEZhotGcgdC7XBmLepdPQRVN5y4b5l9H0y0h32HAQyo/view) so we should add a link to it from [standards docs](http://standard.open-contracting.org/latest/en/implementation/publication_policy/) and/or otherwise update the standards docs page.

**Comment by jpmckinney** [comment]
Added 1.1.5 milestone.

**Comment by jpmckinney** [comment]
@LindseyAM Here's the OC4IDS page for 0.9.2: https://standard.open-contracting.org/infrastructure/0.9-dev/en/guidance/data_user_guide/

**Comment by jpmckinney** [comment]
Fixed in #986.
