### ISSUE TITLE
How to to represent disqualified tenderers

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#763]
The Kyrgyz Republic combines qualification and award into one action. Disqualified bidders have an 'award decision' document. To disambiguate unsuccessful awards (which means unsuccessful for any reason besides cancellation) from disqualified bidders, it was proposed to add a 'disqualified' status, or to put 'disqualified' under a new `statusDetails` field. This issue also arose in Ukraine. In both cases, there is a 'decision protocol', which contains information on (1) who is the winner and (2) who was disqualified during evaluation.

This issue might require more research into how to represent qualification in OCDS, to give this publisher an option to express this information separately from awards.

**Comment by MusicMaker1337** [comment]
It may be better to separate the status of the award decision from the decision itself because these are totally different concepts. 

Imagine a situation, where the procuring entity decided to disqualify a bidder, but then changed its mind and canceled the decision. Tn this case the decision 'disqualified' itself did not change at all, but the status of that decision changed: "I cancel my disqualification decision". 

Maybe there can be an `awardDecision` object, which would have two separate fields: `status` for the decision status (the same as `award.status`) and `decision` for the decision itself.

**Comment by jpmckinney** [comment]
This might involve finding a way to make the following extension backwards-compatible with OCDS and available for wider use: https://github.com/open-contracting/ocds_qualification_extension

**Comment by jpmckinney** [comment]
Looking back at this issue, we already have a [Bid extension](https://extensions.open-contracting.org/en/extensions/bids/master/schema/#bid), in which a particular tenderer's bid can be given a status of 'disqualified'.

Different jurisdictions will disclose disqualifications at different points in their process (whether in an award decision, after opening the first envelope only, etc.). However, conceptually, disqualification means the same thing. As such, I think all jurisdictions can use a common model using the bids extension.

Happy to re-open to consider any disadvantages.
