### ISSUE TITLE
Use URLs as identifiers

### ISSUE THREAD

**Issue by akuckartz** [open-contracting/standard#766]
Context: new issue was suggested in https://github.com/open-contracting/standard/issues/461#issuecomment-438394935

**Comment by jpmckinney** [comment]
It would be impractical for publishers to mint URLs for every identifier in OCDS. Which identifiers do you mean?

**Comment by akuckartz** [comment]
Individual URLs generally do not need to be minted manually but can be minted by using software. The required effort for publishers therefore should be rather limited.

**Comment by jpmckinney** [comment]
I think you underestimate the contexts in which many publishers are operating :) Please specify which identifiers within the OCDS schema you mean.

**Comment by akuckartz** [comment]
Maybe start with the "Open Contracting ID" (ocid).

**Comment by jpmckinney** [comment]
The [OCID](http://standard.open-contracting.org/latest/en/schema/identifiers/#contracting-process-identifier-ocid) isn't presently constructed as a URI. This could involve changing the OCID Prefix to start with `ocds:` instead of `ocds-`, and encoding characters as necessary.

However, if you mean for the `ocid` to be dereferenceable, then that would be a more significant change, which has a wider range of concerns. A first concern is that OCDS requires releases to be published within packages, and so shouldn't be dereferenceable outside the context of a package. (Packages already have URLs as identifiers.) As such, OCIDs can't be URLs.

**Comment by jpmckinney** [comment]
Given that this is an issue that can only be resolved in a version 2.0 (which is not presently scheduled), and given no engagement by others on the issue, I will close it for now. When we start on version 2.0, there will be a significant effort to solicit ideas from the community – like this one.
