### ISSUE TITLE
Tender: Estimated size of the total value of the procurement

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#773]
Here in the Republic of Kosovo, we have the procurementValue field. This field's a codelist for the expected value of the contract. The values are:
                

1. Vlerë e madhe (Big value)
2. Vlerë e mesme (Medium value)
3. Vlerë e vogël (Small value)
4.  Vlerë minimale (Minimal value)

This should be a closed codelist and it's good for showing the expected value of the coming contract from a codelist.

**Comment by jpmckinney** [comment]
@leobaz We typically model the expected value as a number (or a pair of numbers for the minimum and maximum) rather than a codelist, and I haven't seen any other jurisdiction taking this approach. I therefore recommend creating a [local extension](http://standard.open-contracting.org/latest/en/extensions/developing/) for this concept. I also recommend using a term like `estimatedSizeOfValue`, to reserve terms like `estimatedValue` for numbers.
