### ISSUE TITLE
Tender: Whether the procedure is accelerated

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#775]
The applicationDeadlineType is for the deadline for accepting bids. This is a codelist but there are only 2 values:

- The deadline is normal (Afati 
			kohor normal)

- The deadline is shortened (Afati 
			kohor i shkurtuar)

This should be a closed codelist, but if you have any other values in mind we can add it.

**Comment by jpmckinney** [comment]
Most jurisdictions (and I assume Kosovo) have a minimum time period between the publication of a tender notice and the deadline for accepting bids. In OCDS, this time period is expressed as `tender.tenderPeriod` (using either `durationInDays` or a pair of `startDate` and `endDate`). If the period is the same or longer than the minimum, then the deadline is 'normal'; if it is shorter than the minimum, it is 'shortened'. We recommend that this information be encoded using `tenderPeriod`.

If you nevertheless need to publish this code, we recommend creating a [local extension](http://standard.open-contracting.org/latest/en/extensions/developing/), with a field named `isAcceleratedProcedure` that has a boolean value (instead of a two-option codelist).

**Comment by jpmckinney** [comment]
Note, we created this extension to meet EU disclosure requirements: https://github.com/open-contracting-extensions/ocds_procedure_extension
