### ISSUE TITLE
Tender: Main item classification

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#778]
Every service is represented by a number based on the FPP(Common procurement vocabulary).

For example  if the services provided are medical equipments then we use number 90.

**Comment by jpmckinney** [comment]
If the object of procurement is split into items, you can set that number using `items.classification` (items appear under tender, award and contract).

Otherwise, there is a [proposal for an extension](https://github.com/open-contracting-extensions/european-union/issues/15) as part of EU work, which would add a `tender.classification` field, whose value is a [Classification](http://standard.open-contracting.org/latest/en/schema/reference/#classification) object.
