### ISSUE TITLE
Discussion: Better understanding of how OCDS data is integrated into BI tools

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#791]
A government might have a requirement that, if a tender notice is changed within five days of the submission deadline, then the submission deadline must be extended. If the government is using `tenderPeriod` to identify slow procedures (e.g. using a business intelligence tool), they might unnecessarily raise flags if they don't account for such extensions.

A natural response is to add a new field to assist in disambiguating these scenarios. According to the release/record model, the correct response is to instead e.g. check for a `tenderUpdate` release that changed the tender period and/or use the `tenderPeriod` from an earlier release. However, most connections to BI tools don't access prior releases.

We should gain a better understanding of how BI tools are presently being implemented, to understand whether the issue is with OCDS or with how tools are using it.

From Kyrgyz Republic and Belarus reviews.

**Comment by MusicMaker1337** [comment]
BI tools usually use _compiled_ releases. The workflow is as follows:
1. The BI tool downloads all compiled releases available at the moment of download and captures the latest modification date among all releases;
2. Some changes occur in the e-PPS, which, in turn, make changes to some of the compiled releases. Any change in a compiled release resets its modification date. It leads to a fact that after any changes are made in the e-PPS, there will be some releases which have a modification date _greater_ than the date memorized by the BI tool;
3. The BI tool downloads all the releases which have a modification date greater than previously memorized, then the BI tool again captures the latest modification date. It is like the BI tool periodically asks a question "any changes since my last visit?";
4. The BI tool updates its data. All the changes in already existing data are rewritten.

**Comment by jpmckinney** [comment]
@MusicMaker1337 My understanding was that, in Belarus, custom `tag` values were used, because the BI tool needed to distinguish events. However, the compiled release, in most other publications, doesn't have a meaningful tag. Can you remind me how tags are being used, with an example?

**Comment by jpmckinney** [comment]
From OCP's experience implementing BI tools, there have been no insights re: changes to the standard, so closing.
