### ISSUE TITLE
Personal identifiers

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#801]
In some countries, as in Honduras and Colombia, some of their tenderers and suppliers have as identifier the ID number, passport or residence card number. Currently the standard documentation says that:

"Organization identifiers should be drawn from an existing organization identifier list. The scheme field is used to indicate the list or register from which the identifier is drawn. This value should be drawn from the Organization Identifier Scheme codelist." [1]

And:

"The Organization Identifier Scheme currently uses the codes from org-id.guide." [2]

But the personal identifiers cannot be included in the org-id.guide site, because it only publishes organization identifiers, not personal ones.

How they should publish these identifiers? 

Refs: [1] http://standard.open-contracting.org/latest/en/schema/reference/#identifier
[2] http://standard.open-contracting.org/latest/en/schema/codelists/#organization-identifier-scheme

Honduras Examples:

- ID number_ http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=OAAAADIAAAAwAAAAMQAAADcAAAA%3d-344y8BF%2fMHE%3d
- passport:  http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=NwAAADcAAAA3AAAAMgAAADkAAAA%3d-2Lgi74%2fBkcQ%3d
- residence card number: http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=NwAAADYAAAA1AAAANQAAADMAAAA%3d-OcYuYrpmGFs%3d

**Comment by jpmckinney** [comment]
I think they would set their own scheme instead of one from org-id.guide. @duncandewhurst Would you agree, and have any suggestion as to how they should identify the scheme (e.g. to not conflict with potential future org-id schemes)?

**Comment by duncandewhurst** [comment]
I agree, personal identifiers are outside the scope of org-id.

BODS has an approach to personal identifiers documented [here](http://standard.openownership.org/en/schema-beta-2/schema/guidance/identifiers.html?#shared-identifiers) and the description of the `identifier/scheme` field includes the following guidance for personal identifiers:

> the scheme should have the pattern {JURISDICTION}-{TYPE} where JURISDICTION is an ISO 3-digit country code and TYPE is one of PASSPORT, TAXID or IDCARD

In the interests of cross-standard compatibility I suggest we follow this approach. For Honduras, another TYPE is required for residence card, I suggest using RESCARD.

@ScatteredInk opened an issue recently to discuss improving documentation and examples around personal identifier schemes (including whether we need person-id.guide): https://github.com/openownership/data-standard/issues/131

For OCDS, the current wording of the schema descriptions for `identifier` and its properties only refer to organization identifiers and org-id.guide, so we should consider updating these to cover personal identifiers too. We should also provide guidance on disclosure of personal identifiers, e.g. from BODS:

> **Warning**
> 
> When using BODS to provide open data, it is important to ensure any person identifiers are suitable for publication under national laws and data protection frameworks.
> 
> Most of the identifier types listed below are not suitable for publication as part of an open dataset.

@yolile since these identifiers are already published in Honduras, I assume appropriate consent/authorization has been given for their disclosure.

**Comment by duncandewhurst** [comment]
This has come up again Guatemala, see https://github.com/org-id/register/issues/379 and https://github.com/org-id/register/issues/378

**Comment by jpmckinney** [comment]
Noting that we should allow name fragmentation as discussed in #637.
