### ISSUE TITLE
Party Legal Representative

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#802]
## Problem
In Colombia they have the information about the legal representative of a supplier. That information is different from the contact point information.

## Proposals

1. Add an entry in the parties array with a new role "legalRepresentative" and use the memberOf extension to point the supplier
1. Add a field in the party/details extension 
1. Add a new legalRepresentative block at the same level that contactPoint

**Comment by jpmckinney** [comment]
The second option is the safest to use for now. The field can be named `legalRepresentative` and the value can be a `ContactPoint` object.

The first option is not semantically correct, as parties are organizations, not people, and the legal representative is a person. The third option is possible, but we need more evidence from more countries to pursue it.

**Comment by yolile** [comment]
The information that they have about the legal representative is their name, identifier and identifier scheme, so the ContactPoint object doesn't seem to be the most appropriate

**Comment by jpmckinney** [comment]
@yolile We seem to be crossing wires because conversations are occurring here and in CRM-4092, where I explained that an `identifier` field can be added to the `ContactPoint` object (whether as a simple additional field or as an extension). As this request is from only a single publisher, let's resolve the issue in one place first (the CRM). We can open an issue here once there's any public interest and/or once we have a clearer proposal.

**Comment by yolile** [comment]
Paraguay DNCP now also wants to publish this information. They have, for each organization, a list of legal representatives including:
- Personal national identifier
- Name and last name
- Job position

The legal representative is a different concept from the organization's contact point.

**Comment by jpmckinney** [comment]
I think maybe this should be brought up in #883 and this can be closed again.
