### ISSUE TITLE
Update Support & Governance section of documentation

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#819]
Just noticed this section is out of date: 

http://standard.open-contracting.org/latest/en/support/governance/#overview 

Proposed new text: 

OCDS was initially developed through a year long iterative process, resulting in version 1.0 in November 2014. 

In 2016, we undertook the first upgrade of the OCDS to version 1.1 following the OCDS governance process outlined below. The full upgrade report can be found [here](https://docs.google.com/document/d/1mpLX7R9S_DyPTPZFtoAh0Gt0IHZLDt4WZbM-nzy8xUY/edit). It outlines all of the changes made, and the process that was followed.

**Comment by jpmckinney** [comment]
Noting that this will be removed in 1.1.4 to eliminate misleading content (i.e. suggesting 1.1 hasn't yet occurred), and can be considered for re-integration into the history page in 1.1.5:

----

## Overview

OCDS was initially developed through a year long iterative process, resulting in version 1.0 in November 2014. Over 2015/16 many organizations have been piloting use of the standard. 

In 2016, we are working towards a first revised version of the standard. This is intended to fix a number of bugs identified through wider adoption of the standard over recent months, and will add a number of features which did not make it into 1.0. 

This document outlines a process for management of changes to OCDS during the move from version 1.0 to 1.1. 

Following this revision process, the Open Contracting Partnership will evaluate either:

* Continuing to operate a self-managed revision process;

* Submitting OCDS into a formal standards process, such as W3C community group, OASIS or other body;

We welcome views on this approach of short-term self-managed revisions, followed by exploration of formal standards processes.

**Comment by jpmckinney** [comment]
It's removed in 1.1.4. Moving to 1.1.5 milestone in terms of integrating into history section, if needed.

**Comment by jpmckinney** [comment]
While reviewing this page, we can also compare to 360Giving, which has much the same structure and content: http://standard.threesixtygiving.org/en/latest/governance/

**Comment by jpmckinney** [comment]
While splitting the normative from the non-normative content of the governance page, we can also add the names of the members of the governance group to the non-normative content (CRM issue 4842).

**Comment by LindseyAM** [comment]
Proposed revision to the Support & Governance section is here: https://docs.google.com/document/d/1ZV-PcIx6P7puwz9Pu-eO13zKRwcOX23DJxXb9E4sF7U/edit#heading=h.fd1knlcyqxi2

**Comment by jpmckinney** [comment]
Thanks, @LindseyAM! I see you edited the full section, not just the page linked from the issue description: http://standard.open-contracting.org/latest/en/support/governance/

My plan for the full section is:
* [x] Move Governance under Schema Reference, so that all normative content is in the same section
* [x] Replace Tools with a link to the [Tools Directory](https://www.open-contracting.org/resources/open-contracting-tools-directory/) and continue to improve that resource, to avoid having to update the tools in two places. Alternately, move the Tools Directory here, and have the OCP website link to this page instead.
* [x] Merge History of OCDS and Appreciation into one page ~~with a narrower scope called Upgrade History. Either integrate this content into the Changelog, or have it as a page under Schema Reference to describe only 1.x upgrades (with the Changelog as a sub-page).~~
* [x] Rename "Support and governance" to focus on support (actual name depends on how we rename the rest of the top-level navigation).

For your document, it'd be easier to integrate if you make a copy/duplicate (check the box about copying comments, etc.) and then remove all content except for the content that you want to appear on the single Governance page. We can then address other sections in new issues, where we can also discuss the relevant part of the plan above (making copies of the document as needed).

**Comment by jpmckinney** [comment]
I made the copy I proposed here: https://docs.google.com/document/d/1aJm1YTKC5Eh3NNKjJa9UGxUusS95cxvareRlUiJ6rto/edit
