### ISSUE TITLE
Deprecate initiationType

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#821]
The current definition ("An open competitive bidding or tendering to form contracts") is overly restrictive; this definition can only be respected if `tender/procurementMethod` is 'open'.

----

More broadly, the design reason for the `initiationType` field is best described here: https://github.com/open-contracting/standard/issues/111#issuecomment-61224721

In other words (and from memory), this field exists because it was anticipated that the `tender` block would be inappropriate for some types of contracting processes. This field was added in order to indicate to data users that different features would be available within the data for such processes. For example, if `initiationType` were 'lottery', then data users would look for a `lottery` block instead of a `tender` block.

However, in practice, the `tender` field has been implemented according to its broad definition ("The activities undertaken in order to enter into a contract."), i.e. for initiation/solicitation in general. This seems like the right approach, instead of having a different block for each kind of contracting process, which makes data use harder. To my knowledge, implementers have not yet encountered contracting processes for which the `tender` block is wholly inappropriate (processes with multiple stages have issues, but the `tender` block is still appropriate for at least one stage).

A related issue might therefore be to re-assess the design approach behind the `initiationType` field more broadly. In the meantime, besides correcting the code, we might want to treat the field and codelist as 'legacy'.

cc @duncandewhurst

**Comment by JachymHercher** [comment]
Since

> To my knowledge, implementers have not yet encountered contracting processes for which the tender block is wholly inappropriate (processes with multiple stages have issues, but the tender block is still appropriate for at least one stage).

and since plans to deal with multiple stage procedures do not seem to involve `initiationType`, I think treating it as legacy / deprecating it sounds like a good appraoch. 

(For a moment I thought whether it couldn't be used for some very different use cases, e.g. if you want OCDS to cover government asset sales, but even if yes, a new field would still probably be less confusing for that purpose.)

**Comment by jpmckinney** [comment]
I am happy to deprecate `initiationType`, as it has not been used for its designed purpose. OCDS for PPPs changes the mandatory code to 'ppp', but this serves no real purpose.

**Comment by duncandewhurst** [comment]
I'm also happy to deprecate it.

OCDS for PPPs changes the mandatory code to alert data users to the different fields used in the profile (`publicAuthority` instead of `buyer` etc.) although the `tender` block is still present. Once https://github.com/open-contracting-extensions/public-private-partnerships/issues/236 is done, that won't be an issue any more and data users can use the `extensions` array in the package metadata to determine what additional fields to expect.

**Comment by jpmckinney** [comment]
Also, we should remove/replace all mentions of "initiation" in the documentation. Except for the codelist, all of these occur in non-normative text, so that change can be done in a 1.1 pull request.
