### ISSUE TITLE
documentType: Deprecate contractSchedule in favor of contractAnnexe

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#870]
'contractSchedule' was originally:

> Schedules and milestones: (no description)

A description was added in #347 (1.1.0)

> Schedules and milestones: Documentation setting out key milestones and schedules. Structured versions of this information may be modelled using the milestones block.

Then there was discussion in https://github.com/open-contracting/standard/issues/386#issuecomment-289475615 that "schedule" should mean "annexe" not "timetable".

So, the description was updated in #473 (1.1.1):

> Contract schedules: Any document which contains additional terms, obligations or information related to the contract, such as a schedule, appendix, annex, attachment or addendum.

But now, we have two codes for the same thing. 'contractAnnexe' is:

> Annexes to the Contract: Copies of annexes and other supporting documentation related to the contract.

**Comment by ColinMaudry** [comment]
Why not the other way around, and deprecating 'contractSchedule'? That may be because I'm French, but the word 'annex' sounds more universal to me than 'schedule' (as defined on [the page](https://weagree.com/drafting-principles/4-structuring-the-transaction-documents/4-2-schedules-annexes-and-exhibits/) referenced in [this comment](https://github.com/open-contracting/standard/issues/386#issuecomment-289475615)). The word 'schedule' has misled even @timgdavies!

**Comment by jpmckinney** [comment]
Good suggestion. We can also go the other way around.

I originally proposed to keep contractSchedule, because it was the term whose description had expanded more in scope over time, but we can similarly update the description of contractAnnexe.

A small disadvantage of contractAnnexe is that it uses British spelling (annexe) whereas we use American spelling (annex) for other terms like organization.

We can check the popularity of each term, and decide that way.

**Comment by ColinMaudry** [comment]
How do we check that? I don't think I have access to your OCDS data vault. Otherwise I'd gladly check myself.

**Comment by jpmckinney** [comment]
I was thinking the popularity of each term in public usage (legal references, procurement discussions, whatever). 

In terms of each code's use, according to [this spreadsheet](https://docs.google.com/spreadsheets/d/1FTIwVceAb9-bfwHBjH07_MPS0JUVU3vfvRH6WVMQCbU/edit#gid=812686904) (you might not have access, but at least I'll be able to find it again), contractAnnexe has 222,437 occurrences and contractSchedule has 4,579	occurrences, but this isn't disaggregated by publisher (e.g. maybe one big dataset is responsible for all contractAnnexe but five small datasets are responsible for contractSchedule, in which case we might prefer contractSchedule if the decision were uniquely based on code usage).

**Comment by ColinMaudry** [comment]
The article linked in https://github.com/open-contracting/standard/issues/870#issuecomment-766861696 says:

> English law firms seem to work with schedules, whilst American firms sometimes prefer attachment or exhibit).

I made a few Google searches:

- ["procurement "schedule to the contract""](https://www.google.com/search?hl=en&q=procurement+%22schedule+to+the+contract%22) returns mainly Irish, British, Indian, Canadian and Australian results (1,970,000 results)
- [ "procurement "annex to the contract""](https://www.google.com/search?q=procurement+%22annex+to+the+contract%22&hl=en&start=50) returns results from everywhere (1,050,000 results)

**Comment by jpmckinney** [comment]
We should avoid a Commonwealth of Nations bias where possible, so let's go with annex, with the Annexe spelling for backwards compatibility.

**Comment by ColinMaudry** [comment]
That would mean we keep and slightly adapt the description of contractSchedule, because it's the one that been improved over time, and use it for contractAnnexe.

I propose the following:

- deprecate contractSchedule, with its current description, indicating data publishers should rather use contractAnnexe
- copy and adapt  the description of contractSchedule for contractAnnexe:

> Any document which contains additional terms, obligations or information related to the contract, such as a **annex**, appendix, **schedule**, attachment or addendum.

(I've just switched annex and schedule in the list)

**Comment by jpmckinney** [comment]
That sounds fine to me!
