### ISSUE TITLE
Add tender.datePublished field

### ISSUE THREAD

**Issue by juanpane** [open-contracting/standard#892]
### The problem

Many countries have the information on when the tender was published. We are currently working specifically with Honduras and Paraguay, and both countries have this information available for publishing.

Having this information in a easy way to access it can have many benefits, for instance, to be able to compute some indicators that will say how many days a potential bidder has to prepare an offer (tender.tenderDate.endDate -  tender.datePublihsed).

Currenly there is no easy attribute that can be used to publish this information. In the past [there was a discussion](https://github.com/open-contracting/standard/issues/261) on how to do this, but the proposed solution is not very straigth forward and is not simple

### Proposed solution

The proposal is to create a simple extension with one attribute called **tender.datePublished** of type date which can then be used by publishers.

**Comment by jpmckinney** [comment]
Thanks! I've scheduled it for inclusion in OCDS 1.2.0.

**Comment by duncandewhurst** [comment]
This information is also available in PhilGEPS

**Comment by duncandewhurst** [comment]
The PhilGEPS data also includes a published date for the award notice.

Other than understanding how timely publication of the award notice was (after the actual date of the award) I am not sure how important it is to have an explicit field for this information over the approaches discussed in #261, but for consistency with `tender.datePublished` we should consider whether to add `award.datePublished`

**Comment by duncandewhurst** [comment]
The [Himachal Pradesh Govt Tenders Information System](https://hptenders.gov.in/nicgep/app) includes a `publicationDate` field for tenders.

**Comment by jpmckinney** [comment]
Noting that this extension was published and registered a while ago (CRM-4909): https://extensions.open-contracting.org/en/extensions/tender_datePublished/master/

**Comment by duncandewhurst** [comment]
The field name (`datePublished`) and description ("The date when the tender was published.") in the extension seem to be backward-looking only.

Some publishers wish to disclose the expected publication date of the tender, which may still differ from the date from which the tender is open for submissions, e.g. SIF's SOURCE platform includes a 'tender_publication_taget_date` field.

We could instead use `publicationDate` (which would conform better to the schema style guide) and also improve the description so that it does more than restate the title, e.g.

path | title | description
-- | -- | --
`publicationDate` | Publication Date | The date on which the tender notice or documentation is published

**Comment by jpmckinney** [comment]
The intended date of publication of a notice is captured by `futureNoticeDate` in the [communication](https://extensions.open-contracting.org/en/extensions/communication/master/) extension.

`tender.datePublished` matches `Document.datePublished`, `Contract.dateSigned`, `dateModified` (Milestone and Document) and `Milestone.dateMet`, as well as Schema.org.

**Comment by duncandewhurst** [comment]
Ah, I was not aware of that extension. Bring on https://github.com/open-contracting/standard/issues/1074.

We should add something to the schema style guide about date fields being an exception to the 'put the qualifier first' rule.

**Comment by jpmckinney** [comment]
> We should add something to the schema style guide about date fields being an exception to the 'put the qualifier first' rule.

Done in above commit.

**Comment by Ben-Hickling** [comment]
I'm re-opening this thread as requested by the OCDS Helpdesk to note that in the UK we plan to use both `tender.datePublished` and `awards.datePublished`, to respectively capture the dates that the tender and award were published. We will create a new extension for the latter if necessary. This will allow this information to be included in tenderUpdate and awardUpdate releases where they wouldn't be otherwise. We need to cater for analysis tools that only hold the latest release for each procurement (so the awardUpdate overwrites the award, for example).

**Comment by jpmckinney** [comment]
Hi @Ben-Hickling, can you create a new issue? This issue was about adding `tender.datePublished`, although Duncan did add a comment about an award datePublished. At any rate, they are separate fields, and deserve separate issues.

**Comment by Ben-Hickling** [comment]
@jpmckinney I've now created #1456 to discuss `awards.datePublished`.
