### ISSUE TITLE
Tender: Guarantees from the Bidder in order to preserve the Offer

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#900]
In Paraguay, the procuring entity have to define some information about the guarantees that the tenderers should provide. This guarantee is required to ensure that the offers made by the tenderers during the tender stage are kept if they are awarded.

The available data is:
- the percent of the guarantee (a value, could be 5, 10, etc % of the amount)
- guarantee type (policy, sworn statement or bank guarantee)
- guarantee period
- guarantee amount

Then, we have the data about the guarantees that the tenderers actually presented, this data is only available as structured data in the auctions, in traditional process we only have this data as documents, but the data that we have from the auction system is:

- guarantee number
- guarantee type
- guarantee entity (for example the insurer)
- date of issue
- guarantee period

For model this, we could reuse the existing `Guarantee `object that exists in the [guarantees extension](https://github.com/INAImexico/ocds_guarantees_extension), changing the `Guarantee` object description to be more generic and less specific about that the Guarantee is for the contract. Also we need to update the obligations code list to include the type "`preserveOffer`", and also the type codelist to include policy, sworn statement and bank guarantee. Also we need to add a `date `field and a `percent` field. And maybe allow that the '`guarantor `' doesnt have to be a OrganizationReference, so it doesnt have to be in the parties array. 
After that, maybe we can include the fields `"tender/requiredGuarantee"` and `"bid/guarantee"`

The legal definition of the guarantees can be found at [Article 39 of the paraguayan public procurement law (page 38)](https://www.contrataciones.gov.py/documentos/download/marco-legal/12760)

**Comment by PaulBoroday** [comment]
Always was wondering why not to use [requirements](https://github.com/open-contracting-extensions/ocds_requirements_extension) for this need?

**Comment by yolile** [comment]
I think you are rigth, we can use that extension, but I'm going to open an issue to add "bid" to the relatesTo codelist.

**Comment by PaulBoroday** [comment]
I don't think you should do it. 'relatesTo:tenderer' fits in this case - guarantees (both bid and contract execution) are requirements against tenderer, prescribes him to provide additional service. Its the same as a warranty requirement. Isn't it?

**Comment by yolile** [comment]
I'm not sure. The tenderer example at the extension is about "Number of years the bidder has been trading" but in this case, the requirement is about the bid that the tenderer is doing, not about the tenderer it self

**Comment by PaulBoroday** [comment]
Fare enough ) But let's take a look on this from the [definition](https://definitions.uslegal.com/b/bid-guarantee/). It looks more like 'corporate commitment' rather than bids' attribute. On another hand, technically you will have _requirementResponse_ related to guarantee _requirement_ inside your _bid_. And, again, technically, all the _criteria_ in this way or another related to _bid_. I mean - it's obvious )

**Comment by jpmckinney** [comment]
I think @PaulBoroday is right with respect to all the requirements being about the bid, even if implicitly and/or indirectly.

Regarding warranties, my understanding is that warranties are generally for items (e.g. ~~motor will not fail within 3 years~~ if motor fails within 3 years, it will be fixed or replaced at no cost).

Guarantees are different from warranties. For [example](https://publicprocurement.fandom.com/wiki/Bank_guarantees), the buyer might require a bank guarantee for the value of the contract. If the supplier defaults on their obligation, the buyer can invoke the guarantee to get that value in cash.

Such a guarantee is directly about the bid, as the value of the guarantee depends on the value of the bid, not on the tenderer/bidder or individual items.

The question then is whether to just not set anything in `relatesTo` (i.e. make it implicitly about the bid) or to set it to 'bid'. The disadvantages I see to setting it to 'bid' are:

1. If the semantics are already that requirements are about the bid (and can further relate to things related to the bid like an item or the tenderer), then it's redundant to set it to 'bid'.
1. Since all requirements are implicitly about the bid, publishers might incorrectly set it to 'bid' when what they mean is 'item' or 'tenderer'. 

On the other hand, the disadvantages to not setting it to anything when it relates to the bid are:

1. Users might be unsure whether the requirement relates to the 'bid', or if the publisher simply didn't express that it's actually related to the item or tenderer.

I think the latter disadvantages are worse, so it seems reasonable to add the code to the codelist.

cc @duncandewhurst since he wrote the extension.

**Comment by PaulBoroday** [comment]
'Warranties' is not the main topic of this discussion, but once we touch it, my understanding a bit different. The main idea why to request any warranty is not to receive a sort of promise that motor will not fail within 3 years. No one can guarantee you that - your motor can fail tomorrow. Main idea is to have a suppliers' commitment that if supplied motor will fail during a certain period of time, this supplier will take responsibility (according to his commitment) to fix or replace this broken thing...

**Comment by jpmckinney** [comment]
Yes, I abbreviated the warranty description as it's not the subject here – it's more accurate to write it as you described.

**Comment by jpmckinney** [comment]
@yolile What did you end up doing in Paraguay?

**Comment by yolile** [comment]
We used the requirements extension without setting the `relatesTo` field, example: https://www.contrataciones.gov.py/datos/api/v3/doc/ocds/releases/id/302758-servicio-flete-fluvial-clinker-yeso-caliza-otros-1-1592913681.273
