### ISSUE TITLE
Initiation Type: addition of planning to the closed code list (suggestion)

### ISSUE THREAD

**Issue by daniel-clair** [open-contracting/standard#921]
Sometimes most of supply arrangements (contracts) and many standing offers are not the results of tenders; instead, the vendor might be invited off a (rotating) source list to submit a standing offer.

Currently initiationType has one possible value "tender". Please consider the possibility of adding planning to the code list.

**Comment by jpmckinney** [comment]
@daniel-clair The future of the `initiationType` field is somewhat uncertain, and its semantics might be changed #821. For your implementation, I think it is fine to leave it as-is.

Regarding standing offers and supply arrangements, these are called 'framework agreements' in other parts of the world. A standing offer is like a framework agreement with 'direct call-offs'. My understanding of supply arrangements is that it is like a framework agreement with 'mini-competitions'.

We have [existing guidance](http://standard.open-contracting.org/latest/en/implementation/related_processes/) on how to model framework agreements in OCDS, and there are [proposed changes](https://github.com/open-contracting/standard/pull/890) to improve that documentation.

In the next version of OCDS (1.2.0), we are considering changes so that all mini-competitions are treated as being within the same 'contracting process' that established the framework agreement, instead of separate processes #909.

**Comment by jpmckinney** [comment]
Superseded by linked issues.
